### ISSUE TITLE
Image Uploads not showing

### ISSUE THREAD

**Issue by HostOnNet** [ushahidi/platform#2069] opened 2017-09-20 04:06 UTC
### Expected behaviour

After installation, image upload should work.

### Actual behaviour

I installed ushahidi-platform-release-v3.7.2-rc.2.tar.gz  as per instruction at 

https://www.ushahidi.com/support/install-ushahidi

But image are not displaying. Files get uploaded to  platform/application/media/ folder. When i check page source code, it have URL like

https://www.mydomain.com/media/uploads/5/9/59c1bd1b049ff-img_0560.jpg

I got it fixed by

```
cd /var/www/html
ln -s platform/application/media/
```

What is the correct way to do this ?

### Steps to reproduce the behaviour/error

Just do fresh install as per 

https://www.ushahidi.com/support/install-ushahidi

Upload an image.

**Comment by jshorland** [comment] 2017-09-20 04:39
cc: @Angamanga can you try to reproduce this on OSS?

**Comment by jshorland** [comment] 2017-09-20 05:15
@angamanga confirmed that image upload is working on qa.ushahididev.com -- http://qa.ushahididev.com/posts/6552

**Comment by rjmackay** [comment] 2017-11-01 23:57
Did your deployment have a media/uploads folder? Was the image actually saved anywhere?

**Comment by tuxpiper** [comment] 2018-01-24 11:05
Probably a duplicate of ushahidi/platform-release#5 which has been fixed since . Closing since the reporter has been silent for a few months now.

**Closed by tuxpiper** 2018-01-24 11:05 UTC
Labels: Bug
