### ISSUE TITLE
Survey and Task fields need to have an internal/external setting

### ISSUE THREAD

**Issue by natmanning** [ushahidi/platform#1514] opened 2016-11-18 19:40 UTC
### Expected behaviour

I want to be able to make certain Survey fields and certain Task fields only visable to admins, and not the public.

### Actual behaviour

All Survey fields and Task fields are automatically public.

### Steps to reproduce the behaviour/error

**Comment by jshorland** [comment] 2017-01-26 11:22
Duplicate of #1511. Closing.

**Closed** 2017-01-26 11:22 UTC
