### ISSUE TITLE
API server rejects incoming message from existing targeted survey contact

### ISSUE THREAD

**Issue by kinstelli** [ushahidi/platform#2727] opened 2018-04-11 16:37 UTC
### Expected behaviour

- Sending a message via POST to http://targetedsurveytesting.api.v3-qa.ush.zone/sms/testservice
with secret, message, from as key/value pairs should return `{"payload":{"success":true,"error":null}}`

### Actual behaviour

- Sending a message via POST to http://targetedsurveytesting.api.v3-qa.ush.zone/sms/testservice
with `secret`, `message`, and`from` as key/value pairs only returns `{"payload":{"success":true,"error":null}}` if the number is not one of the original targeted survey contacts.

Instead it returns:
 `{"payload":{"success":false,"error":"mysqli::mysqli(): (HY000\/2002): No such file or directory","code":2,"class":"Database_Exception","file":"\/var\/www\/platform\/application\/classes\/Database\/MySQLi.php","line":59}}`

#### Where does this issue happen?
- [x] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [x] Ushahidi's QA environment

**Comment by kinstelli** [comment] 2018-04-11 21:58
@rowasc - I'm trying to have a look at the code, but I'm not sure I fully understand the intent of this line:
 https://github.com/ushahidi/platform/blob/1b5505df4a540c782ee4a2f9b9cd8ed929d01112/src/Core/Usecase/Message/ReceiveMessage.php#L184 

It seems to be testing against the brand new incoming message, but I think it's meant to look at the most recent _outgoing_ message. Am I understanding that correctly? 

In any case, it's returning a failure here when a new message comes in. Let me know if that's what it's supposed to do.

**Comment by rowasc** [comment] 2018-04-12 01:25
@kinstelli this is looking for an outgoing message. If it doesn't find one, it complains
About the error itself, I need to check since the error you are receiving is not correct.

**Comment by rowasc** [comment] 2018-04-12 17:14
@willdoran @kinstelli isn't {"success":true,"error":null}}  the correct response here? 
Also, I can't reproduce the error you mentioned (below)

{"payload":{"success":false,"error":"mysqli::mysqli(): (HY000\/2002): No such file or directory","code":2,"class":"Database_Exception","file":"\/var\/www\/platform\/application\/classes\/Database\/MySQLi.php","line":59}}

 Can you expand on the steps?

**Comment by rowasc** [comment] 2018-04-12 17:17
I just tested and got the message to change for the contact and the survey marked as finished  because there wasn't a new attribute to send. I also tested and was able to get the next attribute to be sent in a contact that had pending questions to answer.

**Comment by kinstelli** [comment] 2018-04-12 17:18
My original description might have been confusing. Yes, ` {"success":true,"error":null}} ` is the expected response.

I'll create a list of steps to try to replicate the issue in a few minutes. I was using http://targetedsurveytesting.api.v3-qa.ush.zone/sms/testservice

**Comment by rowasc** [comment] 2018-04-12 17:19
@kinstelli  just realized you are linking to a qa server...which branch are you testing? All of the incoming  message code is pending code review/merge.

**Comment by kinstelli** [comment] 2018-04-12 17:37
@rowasc 

If you send a POST to `http://targetedsurveytesting.api.v3-qa.ush.zone/sms/testservice` with:
`secret: howamisupposedtoknowitsasecret`
`message: whatever you want`
`from: 4045551213`

This should work and return success.

However, switch the payload to a phone number in the targeted survey, and it returns an error.
Send a POST to `http://targetedsurveytesting.api.v3-qa.ush.zone/sms/testservice` with:
`secret: howamisupposedtoknowitsasecret`
`message: whatever you want`
`from: 4045551212`

**Comment by willdoran** [comment] 2018-04-12 21:42
@kinstelli I think this is fixed can you confirm and close?

**Closed** 2018-04-12 23:14 UTC
Labels: API, Bug, P1 - Immediate
