### ISSUE TITLE
tasks and all information are completely visible to everyone

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1481] opened 2016-11-04 20:09 UTC
I thought tasks were supposed to be visible internally to logged in users only?

**Comment by rjmackay** [comment] 2016-11-09 03:51
This wasn't ever implemented: See https://github.com/ushahidi/platform/issues/1363

**Comment by rjmackay** [comment] 2016-11-16 03:30
Closing this. Not a bug..

**Closed by rjmackay** 2016-11-16 03:30 UTC
Labels: P0 - Unbreak now!
