### ISSUE TITLE
Consecutive user logins intermittently fail

### ISSUE THREAD

**Issue by kinstella** [ushahidi/platform#2459] opened 2018-02-02 17:05 UTC
### Expected behaviour
- Using a tool such as Postman, log in with known good credentials using a POST request
- Successful log in
- Log out
- Using a tool such as Postman, log in again with known good credentials using a POST request
- Successful log in

### Actual behaviour
- Using a tool such as Postman, log in with known good credentials using a POST request
- Successful log in
- Log out
- Using a tool such as Postman, log in again with known good credentials using a POST request
- A 400 Bad Request code is returned:
 https://<deployment>/oauth/token, with a server response of {"error":"invalid_request","error_description":"The user credentials were incorrect."}

##### Where
- [x] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [x] Ushahidi's QA environment
- [ ] Other (explain):

Aha! Link: https://ushahiditeam.aha.io/features/PROD-435

**Comment by willdoran** [comment] 2018-02-02 20:12
The login bug is most probably caused by an issue with the third party OAuth library that the API uses. The version we use is very very out of date. Upgrading to the latest version will take a certain amount of time given the changes between versions. The issue is likely to be solved by moving to the lumen version of the API. Fixing or upgrading the current lib is likely a waste of time as it will be redundant the moment the lumen branch is merged.

The time it would take to find and fix the issue is likely to be at least 1 week. Until the lumen branch is landed, the best course of action is to carefully coordinate demos of the dashboard and ensure whoever is demoing it, properly understands how/when the bug occurs so that they can avoid triggering it.

**Comment by webong** [comment] 2023-09-07 13:22
Close this issue as we now have the Laravel Passport handling Auth

**Closed by webong** 2023-09-07 13:22 UTC
Labels: Tech Debt, Codebase: API, Theme: Users and roles
