### ISSUE TITLE
Not possible to turn off notifications for saved search

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#1567] opened 2017-02-01 09:37 UTC
### Expected behaviour
When clicking on "Turn off notifications" on a search saved by someone else, the notifications should be turned off and the button "Get notifications" should be visible instead:

### Actual behaviour
Nothing happens, the text is still "Turn off notifications" and the notifications are not turned off.
Before clicking:
![screen shot 2017-02-01 at 10 30 05](https://cloud.githubusercontent.com/assets/8624777/22501574/aa4eb954-e869-11e6-9193-e4b5a6a71a68.png)
After clicking:
Should be: 
![screen shot 2017-02-01 at 10 32 16](https://cloud.githubusercontent.com/assets/8624777/22501587/bcf6f45e-e869-11e6-9b23-dc782fb7daae.png)
Is: 
![screen shot 2017-02-01 at 10 30 05](https://cloud.githubusercontent.com/assets/8624777/22501574/aa4eb954-e869-11e6-9193-e4b5a6a71a68.png)
 
### Steps to reproduce the behaviour/error
1. Log in
2. Choose a saved search made by somebody else
3. Click on button 'get notifications'
4. Click on button 'turn off notifications'

**Comment by jshorland** [comment] 2018-02-27 23:42
Can't reproduce. Closing.

**Closed by jshorland** 2018-02-27 23:42 UTC
Labels: Bug
