### ISSUE TITLE
[Grammarly] Roving whitespace movement when adding a new category.

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1796] opened 2017-06-12 10:54 UTC
I don't know how best to describe this, so i'll just show you!

![screenshot](http://i.imgur.com/LOluZI2.gif)

Steps to reproduce
* Log into your deployment
* Click on settings, then categories
* Attempt to create a new category.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-595

**Comment by jshorland** [comment] 2017-06-12 19:03
Haha weird!

**Comment by Angamanga** [comment] 2017-06-27 13:59
@aoduor I cannot reproduce this, which browser did you use when this happened?

**Comment by aoduor** [comment] 2017-06-27 15:12
Google chrome :(

**Comment by rowasc** [comment] 2019-06-09 22:50
noting this is a grammarly thing, it's happened to me both in platform and other places. I suspect it might have something to do with either angular or our input types / css but it definitely comes because of the plugin

**Comment by Angamanga** [comment] 2019-09-26 07:27
I finally could reproduce this! It definitely happened after installing Grammarly!

**Comment by rowasc** [comment] 2020-10-09 17:06
I'm tagging for community task and maybe someone can do some research to fix it (and we can help)

**Comment by emalindahk** [comment] 2020-10-11 15:47
Hi, I'm Emmah I would like to work on this for my outreachy contribution

**Comment by Angamanga** [comment] 2020-10-12 08:35
@emalindahk I assigned you to this one: https://github.com/ushahidi/platform/issues/3315

**Comment by emalindahk** [comment] 2020-10-13 06:14
@Angamanga I cannot reproduce this issue, I'm using Chrome everything seems to be okay.

**Comment by Angamanga** [comment] 2020-10-13 09:33
@emalindahk You need to have the Grammarly-extension for Chrome installed to see it: https://www.grammarly.com

**Comment by emalindahk** [comment] 2020-10-13 09:49
![ezgif com-optimize](https://user-images.githubusercontent.com/12936055/95845148-7cf76700-0d52-11eb-871b-a7ddc444f17b.gif)

**Comment by emalindahk** [comment] 2020-10-13 09:50
@Angamanga I have the extension, this is what is happening on my chrome

**Comment by Angamanga** [comment] 2020-10-14 09:05
@emalindahk Hm interesting! Thank you for looking into it. It seems like Grammarly has fixed this issue for us :) Closing this.

**Closed by Angamanga** 2020-10-14 09:05 UTC
Labels: Bug, Codebase: Client, Community Task, Theme: Categories
