### ISSUE TITLE
Activity time filters not working

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#1169] opened 2016-06-10 18:12 UTC
### Expected behaviour

When I select show activity by last week, I will see activity
### Actual behaviour

No activity is shown
### Steps to reproduce the behaviour/error

Go to QA site, go to activity, select time filter of last week

**Comment by rjmackay** [comment] 2016-06-13 03:00
I think thats just because there aren't enough data points. If theres only going to be  a single point on the timeline.. we don't show anything.

**Comment by rjmackay** [comment] 2016-06-13 03:04
Can you retest? Bearing in mind that time chart graphs the post creation date, if you haven't created many posts this week the chart is probably not going to show anything. 1 week granularity is almost

**Comment by jshorland** [comment] 2016-06-13 03:36
On qa.ushahididev.com, I have added posts today and published those posts, but activity this week still shows no data.

**Comment by jshorland** [comment] 2016-06-13 03:37
Further, If you switch it to "all time" you'll see the post count I've created today.

**Comment by zhalloran** [comment] 2016-06-13 13:49
Looking through the code now. Don't fully understand how filters are implemented against posts, but my guess would be that the created-before value is the issue (i.e. the filter behavior is starte date <= post date < last date). What we probably want is start date <= post date <= last date. Just not sure where to make that change in the code. @rjmackay @jshorland

**Comment by rjmackay** [comment] 2016-06-13 21:07
Sorry I should have comment on that before I logged off last night. The time filters work fine AFAIK, but we don’t show a chart with less than 3 data points. When you view by week.. theres very little data

**Comment by zhalloran** [comment] 2016-06-13 21:08
No, the issue is that the end_date cuts off at 00 hours for the selected end date. So for example, if I select today as the end date, I will exclude any posts from today that occurred after 00 hours.

**Comment by rjmackay** [comment] 2016-06-13 21:19
oh. It shouldn't be putting an end date on at all... I'll check.

**Comment by zhalloran** [comment] 2016-06-13 21:25
Sorry. To clarify, if you select week, it doesn't append created_before. I guess I discovered another bug related to created_before for timeline and map filters. My mistake.

**Comment by rjmackay** [comment] 2016-06-13 21:41
... ok. Right so what you saying is on map and timeline (and activity to?) if you specify filter dates.. its uses start of day, not end of date on the created_before date?

**Comment by zhalloran** [comment] 2016-06-13 23:53
yes, that's correct

**Comment by jshorland** [comment] 2016-06-14 00:29
Do I need to retest this @zhalloran ?

**Comment by zhalloran** [comment] 2016-06-14 00:43
Not as yet, @jshorland. Working on something else right now.

**Comment by rjmackay** [comment] 2016-06-14 02:18
@jshorland Fixed some issues related to this. Retest?

**Comment by jshorland** [comment] 2016-06-14 02:58
Retested: no clear change to the way the charts change when I switch from all time, to this week, to this month. This month and this week are still "no data"

**Comment by jshorland** [comment] 2018-03-01 02:59
fixed. closing.

**Closed by jshorland** 2018-03-01 02:59 UTC
Labels: P2 - Normal
