### ISSUE TITLE
Published single reports showing up twice on map

### ISSUE THREAD

**Issue by natmanning** [ushahidi/platform#1478] opened 2016-11-03 18:56 UTC
Expected behaviour

A published report will show up once on a map

Actual behaviour

There is a report i just published in Arkansas in “Other” Survey. It is just one report, and only coming up as one on Timeline. But on my Map it is showing up twice, and showing two of the same report in the same place.

Steps to reproduce the behaviour/error

Go to usaelectionmonitor.ushahidi.io
look at arkansas on the map and look at both posts there and see they are the same. Then look at timeline, and see only 1 post there

screen shot 2016-11-03 at 11 51 15 am

**Comment by natmanning** [comment] 2016-11-03 19:00
Note: other reports are not showing up twice. This report came in via Twitter, and was then edited and turned into a report by the admin, which seems to be the only major variable

**Comment by willdoran** [comment] 2016-11-04 17:21
@natmanning I'm not seeing the post, is it published? can you link me to it directly?

**Comment by rjmackay** [comment] 2016-11-16 03:29
Closing this since we can't reproduce it

**Comment by rjmackay** [comment] 2016-11-16 03:29
Might be related to #1503

**Closed by rjmackay** 2016-11-16 03:29 UTC
Labels: P0 - Unbreak now!
