### ISSUE TITLE
The task required setting prevents a post from being published

### ISSUE THREAD

**Issue by CeciliaHinga** [ushahidi/platform#3957] opened 2020-04-24 15:53 UTC
**Describe the bug**
When you try to save a post for publishing, after switching the '_task completed_' toggle on in order to mark the task as complete before a post can be visible to the public, a message pops up displaying no changes have been made.
<img width="482" alt="Posts_-_Heba" src="https://user-images.githubusercontent.com/20906968/80225746-25eec000-8654-11ea-8900-8107f143ff2b.png">
When you click "ok" and edit something and save the changes, then click on '...' and try to publish you get an error
<img width="1335" alt="These_Are_The_Routes_That_SWVL_Has_Temporarily_Cancelled_-_Heba_and_Slack___Anna___Ushahidi" src="https://user-images.githubusercontent.com/20906968/80229165-b4654080-8658-11ea-8be8-56d45bec1f14.png">
When you go back to the post and edit, you will notice the '_task completed_' toggle is off. So your only choice is to edit the post, mark as published, switch on the '_task completed_' toggle on, all at the same time and save. The post gets published but if you click on edit again, you will find the '_task completed_' toggle is still off.

**Where was the bug observed**
Production

**To Reproduce**
1. As an admin go to 'Data'
2. Click on a post, click on edit. Scroll down to the task field, switch the task completed toggle on. Click on save, a 'no changes have been made' notification will pop up.
3. Click ok.
4. Edit something and click on save.
5. Click on  '...' of the post you want to publish.
6. Click on Publish. You will get the above error.
7. Click on Edit again, click on published, switch on the '_task completed_' toggle, then save. The post gets published.
8. Click on the same post one more time, the task completed will be off.

**Expected behavior**
The task completed toggle should remain on when it has been switched on to mark the task as completed for publishing.

**Is there a workaround? What is it.**
No

**Desktop Hardware Details (please complete the following information):**
 - OS iOS
 - chrome

Aha! Link: https://ushahiditeam.aha.io/features/PROD-119

**Comment by rowasc** [comment] 2020-04-24 15:55
thanks @CeciliaHinga . Is this happening with a specific survey design, like having a required task with no fields in it?

**Comment by CeciliaHinga** [comment] 2020-04-24 16:09
@rowasc No, this is when you organize your survey into tasks and add fields related to actions that need to be taken before you publish the post publicly.

**Comment by CeciliaHinga** [comment] 2020-04-24 16:10
@rowasc e.g verification

**Comment by rowasc** [comment] 2020-04-24 16:12
ah ok so this is a survey where
- There is a task
- The task has fields in it
- The task is required. 
Thanks ! That's definitely a problem.

**Comment by rohit645** [comment] 2020-04-25 07:12
I am able to reproduce this locally. Can I work on this issue?

**Comment by rowasc** [comment] 2020-04-25 08:01
absolutely, thank you!

**Comment by rohit645** [comment] 2020-04-25 11:04
@rowasc Hmm, I think I found the bug.

Toggling of task_completion occur at:

https://github.com/ushahidi/platform-client/blob/3a9d668c5a0434ad8f7672ebfbb4cfd1701bccd8/app/main/posts/modify/post-tabs.directive.js#L55

Checking the status of Complete is checked at:

https://github.com/ushahidi/platform-client/blob/3a9d668c5a0434ad8f7672ebfbb4cfd1701bccd8/app/main/posts/modify/post-tabs.directive.js#L51

When the post is saved, I tried to log the output which was as follows:

![Screenshot from 2020-04-25 16-08-39](https://user-images.githubusercontent.com/33249010/80277919-04530e80-8710-11ea-84fb-b50ae52e6efb.png)

completed_stages attribute is empty, whereas it should have returned an array of integers (depending upon number of tasks completed). 
Is this bug related to API? As everything is working fine on the client-side according to me. If it is I would need some guidance on how to solve it.

**Comment by rowasc** [comment] 2020-04-26 21:46
thanks @rohit645 . Q: are completed_stages being sent at that point? That was my initial reaction, that maybe we just aren't sending the updated stages. If no, then it's likely a frontend bug. If we are, then we're likely looking at a backend issue.
If it's the backend I'd look into the PostRepository::update (src/App/Repository/PostRepository.php)  to see what's up there.

**Comment by rohit645** [comment] 2020-04-27 03:05
> thanks @rohit645 . Q: are completed_stages being sent at that point? That was my initial reaction, that maybe we just aren't sending the updated stages. If no, then it's likely a frontend bug. If we are, then we're likely looking at a backend issue.
> If it's the backend I'd look into the PostRepository::update (src/App/Repository/PostRepository.php) to see what's up there.

I think we are sending the updated stages. I tried to log it at : 
First Log
https://github.com/ushahidi/platform-client/blob/3a9d668c5a0434ad8f7672ebfbb4cfd1701bccd8/app/main/posts/modify/post-editor.directive.js#L268

and 

Second Log
https://github.com/ushahidi/platform-client/blob/3a9d668c5a0434ad8f7672ebfbb4cfd1701bccd8/app/main/posts/modify/post-editor.directive.js#L273

This was the output:
First Log before sending PUT request to API
![Screenshot from 2020-04-27 08-32-28](https://user-images.githubusercontent.com/33249010/80330057-c239e200-8861-11ea-8834-521d398cc03a.png)

Second Log (The response from API):
![Screenshot from 2020-04-27 08-31-29](https://user-images.githubusercontent.com/33249010/80330075-cf56d100-8861-11ea-8424-f67c7c221ada.png)

I think I need to look at PostRepository.

**Comment by A-DML** [comment] 2020-10-08 09:09
Hi @Angamanga i will like to work on this for my outreachy contribution

**Comment by Angamanga** [comment] 2020-10-08 12:09
Thank you @A-DML 🎉  Please go ahead!

**Comment by A-DML** [comment] 2020-10-08 13:39
Thanks @Angamanga . I will

**Comment by A-DML** [comment] 2020-10-14 09:18
Hey @Angamanga, I need assistance with figuring some things out for this task, I tried using JS to solve this, it's not looking like it. Is there certain instruction I need to follow

**Comment by rowasc** [comment] 2020-10-16 20:09
@A-DML hey. What specific issue are you having? 
1. Were you able to reproduce the issue? 
2. Are you looking for assistance on knowing where the files are? 
3. What have you tried (you mentioned you tried JS but specifics would be helpful) 
This may help Anna provide the correct guidance. Please make sure you attempt to reproduce the issue (and are able to reproduce it) before coding, since it'd be hard for you to know if you have fixed it otherwise once you work on it.
Thanks

**Comment by rowasc** [comment] 2020-10-26 13:20
@A-DML Hey since you haven't been back I'm unassigning this, please do let me know if you are working on it. Thanks

**Comment by Angamanga** [comment] 2024-03-01 08:24
This works now so closing

**Closed by Angamanga** 2024-03-01 08:24 UTC
Labels: Bug, P1 - Immediate, Community Task, Codebase: Client
