### ISSUE TITLE
Add "In progress" or "Waiting" bar to notify users of actions happening in the background.

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1668] opened 2017-04-03 14:56 UTC
Feedback from user.

"When we click "Invia" (or SEND), there is no "message" like waiting or rounding wheel or similar... this means that people click on the button twice or thrice. It is possible to have a pop-up or a message for waiting?"

User complained of duplication of submissions because no feedback was being given to a user on success of e.g submission of a post, creation of a field

**Comment by aoduor** [comment] 2017-04-10 13:08
User brought this up again

Refs https://app.intercom.io/a/apps/hl5rfiga/respond/inbox/angela@ushahidi.com/conversations/9204361285

**Comment by rjmackay** [comment] 2017-04-10 22:50
Rollcall has a nice simple solution to this. @brandonrosage could we do something similar?

**Comment by niccolov** [comment] 2017-04-13 09:27
Hi @rjmackay and @brandonrosage any news about it?

People get stuck with it every time. The problem is that a lot of person click more time the send buttom (so we receive duplicate posts) or go back and stop sending the post :/

When we click SEND nothing happens and this bring persons to think that something is not working or that they pressed wrongly.

We are hoping for a solution ;)

**Comment by niccolov** [comment] 2017-04-19 13:40
@rjmackay @brandonrosage Any update about that? I've seen a lot of person get stuck or nervous about this problema. Once they click SEND, nothing change on the "window" and no "wait messages" appers on screen. People then think:

- I did it and they close the phone (and in many case the upload stop) :(
- I did something wrong, let's push again... and they press send 2/3/4 times until they get the final message. For us it means moderate many duplicates.

We tested it with different persons with different technology skills and they all have some problem about this step.

Thanks

**Comment by niccolov** [comment] 2017-04-24 08:12
Good morning, sorry to ask again but the 27 of April we will launch the project to the public... so we would like to have some news about it to be ready to answer to technical and/or assistance request.

**Comment by aoduor** [comment] 2017-04-24 08:15
Hey @niccolov thanks for reaching out.

Ping @jshorland @rjmackay @brandonrosage - somewhat related to #1713 - confirming that we need this for Uchaguzi as well.

**Comment by niccolov** [comment] 2017-04-24 08:20
Ping @jshorland @rjmackay @brandonrosage Please pay attention to this... People are getting confused about this :/

**Comment by jshorland** [comment] 2017-04-24 15:08
@angamanga Can you add this to your "up next"? we have a convention for upload progress on csv import as well. We might want to use the same.

@niccolov we understand and are trying to help with this as quickly as possible.

**Comment by Angamanga** [comment] 2017-04-25 11:14
👍 I'll look at it today and tomorrow if needed!

**Comment by niccolov** [comment] 2017-04-25 21:12
Thank @Angamanga and @jshorland. I had a couple of hours free.. that's why I've wrote to you again ;)

Take your time... you are doing great things!

**Comment by jshorland** [comment] 2017-04-26 17:53
@angamanga as we discussed today, to quickly get a solution out to the problem of users clicking the submit button a million times and wreaking havoc on the deployment, let's disable the "submit" button after they click it once, and notify the user that the photo is uploading by changing the text on the button to "saving".  Even if they navigate away, the post will still continue uploading as they system is currently built, but they won't be able to. click submit a million times

**Comment by jshorland** [comment] 2017-04-26 21:00
@niccolov -- we LOVE when users log issues that they find -- we'll try to address them as soon as possible :-) I think we can get you a fix for this relatively quickly to stop users from clicking submit over and over and over, which I'm sure is incredibly frustrating. We'll keep you updated!

**Closed** 2017-06-07 02:37 UTC
Labels: Feature request, P0 - Unbreak now!, Stage: Testing
