### ISSUE TITLE
Dotcom/Resilience - Image links are broken on Ushahidi Resilience webpage

### ISSUE THREAD

**Issue by jrtricafort** [ushahidi/platform#3525] opened 2019-04-05 16:50 UTC
Reported by @Shadrock : https://www.ushahidi.com/stories/resilience - the image links are broken.

**Comment by jrtricafort** [comment] 2019-04-05 16:52
@Shadrock I went to the page and the images appeared to load successfully for me. See screenshot:
![image.png](https://images.zenhubusercontent.com/5ac5411e4b5806bc2bcdb0c4/d6030c92-b012-491b-9071-47e0bfb0e922)

@Erioldoesdesign would you be able to double-check if the images load for you as well? If they are not loading, would you be able to confirm if the folders containing the media appear to be in the correct place?

If either of you are able to repro the bug, feel free to add more info and screenshot here. Thanks all!

**Comment by Shadrock** [comment] 2019-04-05 17:12
Juan's screenshot above is how the page should look, so I'm wondering if the problem is on my end. I've replicated on Chrome and Firefox. In some cases the inset picture is fine but the background is missing. The example below is what I see when I view the same page Juan viewed, above.
![Screen Shot 2019-04-05 at 11.09.39 AM.png](https://images.zenhubusercontent.com/5a6a46294b5806bc2bc454b9/1ad96b42-b253-452b-9e35-609814ebc1f5)

**Comment by Shadrock** [comment] 2019-04-05 18:02
After moving to a different network, I can't replicate the issue. I can only assume that I was on a throttled network or had some other problem on my end. Closing this issue now. Thanks to everyone.

**Closed by Shadrock** 2019-04-05 18:02 UTC
Labels: Bug, dotcom

**Comment by Erioldoesdesign** [comment] 2019-04-11 22:57
FYI I checked this page and everything loaded. However, the mobile experience is pretty awful and the images go wonky. Definitely a template set that requires some attention for mobile.
