### ISSUE TITLE
CSV import should feed back useful errors

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#1454] opened 2016-10-18 18:22 UTC
### Expected behaviour
- When an import fails or contains rows that failed to import
- The platform should explicitly list which rows errored

### Actual behaviour
- At present we only return number of errors

### Steps to reproduce the behaviour/error
- Import csv with erroneous rows

**Comment by rjmackay** [comment] 2016-10-19 18:59
This is a duplicate of #1448

**Closed by rjmackay** 2016-10-19 18:59 UTC
Labels: Enhancement, Feature request, Needs Triage
