### ISSUE TITLE
Next applicable report is not appearing after saving

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#2204] opened 2017-10-23 14:15 UTC
### Expected behaviour
When I save a report after structuring, and it does not fall into selected filters anymore, it should swipe out and next applicable report should be visible in detail-mode. 

### Actual behaviour
When I save a report after structuring, I always go to the detail-mode of that report, even if it does not fall into the filters anymore.

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by rowasc** [comment] 2017-10-23 14:48
Not a bug, This is not implemented yet. Thanks for logging it !

**Comment by rjmackay** [comment] 2017-11-01 04:28
@justinscherer Was this the intended behaviour? Do you think its essential to implement before data view goes live in core?

**Comment by justinscherer** [comment] 2017-11-01 16:33
>  Do you think its essential to implement before data view goes live in core?

Our filters don't make sense without this item. For example, if you're filtering for unstructured posts from SMS, and you structure an SMS report, it no longer applies to the filters and should therefore not appear in the list. After structuring 50 reports in the same way, your filters no longer make sense unless the structured posts disappear.

**Comment by rjmackay** [comment] 2017-11-01 21:36
@crcommons this relates to the work you did to remove posts from the list if they no longer match. Could you take a look?

**Comment by crcommons** [comment] 2017-11-02 18:23
@rjmackay I believe that this is occurring because of problems with the filters. When I select the saved search "Unstructured posts from sms and email" and then I structure a post, the post always remains in as a result in that saved search, even if I refresh. If it were a problem with the code that removes it and selects the next post, that now structured post would be gone from the list when I refresh. @Romina-Suarez Just flagging for you since its ANOTHER issue with filters.

**Comment by rowasc** [comment] 2017-11-02 18:28
uh.. this feature was never done AFAIK. So I'm not sure about it @crcommons

**Comment by crcommons** [comment] 2017-11-02 18:37
The issue should really read: "Next applicable post is not selected when post is edited/saved and no longer matches filters." This was implemented, but is broken only when filters are not working correctly. Otherwise, it works. 

@justinScherer, In ALL circumstances, should the next post be selected, even if the currently selected post DOES match the current filters. (aka if I have no filters set, and I edit a post and save it, should the current post remain selected or should it select the next post?)

**Comment by rowasc** [comment] 2017-11-02 18:39
@crcommons ugh. I was fairly certain this was not done at all, sorry about that ( I assumed we only had the "next" working for cancel/save/close actions)

**Comment by justinscherer** [comment] 2017-11-03 14:40
> @justinscherer In ALL circumstances, should the next post be selected, even if the currently selected post DOES match the current filters. (aka if I have no filters set, and I edit a post and save it, should the current post remain selected or should it select the next post?)

In this case it would remain selected.

**Comment by crcommons** [comment] 2017-11-03 14:56
Perfection! Then all of this is already happening! Worth noting that it only isn't happening when the filters are screwing up, which is a whole other issue. Moving to done.

**Closed** 2017-11-03 14:56 UTC
Labels: 2chaguzi, Enhancement, P1 - Immediate, P2 - Normal
