### ISSUE TITLE
Saved search - after editing saved search permissions, it's not possible to set "Everyone" again 

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2077] opened 2017-09-20 17:29 UTC
### Expected behaviour
I can set edit a saved search and change its permissions/public as I wish. 

### Actual behaviour
I can only change to more restrictive permissions after I select a permission set for the first time. ie: If I set permissions to "User" I cannot go back to "Everyone". 
The UI reports "Everyone" but the backend does not support it and returns a 403 when an anonymous user tries to load the saved search

### Steps to reproduce the behaviour/error

- [ ] [Logged in]Create a saved search with permissions "Everyone". Save it, and save the URL for later.
- [ ] [Annonymous] Verify that you can access the saved search (by going directly to the URL you saved) 
- [ ] [Logged in] Go to the saved search and edit permissions, setting them for "User". Save.
- [ ] [Annonymous] Verify that you cannot access the saved search. 
- [ ] [Logged in] Go to the saved search and edit permissions, setting them for "Everyone". Save.
**- [ ] [Annonymous] Verify that you cannot access the saved search.**  => We should be able to access it, but we aren't

**Comment by rowasc** [comment] 2017-09-20 17:31
Debug info: 
The role is set to [] empty array when you change to "Everyone" instead of being set to Null, which is the initial state

**Comment by jshorland** [comment] 2018-02-28 00:20
Can't reproduce. Closing.

**Closed by jshorland** 2018-02-28 00:20 UTC
Labels: Bug
