### ISSUE TITLE
For each targeted survey, all messages for a contact are shown, not just messages related to that survey.

### ISSUE THREAD

**Issue by kinstelli** [ushahidi/platform#2753] opened 2018-04-16 16:34 UTC
### Expected behaviour
- Only messages relevant to a specific targeted survey should appear in a post for a contact when viewing a targeted survey.

### Actual behaviour
- Every message sent to/from a specific contact are appearing in the post for a targeted survey.

In this example, questions and responses from a previous survey (form April 13, 2018) are appearing in the list for a newly generated survey.
<img width="628" alt="screen shot 2018-04-16 at 11 27 13 am" src="https://user-images.githubusercontent.com/6600708/38822649-b4228582-4169-11e8-9dc9-d63da707380c.png">

### Steps to reproduce the behaviour/error
- Create a survey that includes a phone number used in a previous survey.
- Find the post in the new survey that is related to that contact
- Review the messages attached to that post, confirm that some messages do not belong to the current survey

#### Where does this issue happen?
- [x] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [x] Ushahidi's QA environment
- [ ] Other (explain):

Aha! Link: https://ushahiditeam.aha.io/features/PROD-371

**Comment by rowasc** [comment] 2018-04-16 18:17
@mkinsella really interesting/frustrating but, status update in case you have ideas:
-The post ID for the message not in a targeted survey and the one in a targeted survey is not the same (this is good. It was my initial concern, but discarded now). 
- I believe this is only related to how we fetch “conversation with author”

**Comment by rowasc** [comment] 2018-04-16 18:40
@caharding                      

sending the TLDR of the solution now that I had some more time to research:
- [Easy] don't create a new post if one exists , even if not in a targeted survey
- [Easy] add post_id filter in the client to only bring back the messages for contact+post_id
- [Not sure, should be easy ] add filter for post_id in the backend. In theory this already should exist but it's not working so I'm checking out why

-----a long explanation of how this happenes ----
> I'm guessing the problem is a data model issue
mmmm not quite a data model issue, more of a logic/filtering one which is caused by a bug in the post creation that we have had for a long time and was not correctly addressed for this iteration. 
We don't filter by post when showing the thread, because right now when a contact (who isn't yet in a targeted survey) sends a message we create a new post, even if there's one already. For this behavior, filtering would be wrong if you want to see all messages in the thread. This can be avoided by not creating a new post unless there is none to associate the message to. 
So when requesting a thread we ask for "All messages for this contact" when the way we need to do it is asking "All messages for this contact AND this post_id" .


>I'm guessing that if a user sends 3 posts, and then there is a convo back and forth over SMS, the comment section gets updated on all three posts.
Correct. if there were 3 posts with a contact that's the same and we have a back and forth, you are correct, they would appear everywhere.

**Comment by caharding** [comment] 2018-04-16 21:26
OK this is better understood now.

CURRENT SOLULTION
For SMS not part of a Targeted Survey: 
- treat as currently handled in production
- the proposed solution would thread all messages into a single post
- this would break Ushahidi Platform for users. For example Uchaguzi field reporters making reports over SMS would make many posts about different issues over SMS. It would be bad if these were all threaded together. 

For SMS part of a targeted survey:
- SMS Messages should be added as thread until a new SMS survey is created, then threads move to that new survey. 
- @rowasc can you confirm that is notified when a new survey is initiated? What happens when a user does not complete Survey A and Survey B is sent out. Are they notified that "hey all your last survey is not closed and you're starting a new one?"

FUTURE SOLUTION
- we would like to be able to have both post creation via SMS and messaging over SMS and need a solution, but today they are tied together, creating lots of strange problems
- the problem is that our user model #2569 and messaging #2570 is really a hack and we've opened issues for to address both

**Comment by caharding** [comment] 2018-04-18 00:05
@rowasc was this resolved with yesterdays release?

**Comment by rowasc** [comment] 2018-04-19 18:49
@caharding 
No. We need to invest some time on this to solve it. I think it's a 2-3 pointer but @rjmackay might want to jump in here too. 
Following up on the suggested solution posted by you after our chat:
------

For SMS part of a targeted survey:

SMS Messages should be added as thread until a new SMS survey is created, then threads move to that new survey. => Let me go step by step to make sure I understand:

#### "Step 1" : While there is no targeted survey for User A:
- User A sends a SMS
- We receive it, create a post and message. 
- User A sends another SMS
- We receive it, create a post and message. 
- When an Admin checks data view  and opens the first post created by the user's SMS, they see ALL messages (as it is in production now) threaded there.

### "Step 2": Now a targeted survey with User A is created
- A targeted survey is sent, the first Question is sent to User A
- User A responds. The first post is created, the first message associated with that post is created
- When an Admin checks data view and opens the first post created by the user's SMS while not in a targeted survey, they see ALL messages (as it is in production now) threaded there, except the ones from the survey.
- When an Admin checks the data view and opens the first post of User A that is related to the targeted survey, they see the first Question and the response that User A sent.
- Question 2 is sent to User A.
- User A responds. 
- When an Admin checks data view and opens the first post of User A that is related to the targeted survey, they see the two questions sent to User A and the two responses User A sent, but not the messages that aren't related to the survey thread.

Is this correct?
-------
Answer your question:
>>> @rowasc can you confirm that is notified when a new survey is initiated? What happens when a user does not complete Survey A and Survey B is sent out. Are they notified that "hey all your last survey is not closed and you're starting a new one?"
We notify the admin of the contacts that were "moved" to Survey B. We do not notify the users that they have been moved from A to B. Their responses to Survey A are still linked to Survey A. Their responses to Survey B will be linked to Survey B.

**Comment by rowasc** [comment] 2018-04-19 18:51
@rjmackay the proposed solution changed after I had a call with Charlie. To answer your questions: The original spec specifically said we should have been creating only 1 post and adding to it not creating multiple posts.

**Comment by rowasc** [comment] 2018-06-19 18:48
@jrtricafort this should be out of cycle 5 , not sure where to send it. Do I just empty the milestone for it?

**Comment by rowasc** [comment] 2018-07-02 14:00
Also, Will is off today, so it should be tomorrow or later in the week

**Closed** 2020-10-13 16:08 UTC
Labels: Bug, DREAMS, P2 - Normal, Won't Fix
