### ISSUE TITLE
Posts remain locked even if no one is working on the post

### ISSUE THREAD

**Issue by CeciliaHinga** [ushahidi/platform#4428] opened 2022-06-13 12:40 UTC
**Describe the bug**
1. Once a user finishes working on the post, the post remains locked, indicating someone is still working on the post. Meaning;
      a. The admin cannot "break" the lock to ensure that a Post becomes available again in a time-sensitive situation.
      b.The post does not expire within 5 minutes. More than 2 days later, the post still shows it is locked.
      c.The post is not unlocked even if the user who was working on the post logs out.
      d.It does not display the username of the person working on the post.

2. If you access the deployment as an admin, you will see a different has been locked from the one a user with "manage posts" permission will be seeing.

3. If you click on the three-dotted icon on the post as an admin/a user who can manage posts, the edit function will not be displayed but if you click on the three-dotted icon on the detailed version of the same post, the edit function will be displayed. (please note, at the top right corner of the screen, the edit button in yellow will not be displayed as it should)

**Where was the bug observed**
(https://uchaguzi.staging.ush.zone/views/map)

**To Reproduce**
1. Go to https://uchaguzi.staging.ush.zone/views/map
2. Log in as an admin/a user who can manage posts
3. Click on "data"  depending on the account you have used, the locked posts will be different.
4. It does not display the username of the person working on the post.
5. If you click on the three-dotted icon on the post as an admin/a user who can manage posts, the edit function will not be displayed but if you click on the three-dotted icon on the detailed version of the same post, the edit function will be displayed. (please note, at the top right corner of the screen, the edit button in yellow will not be displayed as it should)

**Expected behavior**
1. If a user is working on a post, the admin should be able to break the lock.
2. If a user working on the post logs out, the post should automatically be unlocked
3. If a post is locked for more than 5mins, it should automatically expire.
4. All locked posts should be visible and the same to all users.
5. If a post is locked, a user who has permission to manage posts should not be able to edit the post.

**Is there a workaround? What is it.**
Click on the same post and click on the three-dotted icon on the detailed version of the post on the right to edit the post.

**Screen recordings**
First attempt for a user who can only manage posts
https://slack-files.com/T024G41EQ-F03KFECER5J-3d865d57dc

First attempt for an admin
https://slack-files.com/T024G41EQ-F03KRPCK7B3-e952d52058

2nd attempt for a user who can only manage posts
https://slack-files.com/T024G41EQ-F03KRPLF6V7-32637a75a4

2nd attempt for an admin
https://slack-files.com/T024G41EQ-F03JYG1FHLP-cc4a3547d9

**URL / Environment where this happened**
staging

**Desktop Hardware Details (please complete the following information):**
 - OS: iOS
 - Browser chrome and brave

**Comment by tuxpiper** [comment] 2022-06-21 13:52
@Mh-Asmi is investigating

**Comment by tuxpiper** [comment] 2022-07-07 14:48
@Mh-Asmi identified the root cause. As mentioned in this document: https://www.notion.so/ushahidiorg/Post-Locking-Feature-Audit-for-Uchaguzi-2022-a7f7566a9a1c4a669e67823e97932afd#e06fd8131289438dab8e531765b1dac1 

> When the user finishes his editing by saving, the lock must be deleted … “platform client doesn’t  call the delete lock API in some cases ”

Specifically, when the client clicks on the most obvious "Save" button at the bottom of the screen.

This needs to be fixed in the client. Unassigning from @Mh-Asmi

**Comment by tuxpiper** [comment] 2022-07-29 17:09
This has been fixed in Uchaguzi. Soon will be released to all ushahidi.io

**Closed by tuxpiper** 2022-07-29 17:09 UTC
Labels: P1 - Immediate, Codebase: Client, Uchaguzi2022
