### ISSUE TITLE
Archived posts should be shown in collections created from CSV imports

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#1462] opened 2016-10-26 17:08 UTC
### Expected behaviour
- When a user imports a set of posts that contain archived posts, the resulting collection should always display the archived posts

### Actual behaviour
- Archived posts are hidden

**Comment by willdoran** [comment] 2016-10-26 17:10
To achieve this we can add a field to the collection object 'Source' which give the origin point of the collection. If 'Source' is set to import then the archived filter will be enabled on the collection views so that the archived posts are visible.

**Comment by rjmackay** [comment] 2016-10-26 20:00
I think this is a dupe of #1446  and applies to all collections not just those from import. I don't think adding a source parameter fixes this properly. We shouldn't have any status filter when viewing a collection by default.

**Comment by willdoran** [comment] 2016-10-26 20:15
@rjmackay, should we then clear all filters by default on collections? That would greatly simplify the issue or is there another dimension I'm missing?

**Comment by rjmackay** [comment] 2016-10-26 20:18
No I think thats right. We should clear all filters by default, and add a display of any active filters.
The only complication might be maintaining filter while switching between map and timeline views on the same collection.. but tbh we could ignore that right now for a quick fix.

**Comment by willdoran** [comment] 2016-10-26 20:20
@rjmackay how do you mean "display of any active filters" is there a pattern for that or how would you imagine it being formed?

Clearing the filters or rather setting 'collection defaults' is straightforward and I can stage quickly/

**Closed** 2016-10-28 18:31 UTC
Labels: Bug, P1 - Immediate, Theme: CSV
