### ISSUE TITLE
Insert error for Table 'post_datetime'

### ISSUE THREAD

**Issue by pierreverbakel** [ushahidi/platform#838] opened 2015-11-22 21:53 UTC
I get the following results in en the errorlog. There must be something wrong with the value format....
:

2015-11-20 05:06:48 --- EMERGENCY: Database_Exception [ 1292 ]: Incorrect datetime value: '2015-12-05T21:30:00.000Z' for column 'value' at row 1 [ INSERT INTO `post_datetime` (`value`, `form_attribute_id`, `post_id`, `created`) VALUES ('2015-12-05T21:30:00.000Z', 10, 9, 1447996008) ] ~ APPPATH/classes/Database/MySQLi.php [ 155 ] in /srv/www/htdocs/platform-3.1.0/vendor/ohanzee/database/src/Database/Query.php:251
2015-11-20 05:07:15 --- EMERGENCY: Database_Exception [ 1292 ]: Incorrect datetime value: '2015-12-05T21:30:00.000Z' for column 'value' at row 1 [ INSERT INTO `post_datetime` (`value`, `form_attribute_id`, `post_id`, `created`) VALUES ('2015-12-05T21:30:00.000Z', 10, 9, 1447996035) ] ~ APPPATH/classes/Database/MySQLi.php [ 155 ] in /srv/www/htdocs/platform-3.1.0/vendor/ohanzee/database/src/Database/Query.php:251
2015-11-20 05:32:51 --- EMERGENCY: Database_Exception [ 1292 ]: Incorrect datetime value: '2015-11-27T11:30:00.000Z' for column 'value' at row 1 [ INSERT INTO `post_datetime` (`value`, `form_attribute_id`, `post_id`, `created`) VALUES ('2015-11-27T11:30:00.000Z', 12, 9, 1447997571) ] ~ APPPATH/classes/Database/MySQLi.php [ 155 ] in /srv/www/htdocs/platform-3.1.0/vendor/ohanzee/database/src/Database/Query.php:251
2015-11-20 06:25:29 --- EMERGENCY: Database_Exception [ 1292 ]: Incorrect datetime value: '2015-11-20T06:00:00.000Z' for column 'value' at row 1 [ INSERT INTO `post_datetime` (`value`, `form_attribute_id`, `post_id`, `created`) VALUES ('2015-11-20T06:00:00.000Z', 19, 11, 1448000729) ] ~ APPPATH/classes/Database/MySQLi.php [ 155 ] in /srv/www/htdocs/platform-3.1.0/vendor/ohanzee/database/src/Database/Query.php:251
2015-11-20 06:26:13 --- EMERGENCY: Database_Exception [ 1292 ]: Incorrect datetime value: '2015-11-20T06:00:00.000Z' for column 'value' at row 1 [ INSERT INTO `post_datetime` (`value`, `form_attribute_id`, `post_id`, `created`) VALUES ('2015-11-20T06:00:00.000Z', 19, 11, 1448000773) ] ~ APPPATH/classes/Database/MySQLi.php [ 155 ] in /srv/www/htdocs/platform-3.1.0/vendor/ohanzee/database/src/Database/Query.php:251
2015-11-20 06:26:24 --- EMERGENCY: Database_Exception [ 1292 ]: Incorrect datetime value: '2015-11-20T06:00:00.000Z' for column 'value' at row 1 [ INSERT INTO `post_datetime` (`value`, `form_attribute_id`, `post_id`, `created`) VALUES ('2015-11-20T06:00:00.000Z', 19, 11, 1448000784) ] ~ APPPATH/classes/Database/MySQLi.php [ 155 ] in /srv/www/htdocs/platform-3.1.0/vendor/ohanzee/database/src/Database/Query.php:251
2015-11-20 06:28:08 --- EMERGENCY: Database_Exception [ 1292 ]: Incorrect datetime value: '2015-11-20T06:00:00.000Z' for column 'value' at row 1 [ INSERT INTO `post_datetime` (`value`, `form_attribute_id`, `post_id`, `created`) VALUES ('2015-11-20T06:00:00.000Z', 19, 12, 1448000888) ] ~ APPPATH/classes/Database/MySQLi.php [ 155 ] in /srv/www/htdocs/platform-3.1.0/vendor/ohanzee/database/src/Database/Query.php:251
2015-11-20 06:29:29 --- EMERGENCY: Database_Exception [ 1292 ]: Incorrect datetime value: '2015-11-20T06:00:00.000Z' for column 'value' at row 1 [ INSERT INTO `post_datetime` (`value`, `form_attribute_id`, `post_id`, `created`) VALUES ('2015-11-20T06:00:00.000Z', 19, 14, 1448000969) ] ~ APPPATH/classes/Database/MySQLi.php [ 155 ] in /srv/www/htdocs/platform-3.1.0/vendor/ohanzee/database/src/Database/Query.php:251
2015-11-20 06:28:41 --- EMERGENCY: Database_Exception [ 1292 ]: Incorrect datetime value: '2015-11-20T06:00:00.000Z' for column 'value' at row 1 [ INSERT INTO `post_datetime` (`value`, `form_attribute_id`, `post_id`, `created`) VALUES ('2015-11-20T06:00:00.000Z', 19, 13, 1448000921) ] ~ APPPATH/classes/Database/MySQLi.php [ 155 ] in /srv/www/htdocs/platform-3.1.0/vendor/ohanzee/database/src/Database/Query.php:251
2015-11-20 06:52:44 --- EMERGENCY: Database_Exception [ 1292 ]: Incorrect datetime value: '2015-11-25T18:00:00.000Z' for column 'value' at row 1 [ INSERT INTO `post_datetime` (`value`, `form_attribute_id`, `post_id`, `created`) VALUES ('2015-11-25T18:00:00.000Z', 12, 9, 1448002364) ] ~ APPPATH/classes/Database/MySQLi.php [ 155 ] in /srv/www/htdocs/platform-3.1.0/vendor/ohanzee/database/src/Database/Query.php:251

**Comment by willdoran** [comment] 2016-03-16 20:05
Using the current release version I am not able to reproduce this.

@pierreverbakel could you test with the newest version of the platform and client?

**Comment by willdoran** [comment] 2016-03-17 18:34
I can't reproduce this in the current version. Given the time between version I believe this has been fixed. I'm going to close the issue for now.

@pierreverbakel please feel free to reopen the issue if you're still experiencing it.

**Closed by willdoran** 2016-03-17 18:34 UTC
Labels: 3 - In progress, Bug, P2 - Normal, Theme: Post editing
