### ISSUE TITLE
Unable to navigate beyond first page of list of users in admin pane

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#2469] opened 2018-02-12 13:42 UTC
### Expected behaviour
*If i have less than 10 users on my deployment, no pagination should be made available to me as a user.
*If I have more than 10 users on my deployment, pagination should be there, and clicking on either the page number, or arrow buttons should navigate to a list of users beyond the previous list i was viewing. 

#### In a deployment with 10 users or less, I don't have user pagination
- [x] Go to Settings -> Users
- [x] Verify that there is no pagination 

#### In a deployment with more than 10 users and less than 21, the pagination bar has a link to page "1" and "2" 
- [x] Go to Settings -> Users
- [x] Verify that there is pagination 
- [x] Verify that there is pagination to go to the first page and the second page.
- [x] From the first page, click "2"
- [x] Verify that you are taken to the second page.
- [x] From the second page, click "1"
- [x] Verify that you are taken to the first page.

#### In a deployment with more than 10 users and less than 21, the pagination bar has a link to go to the next page when I'm in the first page (">" arrow)
- [x] Go to Settings -> Users
- [x] Verify that there is pagination 
- [x] From the first page, Verify that there is pagination arrow to the next page
- [x] Click the ">" arrow
- [x] Verify that you are taken to the second page.
- [x] From the second page, click "<" arrow
- [x] Verify that you are taken to the first page.

### Actual behavior
Clicking on page number, or the back and forward arrows does absolutely nothing. They are non responsive. 

### Steps to reproduce the behaviour/error
* Log into your deployment
* Click on settings, then users
* Attempt to navigate to a different page by clicking forward, backwards, or clicking on a page number.

Noticed while on DREAMS Partner deployments.

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [*] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by jshorland** [comment] 2018-02-12 19:11
Reproduced on qa.ushahididev.com

This needs to be fixed ASAP

**Comment by rowasc** [comment] 2018-02-12 21:53
@jshorland fix sent for code review, demo can be seen here. 
We probably want to add a loading bar and make it a bit nicer, I made a comment about this by the end of the demo, essentially the pagination does not trigger a loading bar, it just goes to the next page. I think that might be a separate ticket just because of the different priorities, but let me know if not and I can check today since it's probably a quick fix

**Comment by rowasc** [comment] 2018-02-12 21:53
oops demo is uploading. Sorry. Will notify again when it's up

**Comment by rowasc** [comment] 2018-02-12 22:08
https://drive.google.com/open?id=1pqDkGc6YRROjf7nId2_sVIZM5YHX3gcu demo

**Comment by jshorland** [comment] 2018-02-12 23:12
demo looks great! thanks for jumping on this so fast

**Comment by rowasc** [comment] 2018-02-14 16:58
@jshorland before we go to prod, can you check this in the url http://platform2469master.lab2.ushahidilabs.com/     ? 
Thanks

**Comment by rowasc** [comment] 2018-02-14 16:58
credentials are the ones I sent today

**Comment by jshorland** [comment] 2018-02-14 23:08
Jess testing feb 14
## Test Script (admin/user with permissions to see users)

#### In a deployment with 10 users or less, I don't have user pagination
- [x] Go to Settings -> Users
- [x] Verify that there is no pagination 

#### In a deployment with more than 10 users and less than 21, the pagination bar has a link to page "1" and "2" 
- [x] Go to Settings -> Users
- [x] Verify that there is pagination 
- [x] Verify that there is pagination to go to the first page and the second page.
- [x] From the first page, click "2"
- [x] Verify that you are taken to the second page.
- [x] From the second page, click "1"
- [x] Verify that you are taken to the first page.

#### In a deployment with more than 10 users and less than 21, the pagination bar has a link to go to the next page when I'm in the first page (">" arrow)
- [x] Go to Settings -> Users
- [x] Verify that there is pagination 
- [x] From the first page, Verify that there is pagination arrow to the next page
- [x] Click the ">" arrow
- [x] Verify that you are taken to the second page.
- [x] From the second page, click "<" arrow
- [x] Verify that you are taken to the first page.

**Comment by jshorland** [comment] 2018-02-14 23:08
PASSES QA!

**Comment by rowasc** [comment] 2018-02-14 23:39
@jshorland :woo OK great! We can deploy this week then.  thanks

**Comment by rowasc** [comment] 2018-02-19 14:36
@jshorland I just deployed to prod and re-tested this. It looks fine.

**Comment by jshorland** [comment] 2018-02-19 19:12
Boom. Closing.

**Comment by jshorland** [comment] 2018-02-19 19:13
Great! can we close @rowasc

**Closed** 2018-02-19 19:14 UTC
Labels: Bug, DREAMS, P0 - Unbreak now!
