### ISSUE TITLE
Implement improved location picker

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#1327] opened 2016-08-04 04:30 UTC
<img width="507" alt="screenshot 2016-08-04 16 28 47" src="https://cloud.githubusercontent.com/assets/7965/17390356/8ce5133c-5a60-11e6-95bf-3d5338cf3297.png">

<img width="512" alt="screenshot 2016-08-04 16 30 17" src="https://cloud.githubusercontent.com/assets/7965/17390386/c38f4542-5a60-11e6-8b3a-1eec48e61fdf.png">
- Needs full specification
  - Do we allow users to edit a caption/label for the location?

**Comment by rjmackay** [comment] 2016-09-08 22:09
From #783 
---
I've improved the location picker so that its search control behaves more like the global 'searchbar' and so that the input doubles as the location field's **_value_**.

![location field](https://cloud.githubusercontent.com/assets/1136279/16629849/313ff244-437d-11e6-9616-6b70950eabb4.png)

The assumption here is that, when a user types anything into the input, it provides buttons to "Search" or "Use your current location," as well as a brief list of search results for addresses and nearby venues. Selecting "Search" would fill the "results" list with a more complete list of results, if they didn't already see something that matched.

Whatever they leave in that field, either via selecting a search result or manually typing lat and long, will be captured as the value they're passing along to the post.

**Comment by rjmackay** [comment] 2016-09-08 22:11
Ideally this should implement #929 and include a note about where locations come from.

**Comment by rjmackay** [comment] 2016-09-13 02:20
@willdoran This needs spec + sizing. Could you take a look at the info above an let me know if this needs more info to implement? Then estimate size if you can.

**Comment by willdoran** [comment] 2016-09-13 13:10
To be added:
- [ ] Geographic search service
- [ ] Predictive typing search with suggestions
- [ ] Use current location
- [ ] Search button; returns full search
- [ ] Wire Search service to post-location-field

Relies on:
- [ ] UI to display results' origin - where/how does that information appear?

Questions:
1. How many search results can be returned?
2. If the search is also performed while the user is typing, how is typing "Montreal" and seeing suggested results, different from typing "Montreal" and hitting search?
3. Should "Use your current location" also contain a tooltip to explain that location based search will have to be authorised by the user?
4. For the requirement:
**"Whatever they leave in that field, either via selecting a search result or manually typing lat and long, will be captured as the value they're passing along to the post."**
What if what they live in that field does not match a geographic location?

Based on what I listed I would estimate this to take 5 days + 1 day for review

**Comment by rjmackay** [comment] 2016-09-15 01:07
Also need:
- [ ] Remove 'use my location' control from map

> Geographic search service

We already have a geocoded search using OSM.. did you mean something else?

> 2.  If the search is also performed while the user is typing, how is typing "Montreal" and seeing suggested results, different from typing "Montreal" and hitting search?

I think this actually means we could remove the 'Search for "Montreal"' button entirely...

> 4. Whatever they leave in that field, either via selecting a search result or manually typing lat and long, will be captured as the value they're passing along to the post.

I don't think this requirement makes sense now I read it. We have another task for capturing this as a kind of 'label' on a location.. that should be out of scope here. But I'm not clear if @brandonrosage meant something else too.

@brandonrosage can you look at Will's questions above?

**Comment by brandonrosage** [comment] 2016-09-15 16:26
@willdoran: I've staged the solution for this pattern in the [`f-location-picker`](https://github.com/ushahidi/platform-pattern-library/tree/f-location-picker) branch of the PL. You can sample it in the "[Post: Add](http://preview.ushahidi.com/platform-pattern-library/f-location-picker/assets/html/5_layouts/post-add.html)" layout. It will eventually be merged into a future sprint-specific branch (e.g. `sprint-12`) when the issue is assigned to a sprint.

> How many search results can be returned?

I'd suggest 10, implying that narrowing the search with a more specific value will bubble a specific result to the top.

> If the search is also performed while the user is typing, how is typing "Montreal" and seeing suggested results, different from typing "Montreal" and hitting search?

Great point. I've removed the button, making the pattern entirely driven by automatic search results. Feasible, I hope.

> Should "Use your current location" also contain a tooltip to explain that location based search will have to be authorised by the user?

I don't think so. First, I think the browser's subsequent dialog window asking them to grant permission is reasonable -- we don't need to warn them that that dialog is coming. Second, if we did warn them, it'd have to be exclusively for users we know (using client-side code) haven't already granted permission to share their location with ushahidi.io.

> For the requirement: "Whatever they leave in that field, either via selecting a search result or manually typing lat and long, will be captured as the value they're passing along to the post."
> What if what they live in that field does not match a geographic location?

This is great clarifying point. I think what you're suggesting is correct: Location fields should assume a value that includes a lat/lng -- not accepting simple text values. 

My previous direction assumed a use case for authors wanting to offer a simple text description. But that's not going to work, for so many reasons. If a survey needs to collect that kind of data, it can use a text field.

This means that the user will rely on the provided search results to select their value (short of dragging the map marker). It follows, then, that the searchbar will need to listen for addresses _as well as_ explicit lat/lng strings, so it can provide both address and lat/lng results.

![results](https://cloud.githubusercontent.com/assets/1136279/18557765/e7803934-7b35-11e6-8840-0626081cdcb8.png)

Am I overlooking anything here?

**Comment by brandonrosage** [comment] 2016-10-07 18:31
@seth While this waits for a sprint, can you debug the issues with this pattern where the "searchbar" doesn't align properly in *all* cases?

There's already a `f-location-picker` branch.

**Comment by jshorland** [comment] 2016-10-28 17:13
this doesn't appear to be working fully in qa.ushahididev.com. I get a similar pattern in main map search, but nothing in add-post.

**Comment by willdoran** [comment] 2016-10-28 17:15
@jshorland will check

**Comment by jshorland** [comment] 2016-10-28 17:18
Here's gif of current status:
![screen capture on 2016-10-28 at 13-16-41](https://cloud.githubusercontent.com/assets/3224856/19815476/11df1c5c-9d11-11e6-8b91-e5e82574b15a.gif)

**Comment by jshorland** [comment] 2017-03-07 06:58
@angamanga as I understand it, the search should happen as i type and not require me to click "search". And when I select a search result, it's not clear I need to click on it because my mouse turns into a cursor that seems to indicate i need to type (would be nice to be the pointer hand that indicates a click). And finally, when I click on "use my location" nothing happens. Gif attached. cc: @brandonrosage anything I'm missing?

**Comment by Angamanga** [comment] 2017-03-07 08:32
@jshorland Ah, i see, i'll add the search when typing. But do we need the 'search'-button then? The use your current location-button should work, I'll check why it doesn't...

**Comment by Angamanga** [comment] 2017-03-07 13:51
@jshorland I have added fixes, you can qa them here: http://qa.location-picker-fixes.ushahidilab.com/posts/create/8. The 'use current location' is only working on https so I simply removed that box when not on https. Not sure if we have a testing-site that is on https?

**Comment by jshorland** [comment] 2017-04-12 00:47
@Angamanga sorry this took me so long :-/ 
- it definitely now searches as I type! yay!
- I've lost my "use your current location" button, though

And one other minor thing I don't think we thought about when scoping this -- I can't actually exit out of the dropdown search box, so it covers the map and I can't actually see the map if I want to drag and drop the pin instead of typing in a location. Just a little annoying UX issue I'm adding on here.

**Comment by Angamanga** [comment] 2017-04-20 18:39
@jshorland The "use your current location"-button is only visible on https and therefore it is not visible on qa.ushahididev :( Do we have a testing-site that is on https? I'll sort out the closing of the dropdown!

**Closed** 2017-06-07 02:25 UTC
Labels: P1 - Immediate, Pattern to implement in client, Stage: Waiting to deploy, Theme: Maps
