### ISSUE TITLE
Allow visitors of a deployment to choose language to view from homepage

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1651] opened 2017-03-21 08:39 UTC
### Expected behaviour
When visiting a deployment made available in another language, It would help to be able to access it in English as well.

Something like what we had on v2 deployments here
![screenshot](https://drops.azureedge.net/drops/files/acc_531939/AXpH?rscd=inline%3B%20filename%3DScreen%2520Capture%2520on%25202017-03-21%2520at%252011-37-39.gif&rsct=image%2Fgif&se=2017-03-21T09%3A08%3A17Z&sig=EAy5UrELV%2FK8f0xarlw%2BYePZqacQN%2Bq1cF1RZPyRTFk%3D&sp=r&sr=b&st=2017-03-21T08%3A08%3A17Z&sv=2013-08-15)

Context: The SBTF is informally helping the deployer for https://peru.ushahidi.io get volunteers to help with managing data around the floods in Peru. 

Comment from Per Aarvik: "Can this instance be multilingual? English/Spanish? If so - it would dramatically expand the number of volunteers that could contribute..."

### Actual behaviour
There's no option for me to switch languages on the home page

cc @brandonrosage @jshorland

**Comment by aoduor** [comment] 2017-03-21 08:40
Flagging coz this does sound like an urgent request.

**Comment by rjmackay** [comment] 2017-03-21 19:29
Should this be a per user setting? or just changable for the current session?

**Comment by Angamanga** [comment] 2017-03-21 19:36
@brandonrosage Do you have any suggestions where to put it this kind of dropdown?

**Comment by aoduor** [comment] 2017-03-21 20:11
This should be per session I would think?

Handheld Sent,

Angela Oduor Lungati,
Director of Community Engagement,
Ushahidi | www.ushahidi.com

**Comment by jshorland** [comment] 2017-03-23 20:42
@Angamanga I'm going to move this back to design column and assign @brandonrosage

**Comment by brandonrosage** [comment] 2017-03-24 14:04
My recommendation is to include this control in the mode context. After the mode bar (menu), It contains the most global content. The toolbar, by contrast, is intended to display controls for manipulating the content immediately in view -- not the whole deployment.

So we get this:

![medium screen](https://cloud.githubusercontent.com/assets/1136279/24297150/a97d0412-106f-11e7-9a81-af8ebb2aa0f3.png)

And on small screens: 

![small screen](https://cloud.githubusercontent.com/assets/1136279/24297163/b9093450-106f-11e7-9aeb-e2b93d7c0f12.png)

This is demonstrated in [the Map layout in the `develop` branch of the PL](http://preview.ushahidi.com/platform-pattern-library/develop/assets/html/5_layouts/map.html). I think we should include this "tool" in the mode context for each top-level view (but not their children):

- Map
- Timeline
- Activity
- Settings

Ideally, I think this control listens to a few things:

1. It defaults to the language defined in the deployment's general setting for language.
2. When changed by the user via the mode context, it changes the language used in the UI for that user.
- If that user is logged in, it changes the language in the UI indefinitely, until they change it again.
- Else, it changes the language in the UI for the duration of their session.

**Comment by jshorland** [comment] 2017-03-24 20:59
@Angamanga -- this is good to go on design! implement early next week if you can?

**Comment by Angamanga** [comment] 2017-03-25 12:43
@brandonrosage If a logged in user also is an admin of the site, should this new language-selector change the default language to the site then too?  Like when using the selector in settings->general->select language?

**Comment by Angamanga** [comment] 2017-04-19 07:04
@jshorland This can be QAd here: http://qa.language-switcher-1651.ushahidilab.com/. The behaviour is this:
1. If the user is logged in, the chosen language is stored and will stay the same until the user changes the language again.
2. If the user is not logged in, the chosen language remains for the current session only.
3. If no language is set, the site-default language is used.
Language is changed when user selects language in the dropdown and also when logged in/logged out (if the user previously had chosen a language).

**Comment by jshorland** [comment] 2017-04-20 00:12
Passes QA. LET'S GET THIS DEPLOYED!

**Comment by jshorland** [comment] 2017-04-20 00:19
@Angamanga I take that back -- I found just one small thing. On the window tab on chrome, somehow "ushahidi" is translated into arabic I believe, but I can't get it to change no matter how many times I log in or out or change the language itself. Any idea what the behavior might be?

**Comment by Angamanga** [comment] 2017-04-20 11:58
@jshorland I could not reproduce it but I tweaked it a bit to set the translate and set the page-title, please check if it still is an issue?

**Comment by jshorland** [comment] 2017-04-20 16:21
@Angamanga BOOM. not an issue. 

Passes QA, moving to waiting to deploy!

**Comment by rjmackay** [comment] 2017-06-07 02:26
@jshorland do we need a task to track adding this to mobile?

**Closed** 2017-06-07 02:26 UTC
Labels: Enhancement, Frontend, Mobile, P1 - Immediate, Stage: Waiting to deploy
