### ISSUE TITLE
CSV Column to Survey field Mapping Not working

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1562] opened 2017-01-29 15:52 UTC
I successfully uploaded a CSV file but was unable to proceed with import because the platform didn't show me what fields i'm mapping to my CSV columns. See below.

![screenshot](http://i.imgur.com/g5f3YbX.png)

**Comment by pedrofuentes** [comment] 2017-01-30 18:52
@rjmackay @aoduor any progress on this? we are blocked on uploading information to chileayuda.ushahidi.io from our csv files, thanks.

**Comment by aoduor** [comment] 2017-01-31 07:46
@pedrofuentes - i've got @willdoran investigating this issue. What browser are you using?

**Comment by willdoran** [comment] 2017-01-31 14:09
@pedrofuentes I've created an account on your deployment, would you give it admin rights?

**Comment by willdoran** [comment] 2017-01-31 15:43
@tuxpiper @rjmackay I can confirm this is happening for ctfk.ushahidi.io, it appears to be the csv failing to parse in the api but I can't get further. Would one of you ping me when you are on?

**Comment by pedrofuentes** [comment] 2017-01-31 22:52
@willdoran now you are an admin

**Comment by willdoran** [comment] 2017-01-31 23:03
@pedrofuentes thanks I think I have found the problem, will fix as quickly as possible!

**Comment by pedrofuentes** [comment] 2017-02-01 17:06
Awesome @willdoran ! were you able to fix it?

**Comment by aoduor** [comment] 2017-02-07 12:00
Ping @willdoran confirming this still isn't working for me :(

**Comment by willdoran** [comment] 2017-02-07 16:27
@aoduor hmmm nuts, Ok let me double check again

**Comment by willdoran** [comment] 2017-02-07 17:29
@pedrofuentes It should be fixed and live now, sorry for the delay, can you confirm if the problem is fixed for you?

**Comment by pedrofuentes** [comment] 2017-02-07 21:40
@willdoran yes I got confirmation that is working, thanks!

**Comment by willdoran** [comment] 2017-02-08 00:39
@pedrofuentes Wonderful!

**Closed by willdoran** 2017-02-08 00:39 UTC
Labels: Bug, P0 - Unbreak now!, Stage: Testing
