### ISSUE TITLE
Enhancement - Add New Tables to Activity Page to count Targeted SMS Messages Received and Crowdsourced Posts

### ISSUE THREAD

**Issue by dukedanny** [ushahidi/platform#3163] opened 2018-07-16 14:47 UTC
### Overview
DREAMS partners need a way to accurately count messages sent and received via targeted surveys and they need to be distinguished from other posts. Currently data view does not do this. Instead of refactoring our data models, we will implement two new analytics charts to display the required data, and these charts will be displayed in the Activity Page.

### Requirements
- This should be feature flagged using the current targeted survey feature flag
- There should be 2 new tables in the 'Activity' page 
  - The tables should look like those mocked here: https://docs.google.com/spreadsheets/d/1VZrArtQJYfzEv-qgHSdzrZVjmairHFTmtEHoTMtqrW4/edit?userstoinvite=carolyn@ushahidi.com&ts=5b6335db&actionButton=1#gid=1660507835
- the tables should be able to be filtered by date
- The data in the chart should respect user permissions.
- If a survey does not have data, then it will show up as 0s across the table
- If there are no surveys, then a message will show: You don't have any (targeted/crowdsourced) data to show or you may need to log in.
-Formatting markup:
https://docs.google.com/spreadsheets/d/1VZrArtQJYfzEv-qgHSdzrZVjmairHFTmtEHoTMtqrW4/edit?userstoinvite=carolyn@ushahidi.com&ts=5b6335db&actionButton=1#gid=1660507835

### Test Scripts
- [ ] Go to activity view without targeted surveys enabled, you should not see a new activity chart
- [x] Go to activity view with targeted surveys enables, you should see new activity tables: 1 for Crowdsourced Surveys and 1 for Targeted SMS Surveys
- Make sure that the test environment has posts from each data source 
- Targeted SMS Surveys
  - [x] should only include surveys that are targeted surveys
  - [x] Inbound Response Messages should be the count of messages that were received as a response to that survey
  - [x] Outbound Surveying Messages should be the count of messages that have been sent out for that survey
  - [x] Unique Recipients of Targeted Survey should be the count of people who have received at least 1 message for a targeted survey
  - [x] Unique Responders to Targeted Survey should be the count of people who have responded to any message from a targeted survey
  - [x] totals should equal the sum of each column
- Crowdsourced Surveys
  - [x] should only include surveys that are NOT targeted surveys
  - [x] Crowdsourced Posts should be divided by data source and should be the count of posts that matches that data source
  - [x] Totals should be the sum of each column
  - [x] unstructured posts should have their own row and total unstructured posts should be in Crowdsourced Posts column
-----
- add various filters for time
- [ ] all columns should update based on post-date, except:
- [ ] Outbound Survey Messages should update based on when the message was sent
- [ ] Unique Recipients of Targeted Survey should be based on when the message was sent

-------
- Filter by date
- [ ] results should be the same as above but only include messages from the selected dates

**Describe the problem**

> The number of posts is a summation of the number of individual messages sent out + number of responses.

**Where was the bug observed**
Include Deployment and page URL (e.g. "https://test.ushahidi.io/views/map")

> https://sparkedwomen.ushahidi.io/views/data

**To Reproduce**

> 1. Go to https://sparkedwomen.ushahidi.io/views/data
> 2. Log in as Admin
> 3. Click on Data View
> 4. Observe the number of reports and scroll through posts.
> 5. See error

**Expected behavior**

> Number of reports is supposed to reflect the number of responses only.

**Is there a workaround? What is it.**
Describe any ways to get around this bug, even if they are not elegant.

**Screenshots**

![image](https://user-images.githubusercontent.com/437728/42765194-1ff746a0-8920-11e8-8225-90b08e2e3cd0.png)
**URL / Environment where this happened**
> https://sparkedwomen.ushahidi.io/views/data
Environment: Frontline + Africastalking on .io deployment

**If the bug is datasource related (e.g. SMS or Targeted SMS), please specify the configuration details (e.g. Frontline + Clickatell, etc):**

**Desktop Hardware Details (please complete the following information):**

**Smartphone Hardware Details (please complete the following information):**

**Additional context**

**Comment by jrtricafort** [comment] 2018-07-16 14:53
@dukedanny @Hazellaura Can you clarify the existing behavior? What is being counted currently? It sounds like what is being counted currently is the number of messages sent out, plus the number of responses, is that correct? Or is it just the number of messages sent out that is being currently counted?

@willdoran For background, the reason why this is coming up as a priority from Hazel is since the program will be closing out soon (September 2018), she needs a way to count responses. It sounds like the problem here is a UX issue (not necessarily a bug), and that it is tied to our data model for targeted surveys. Is that correct? If so, we should talk about how we can either fix it, or see if we can work out a process with Hazel to get her DB-pulled stats of the numbers she needs to pull in August.

**Comment by jrtricafort** [comment] 2018-07-16 21:54
@rowasc FYI This will probably need to be addressed in some form (either product enhancement or database pull) in Cycle 8, but still scoping w DREAMS team to understand needs. See comment above.

**Comment by dukedanny** [comment] 2018-07-17 12:11
@jrtricafort 
Yes, this is a correct representation of the issue.

> Current behavior: Posts = messages sent + responses received
Desired behavior: Posts = responses received only

A targeted SMS sent out should not increment the number of reports. Only responses should.

**Comment by jrtricafort** [comment] 2018-07-17 19:42
Thanks @dukedanny .

@willdoran Can you see my comment above? This is tied to our data model, correct? We need to give 
@Hazellaura some way to pull the metric of total reports, not including sent targeted surveys.

@Hazellaura How often do you need to pull these stats for DREAMS? It's just a one-time thing, per deployment, correct?

**Comment by jrtricafort** [comment] 2018-07-23 14:12
Cool thanks @willdoran . Let's discuss this Friday in advance of Cycle Planning for Cycle 8 next week.

**Comment by jrtricafort** [comment] 2018-07-27 16:02
From @willdoran : This will require substantive API changes, and possibly some light DB migration work to retroactively re-count.

**Comment by jrtricafort** [comment] 2018-07-31 23:16
Next action here is for us to have a quick meeting between platform and DREAMS team to confirm this. I am setting this up for Thursday.

**Comment by rowasc** [comment] 2018-08-01 19:49
Excellent. Removing the `consider for upcoming` tag as we considered it and added it :D 

@jrtricafort : for awareness, @crcommons should be added to that call as she will work on it

**Comment by rowasc** [comment] 2018-08-01 19:49
Nevermind she was already invited. Sorry

**Comment by jrtricafort** [comment] 2018-08-02 16:01
Had a very in-depth discussion on this today. Will update the description. See this document for more details in the meantime:
https://docs.google.com/spreadsheets/d/1VZrArtQJYfzEv-qgHSdzrZVjmairHFTmtEHoTMtqrW4/edit#gid=0

**Comment by jrtricafort** [comment] 2018-08-02 16:19
*Actions from Targeted SMS Survey Counting Call*    

- @willdoran  Investigate the “D vs F” bug (see spreadsheet)-- create a new github issue to track 
- @crcommons  Spec the implementaiton of the new table for the Activity page (e.g. tied to existing Targeted Survey feature flag, should support existing date filtering widget, etc etc)
- @jrtricafort Scope the new table - particularly coming up with useful column labels w input from @dukedanny 
- @dukedanny Update @Hazellaura  on this conversation
- @jrtricafort update this github issue #3163 with a new description and title

Full notes from call:
https://docs.google.com/spreadsheets/d/1VZrArtQJYfzEv-qgHSdzrZVjmairHFTmtEHoTMtqrW4/edit#gid=0

**Comment by willdoran** [comment] 2018-08-02 19:08
> Total posts should equal Targeted Survey messages sent + unsolicited SMS messages received + posts from other non-sms data sources

This is not accurate, Total Posts is the total Posts in the system, there is not a clear relationship between messages and posts. It won't be possible from the UI for someone to figure out the exact number of Targeted Survey messages sent, unsolicited texts and posts from other sources.

Total Posts is:
- The number of Targeted Survey Recipients
- plus The number inbound messages received not related to targeted surveys from all data sources, both with and without form ids

So essentially, it is the total number of Posts in the system but it would be extremely difficult for a user to reverse engineer that number or indeed to figure it out, I would leave it as simply the total posts in the system as displayed on the Posts page 

NOTE: the correct nomenclature may be reports?!?! I don't know but we should nail that down.

**Comment by willdoran** [comment] 2018-08-02 19:11
This is good so far but we will need to be able to divide the the posts by Survey or at least group them by Survey, so we might want to do columns as you have described but also add rows per survey that break down the numbers.

**Comment by jrtricafort** [comment] 2018-08-03 15:55
@crcommons @willdoran @rowasc 

Will and I discussed and we decided to implement in Lumen first. We should get Lumen landed by end of next week (August 10). I think we should set an internal goal for this feature to be delivered for DREAMS by August 17 (two weeks from now). Let me know if that's realistic (assuming Lumen lands by Aug 10)

If we are running behind on that, then we can backport to Kohana and roll out to DREAMS with Kohana.

@dukedanny @Hazellaura please confirm if August 17 is early enough for you to begin using this enhancement to do DREAMS metrics counting and reporting.

**Comment by jrtricafort** [comment] 2018-08-03 22:13
As discussed in the Slack channel, we will use the mockup in this document as the format for our first iteration, then we will get the feedback from the DREAMS team

https://docs.google.com/spreadsheets/d/1VZrArtQJYfzEv-qgHSdzrZVjmairHFTmtEHoTMtqrW4/edit?userstoinvite=carolyn@ushahidi.com&ts=5b6335db&actionButton=1#gid=1660507835

There are two new tables. We should only show those surveys that are relevant (i.e. we should only show Crowdsourcing Surveys in the first table, and Targeted Surveys in the second)

@dukedanny @Hazellaura Let us know if you have feedback on this and if August 17 is a good date.

@rowasc @willdoran @crcommons This should be unblocked now. Let me know if August 20 is a good date to deliver this, assuming Lumen lands by Aug 10.

**Comment by jrtricafort** [comment] 2018-08-03 22:15
Assigned to just @crcommons now.

**Comment by willdoran** [comment] 2018-08-08 20:30
@crcommons This looks good, only one thing missing is:
- What happens when there is no data? We should probably display a message rather than a blank table. Can you add that as a requirement and also include it in the tests?

**Comment by jrtricafort** [comment] 2018-08-20 18:26
@crcommons How is this going? Are we on track to close out by the end of the cycle?

**Comment by jrtricafort** [comment] 2018-08-20 20:20
Update from @rowasc and @willdoran - This was built on Lumen since we expected Lumen to have been landed by this point. Since it is not, we have decided to backport to Kohana. @willdoran is working on this, expecting to be done sometime today and will report back with more info. After that, @rowasc will test and deploy this week for DREAMS since @crcommons is back next week.

**Comment by rowasc** [comment] 2018-08-21 16:34
We're doing some last fixes then I'll test today and report back

**Comment by rowasc** [comment] 2018-08-21 20:10
Tested this issue . Found 1 bug so far: 
Steps to reproduce: 
- Start a new targeted survey
- Go to activity and check the targeted survey activity
    - `Unique Responders to Targeted Survey should be the count of people who have responded to any message from a targeted survey` => I see `1` for a survey that I just created that has  0 responses

**Closed** 2018-08-23 23:56 UTC
Labels: DREAMS, consider for upcoming cycle
