### ISSUE TITLE
UI: Hanging Draft Report  

### ISSUE THREAD

**Issue by heatherleson** [ushahidi/platform#315] opened 2015-08-13 13:06 UTC
After I created an account for the demo, I created a report. But I did not finish the report. I proceeded to click around the software. 

Clicked on "all Posts"
At the top was a "draft report". I tried to click on it but it just closed. 
Also, the "list view" of all posts is missing the content. Only after I click on "draft report", does it allow me to see the 'list view;'

All of this begs the question - where is my draft report and how can I edit it if I can't click on it to continue?

Firefox, OS

<img width="1075" alt="screen shot 2015-08-13 at 3 55 37 pm" src="https://cloud.githubusercontent.com/assets/1216707/9250240/2770918e-41d4-11e5-99b0-58fcc5a61323.png">

<img width="1013" alt="screen shot 2015-08-13 at 4 04 42 pm" src="https://cloud.githubusercontent.com/assets/1216707/9250387/324859ba-41d5-11e5-9f93-532404f77d56.png">

**Comment by rjmackay** [comment] 2015-08-17 00:19
Not 100% sure what happened with this.. I *think* we're seeing issues because you don't have permission to view drafts..

**Comment by rjmackay** [comment] 2015-08-31 03:48
- The 'status: draft' reflects the current filters .. I'll keep track of further reports to see if that bit of UI is just confusing to users.

I'm not sure what happened with your draft report, I suspect you simply filtered to a view with no posts. But its not clear. For now I'm closing this out.. its useful feedback but not something I can action right now.
If you see similar issues, can you try to figure out steps to reproduce? Thanks @heatherleson !

**Closed by rjmackay** 2015-08-31 03:48 UTC
Labels: 4 - Done, Bug, P2 - Normal
