### ISSUE TITLE
Upgrade Deployment Plan fails on first try (when using a promo code)

### ISSUE THREAD

**Issue by crcommons** [ushahidi/platform#1798] opened 2017-06-12 17:33 UTC
### Expected behaviour
After upgrading the deployment plan using a promo code, it should reroute to the deployment homepage with newly upgraded features available; it should also send confirmation email.

### Actual behaviour
Instead, the page reroutes to deployment homepage with original plan features; no email is sent. Take multiple tries for upgrade to work properly.

### Steps to reproduce the behaviour/error
1. Create a new deployment and log in.
Settings>Plan>Select Plan (e.g. Responder)>enter coupon code (have not tried to reproduce when purchasing plan)>Enter password>Hit "Done"

This reroutes page back to deployment homepage without the upgrade. No email received either.

**Comment by jshorland** [comment] 2017-06-13 21:04
Related to #169?

**Comment by jshorland** [comment] 2018-02-27 23:59
Can't reproduce. Closing.

**Closed by jshorland** 2018-02-27 23:59 UTC
Labels: Bug
