### ISSUE TITLE
QA new environments on AWS

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#3152] opened 2018-07-09 20:13 UTC
- [x] Create test deployments in `passage` environment from scratch ~based on copying CSV exports forever, quakemap.ushahidi.io~
- [x] Run web regression scripts https://ushahidi.ontestpad.com/script/27#1179//
- [ ] Run mobile regression tests (https://ushahidi.ontestpad.com/script/28)

**Comment by rowasc** [comment] 2018-08-09 21:26
Setting up a 5 since it's a multi day thing . cc @Eve-wanderi is executing this, leaving it assigned to both of us

**Comment by rowasc** [comment] 2018-08-14 02:36
@Eve-wanderi can you confirm when you are done with the passage environment regression testing? thanks

**Comment by rowasc** [comment] 2018-08-21 13:02
@Eve-wanderi can you run the mobile regression ONLY on https://documenthate.passage.ush.zone/ 
with this test script https://ushahidi.ontestpad.com/script/28#// ? Thanks

**Closed** 2018-08-28 12:57 UTC
