### ISSUE TITLE
Survey Permissions: Limit who can view survey responses

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1560] opened 2017-01-27 09:51 UTC
In addition to determining who can submit responses to a survey, I'd like to be able to determine who can view posts to a certain survey.

An example:

- I have survey A, and Survey B.

- I want to be able to limit who can view posts assigned to survey B, e.g, Angie should be able to view posts from Survey A, but not Survey B.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-641

**Comment by brandonrosage** [comment] 2017-02-08 15:45
I think the only elegant way to accomplish something like this would be to provide an option to more narrowly define who can see any given survey -- not just its posts, but its entire presence in the deployment.

Otherwise, I think we'd be pulling the rug out from under the function and hard-won value of post statuses. Here's why:

When we first released Version 3, our approach to the visibility of posts was deliberately flexible and free-form. There was intentionally no all-purpose "Published" or "Under review" status to apply to posts. Instead, we said, "You define explicitly who needs to see any given thing. We won't apply our labels to anything."

@rjmackay later [wrote in an Ushahidi blog post](https://www.ushahidi.com/blog/2016/09/06/making-post-status-easier-to-use-and-understand), "Deployers encountered a confusing dialog that let them change 'Who can see' each post. Deployers told us they were really confused by this, and the vast majority chose to make posts visible to 'Everyone.'"

So, as you know well, we then simplified the product to use the "Published," "Under review," and "Archived" statuses for posts across the board, each with well-defined boundaries for who can see posts labeled with each. And it appears to have successfully addressed the problem it set out to solve.

Now, I understand your request above is not about determining who can see any given post, but about who can see a whole group of posts, organized by survey. It's too small a distinction, however, in my estimation because, once you make exceptions to the definitions for what post statuses mean, they become meaningless.

For example, imagine we offered a control for each survey that allowed deployers to say "only _admins_ can see responses to this survey." And the deployer proceeded to choose that option, review incoming responses, and publish them.

Then, when one of their teammates with "Editor" permissions viewed their Map and chose to show "Published" responses across all their surveys, they wouldn't actually be seeing all "Published" responses. They'd be seeing an subset created by an exception to the definition of the filter controls we're providing them -- which isn't at all transparent to them.

So, again, the only way I see this working is if we offered boundaries that deployers could create around specific surveys, making them completely invisible to certain users -- as if they didn't exist, in those users' eyes. And that point, I'm very interested to know what the user story is behind that feature.

**Comment by rowasc** [comment] 2020-01-02 20:23
@aoduor  I am not sure but is this https://github.com/ushahidi/platform/issues/1534 a duplicate of this ticket? Do you remember why this was needed? Nat mentioned funders, but I don't imagine that we actually would share that level of detail with funders often?

**Comment by aoduor** [comment] 2020-01-07 10:04
No, this is different. 

#1534 is referencing a donor/funder being able to see, say SMS/Twitter posts which haven't been structured/assigned to a specific survey.

Let me give an example to describe this one.

I have survey A, and Survey B. 

I want to be able to limit who can view posts assigned to survey B, e.g, Angie should be able to view posts from Survey A, but not Survey B. 

Makes sense?

**Comment by rowasc** [comment] 2020-01-07 13:56
oh. That makes perfect sense to me, yes. I can see how it'd be useful, especially in large deployments with >10 volunteers that don't all have the same trust levels etc. Thanks Angie

**Closed** 2024-06-19 10:48 UTC
Labels: Feature request, Theme: Forms, Theme: Users and roles, Cleanup/Alive
