### ISSUE TITLE
Add Targeted Survey UI

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#2525] opened 2018-02-27 19:13 UTC
### Overview
The new Targeted Survey UI is designed in a step wizard manner to enable easy creation of Surveys that are intended to be sent to a specific audience, initially via SMS. The feature is currently intended to address the needs of the DREAMS project partners in initiating communications with the individuals they support.

### Requirements
- [x] Targeted Survey UI route distinct from existing Survey Creation route
- [x] Targeted Survey sub directory within Survey directory
- [x] Targeted Survey Template respecting the layout defined by the design
![Screen Shot 2018-02-27 at 14.11.05.png](https://images.zenhubusercontent.com/5a6a44264b5806bc2bc4546d/b2f800a4-a989-4249-b93d-27610bfa7a1b)
- [x] Targeted Survey Controller/Directive
- [x] Targeted Survey wired to routes and modules for Settings
- [x] Targeted Survey test/spec-file for controller/directive
- [x] Targeted Survey link should not appear if Feature Flag is not enabled
### Dependencies
- None

### Test script
- [ ] Follow the requirements, all folders, components and routes stated in requirements should be in place

**Comment by rowasc** [comment] 2018-02-28 13:47
@Angamanga do we need a PL change here?

**Comment by Angamanga** [comment] 2018-03-01 12:56
@rowasc No styling-changes but it would be good to add it to the settings in PL to keep it in sync with the platform. But thats a small part.

**Comment by Angamanga** [comment] 2018-03-01 13:04
@rowasc @willdoran Is there another issue for the backend of this, what endpoint and what format does the backend need the information in? In that case a dependency to this issue in order to complete this one... trying to find dependencies to avoid the same situation as previous cycle when many issues were completed at the same time because they were connected to each other...

**Comment by rowasc** [comment] 2018-03-01 13:38
@Angamanga good point. 
We should make a habit of documenting the endpoints for the client-side work when there is a new one or new params for it. 
I created this ticket (https://github.com/ushahidi/platform/issues/2557)  so you can add the layout in it for reference/to keep it sync'd.  Can you spec it since you know best what needs to happen for this?

**Comment by willdoran** [comment] 2018-03-01 13:42
@Angamanga @rowasc There is an issue for the backend but it needs deeper group discussion. That will hopefully happen in todays meeting

**Comment by Angamanga** [comment] 2018-03-01 18:53
This looks like a duplicate of #2526?

**Comment by rowasc** [comment] 2018-03-01 18:55
@Angamanga my understanding is that this ticket refers more to the set up of the elements that will allow us to do everything else and delegate it amongst ourselves correctly without major conflicts/issues. But I've been wondering about how to word it / spec it correctly and was waiting for our call to do so.

**Closed** 2018-04-18 02:24 UTC
Labels: Client
