### ISSUE TITLE
System does not send out All Questions that have been created in a survey.

### ISSUE THREAD

**Issue by Eve-wanderi** [ushahidi/platform#2830] opened 2018-04-23 19:48 UTC
### Expected behaviour
Incase a user adds 3 or more questions recipients should receive all questions which were added when creating the survey.

### Actual behaviour
System sends out just the first question.

### Steps to reproduce the behaviour/error

1.log into the Test Server
URL: http://targetedsurveytesting.v3-qa.ush.zone
User: qa@ushahidi.com
Password: testing
2.Go to settings>Surveys> New Survey> Send a targeted Survey vis SMS
3.Fill in the name of the survey
4.Fill in your target audience i.e ensure you use valid phone numbers you can use your mobile number
5.Add your Questions. ii.e Add a couple of questions >1
6.Publish your survey.
7.Check if the number you used in step 4 has received sms with all questions added in step 5.

![outgoing messages](https://user-images.githubusercontent.com/36038029/39149583-401b4392-4748-11e8-98c6-f7556198f7e1.png)

**Comment by kinstelli** [comment] 2018-04-23 20:13
Looking at the logs for Twilio, I think this is related to #2797, as is #2829.

**Comment by kinstelli** [comment] 2018-04-23 20:17
@Eve-wanderi - Did you respond to any of the messages in this survey? The 2nd and 3rd questions should only go out if the user has responded.

**Comment by Eve-wanderi** [comment] 2018-04-24 07:58
I cant send a response to the first question. Raised that as well https://github.com/ushahidi/platform/issues/2829

**Comment by kinstelli** [comment] 2018-04-26 19:56
Appears to be a duplicate of #2844. Closing this for clarity.

**Closed by kinstelli** 2018-04-26 19:56 UTC
Labels: Bug, P0 - Unbreak now!
