### ISSUE TITLE
CSV Import fields are blank when mapping in Firefox

### ISSUE THREAD

**Issue by chrisabo** [ushahidi/platform#3297] opened 2018-09-18 21:56 UTC
**Describe the bug**
In the Import process, when reaching the step where you map Survey Field to CSV column, the dropdown boxes for the CSV column are blank after the "Leave Empty" option.

**Where was the bug observed**
https://www.librarysites.io/settings/data-import

**To Reproduce**
1. Log in as admin user
2. Click on Settings -> Import
3. Click on Choose CSV file, select other options

**Expected behavior**
In other browsers, includign Chrome, Opera, and MS Edge, the dropdown boxes have options to select.

**Is there a workaround? What is it.**
Use a different browser

**Screenshots**
![firefox-csv-import-dropdown-blank](https://user-images.githubusercontent.com/43390092/45718703-ddefe900-bb52-11e8-9786-2ca1a4314a95.png)

**URL / Environment where this happened**
https://www.librarysites.io/settings/data-import

**Desktop Hardware Details (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 
 - Version: 62.0 (64-bit)

# Implementation Notes
- Repo: https://github.com/ushahidi/platform-client
- This looks like it's caused by an tag not having the value https://bugzilla.mozilla.org/show_bug.cgi?id=40545 , and not being closed

**Comment by rowasc** [comment] 2019-06-12 14:47
closing as duplicate of https://github.com/ushahidi/platform/issues/2603

**Closed by rowasc** 2019-06-12 14:47 UTC
Labels: Bug, Client, Community Task, Theme: Browser compatibility issues
