### ISSUE TITLE
Attributes are getting duplicated in create survey form.

### ISSUE THREAD

**Issue by rohit645** [ushahidi/platform#3898] opened 2020-03-24 21:37 UTC
**Describe the bug**
Attributes (Location in this case) are getting duplicated in create survey form as one clicks on save button muliple times and error persists.

**To Reproduce**
1. Change "text" to "varchar" here: https://github.com/ushahidi/platform-client/blob/develop/app/settings/surveys/survey-editor.directive.js#L144.
2. Go to 'create survey form'.  
3. Write survey name and description and add a field (e.g. Location).
4. Click on save button.
5. You will see an error message. Click on save again you will see error message again and it goes on.
6. Now go to survey list and again try to edit the survey you create above.
7. You will see that location field gets duplicated below the number of times you hit the save button. Screenshot is attached below.

**Screenshots**
![Screenshot from 2020-03-23 12-42-17](https://user-images.githubusercontent.com/33249010/77291243-e0ad3a80-6d03-11ea-8de7-e6454c6edc41.png)

**Expected behavior**
Attribute field added must not be duplicated again on hitting save button. It should appear once.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-142

**Comment by treasurechristain** [comment] 2020-10-14 02:06
@Angamanga @rowasc  I'm Amadikwa Joy N. An outreachy Applicant. Can I work on this issue please.

**Comment by Angamanga** [comment] 2020-10-14 11:09
@treasurechristain This is not open for the community yet. Please check here for other issues: https://github.com/ushahidi/platform/issues?q=is%3Aopen+is%3Aissue+label%3A%22Community+Task%22. @rowasc This will be fixed in v5 so I suggest we can close it?

**Comment by codedladiesinnovate** [comment] 2020-10-14 11:31
OK, thank you @Angamanga

**Comment by rowasc** [comment] 2020-10-16 20:13
I don't think I understand this issue. It specifically  requires changing the code to reproduce it, which doesn't make sense to me? What am I missing?

**Comment by Angamanga** [comment] 2020-10-19 07:08
@rowasc It is a part of another issue that is fixed. One of the field-types were wrong in the client, so when adding a new field and trying to save, that survey was still created but above problem was happening. This issue is to prevent the form to save if something goes wrong when saving the attributes. But since v5 has another structure, we can close this now I think.

**Comment by rowasc** [comment] 2020-10-20 20:34
Yeah, I think closing is the best here. Thanks

**Closed by rowasc** 2020-10-20 20:34 UTC
