### ISSUE TITLE
password reset keeps telling me the token is expired, even though i'm using it immediately.

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#799] opened 2015-10-26 21:30 UTC
Deployer has reported via support@ that "password reset keeps telling me the token is expired, even though i'm using it immediately"

I've resolved their issue, but need to check if there is a general issue with password resets on ushahidi.io

**Comment by aoduor** [comment] 2015-10-27 12:49
This is a dupe of #788.

**Closed by aoduor** 2015-10-27 12:49 UTC
Labels: Bug, Needs Triage, P1 - Immediate
