### ISSUE TITLE
UI: Timeline Chart missing lines

### ISSUE THREAD

**Issue by heatherleson** [ushahidi/platform#309] opened 2015-08-13 12:35 UTC
Clicked on Timeline for Categories.
The Graph for "positive reports" appears to be missing the line. 
The font is too small. 

Firefox, OS
<img width="1036" alt="screen shot 2015-08-13 at 3 33 45 pm" src="https://cloud.githubusercontent.com/assets/1216707/9249790/c2fdf3ca-41d0-11e5-8aae-d2fc73f93d83.png">

**Comment by rjmackay** [comment] 2015-08-16 23:42
@vbhv

**Comment by jshorland** [comment] 2016-05-02 21:14
Should be fixed alongside mustang design implementations

**Comment by rjmackay** [comment] 2016-06-28 03:50
Need steps to reproduce

**Comment by jshorland** [comment] 2016-07-12 21:37
I'm closing this -- I can't reproduce it.

**Closed by jshorland** 2016-07-12 21:37 UTC
Labels: 5 - Testing, Bug, P2 - Normal, Theme: Data vis
