### ISSUE TITLE
CSV Export not working 

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#2154] opened 2017-10-16 13:44 UTC
### Expected behaviour
I expected a CSV file download after a couple of minutes of clicking export to CSV

### Actual behaviour
I got the yellow progress bar for a while, and then a blank non descript error as shown below.
![screen shot 2017-10-16 at 16 37 31](https://user-images.githubusercontent.com/721918/31614915-86a3dfa6-b290-11e7-91dd-b833dfe5d692.png)

![screen capture on 2017-10-16 at 16-40-48](https://user-images.githubusercontent.com/721918/31614998-d09713ee-b290-11e7-90fe-c841a6f046f6.gif)

### Steps to reproduce the behaviour/error
* Log into qa.ushahididev
* Attempt to download a CSV file

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [x] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by jshorland** [comment] 2017-10-24 22:45
Still cannot get it to export large number of posts. See #2217

**Comment by rjmackay** [comment] 2017-10-25 04:29
Closing as a dupe of #2217

**Comment by rjmackay** [comment] 2017-10-26 08:33
This issue still happens when a download times out. We should at least try to give a sensible error

**Comment by rjmackay** [comment] 2017-11-01 00:24
@jshorland This would be much better fixed after Lumen is merged in. Its a long standing issue that CSV exports time out on large data sets. Whats needed for Uchaguzi? Is there a possibility of working around this?

**Comment by jshorland** [comment] 2018-02-28 00:23
Noting that this should be fixed with the CSV improvements.

**Closed** 2018-02-28 00:23 UTC
Labels: 2chaguzi, Bug, Theme: CSV
