### ISSUE TITLE
Cannot correct location information from posts pulled from Twitter

### ISSUE THREAD

**Issue by Shadrock** [ushahidi/platform#1265] opened 2016-06-22 18:03 UTC
**This is for the COMRADES deployment**: http://comrades.ushahidi.com/views/map
Notes come from a training with 7 very tech savvy users. 
### Expected behaviour

The ability to edit the location of a post pulled from Twitter by changing the location of the map icon.
### Actual behaviour

Unable to change the map icon (e.g. cannot grab it, nor click on the map to re-position it). 
### Steps to reproduce the behaviour/error
- Go to http://comrades.ushahidi.com/views/map
- Logon as Jess: 
  - email = jess@ushahidi.com
  - Password = jess123
- Sort by Unknown (_not_ COMRADES Activities)
- Go to Timeline view
- Find the post by k_meesters dated June 14, 2016 via Twitter ([this link should take you directly to it](http://comrades.ushahidi.com/posts/16))
  ![comrades twitter location correction](https://cloud.githubusercontent.com/assets/4574998/16277670/2d449490-3871-11e6-9015-e300173f2310.png)
- Click the button to edit. 
- Try to edit the location of the post. 
### Thoughts

It was interesting to look at this post with the COMRADES training group because k_meesters was one of the trainees. I asked him where the location information came from. He said he enabled Twitter to pull the location information from his phone. However, in this case it was wildly inaccurate because he was in Schipol airport at the time (roughly 3 miles away as the crow flies). This inaccuracy is probably due to what is known as "[multipath error](http://ieeexplore.ieee.org/xpl/login.jsp?tp=&arnumber=5606130&url=http%3A%2F%2Fieeexplore.ieee.org%2Fiel5%2F5599415%2F5606063%2F05606130.pdf%3Farnumber%3D5606130)" but shows the importance of being able to correct the incoming post even if the location information originated from the phone.

**Comment by rjmackay** [comment] 2016-09-13 17:57
@Shadrock In this case the issue is that the message needs to be assigned to a survey before it can be edited. The experience is a little confusing though.

**Closed** 2017-11-02 00:26 UTC
Labels: Bug
