### ISSUE TITLE
Languages should be listed in the actual target language

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#2384] opened 2018-01-02 23:34 UTC
### Expected behaviour
If I'm a Chinese-speaking user and I want to switch to Chinese, it should say "中文" not "Chinese" because I would need to speak English to understand that...
### Actual behaviour
<img width="317" alt="screen shot 2018-01-02 at 4 33 58 pm" src="https://user-images.githubusercontent.com/29209303/34504250-c29657fa-efda-11e7-9199-b103290ded51.png">

## Hints for solving this issue:
The code for the language-switcher lives here:
1. Template: https://github.com/ushahidi/platform-client/blob/develop/app/common/directives/language-switch.html
2. Directive: https://github.com/ushahidi/platform-client/blob/develop/app/common/directives/language-switch.directive.js

Translations are done with https://angular-translate.github.io/, you can see an example of how translations are made here:
https://github.com/ushahidi/platform-client/blob/develop/app/common/directives/language-switch.html#L8

Here is a thread about a similar solution: https://stackoverflow.com/questions/35137025/dropdown-select-options-translation-in-angular-js-for-multilingual-site

The strings for languages are found here: https://github.com/ushahidi/platform-client/blob/develop/app/common/locales/en.json#L1657

*For internal use only*
Aha! Link: https://ushahiditeam.aha.io/features/PROD-457

**Comment by rowasc** [comment] 2019-06-08 23:11
@Angamanga having the "hardcoded" language names in a lang or simple JS file (instead of allowing translation of language names) would ensure they always the same regardless of which is your current language...which might be the simplest approach here. 

Tagging you in case you have other ideas that are better ? I think this might be a good "entry level " ticket for OSS community if we go for a simple approach

**Comment by Angamanga** [comment] 2019-06-11 08:19
@rowasc Yes, its sounds like a good idea! I'll update it as a first-time-issue :)

**Comment by Jenniline** [comment] 2020-01-03 22:04
Hi, @rowasc  and @Angamanga I will like to work on this issue. 
Please, can it be assigned to me? 

I have tried to reproduce the issue on my deployment so as to view it. However, I don't find it perhaps the version of Ushahidi I use is not that which had the issue. I don't see the drop-down menu displaying the list of languages as shown below. 
![cropped deployment](https://user-images.githubusercontent.com/39647995/71751752-e752b100-2e7c-11ea-93b9-5dae896f646f.jpg)

A description of the issue is needed in order for one to work on it. 

Thanks 
Jenniline

**Comment by rowasc** [comment] 2020-01-06 21:35
@Angamanga I think you were doing some work on this no ? 
@Jenniline I'll let Anna update this as needed. To make it work for multiple languages you'll need a transifex account, you can create it and we can add you to it. Thanks

**Comment by Jenniline** [comment] 2020-02-05 22:11
Hi @rowasc I have successfully created a transifex account my user name is Jenniline_Ebai. 
Please add me to the organisation transifex page so that I can work on the task. I am ready to solve this issue. 
I will like to be assigned this issue.
Thanks

**Comment by Angamanga** [comment] 2020-02-07 13:48
@Jenniline Try adding your transifex-credentials to your .env-file in the platform-client to download the languages,  you can read more about it here: https://docs.ushahidi.com/platform-developer-documentation/development-and-code/setup_alternatives/setting-up-the-platform-client#advanced-other-configuration-variables.

**Comment by Jenniline** [comment] 2020-03-04 12:44
Hi @Angamanga and @rowasc I have added the transifex details to the .env-file in my platform-client
In order for me to download the languages, I ran the _gulp dist_ command and they downloaded successfully.
I am still unable to reproduce the behaviour of this issue so that I can know the location where the issue comes from. 
Also, can I have a bit of direction on how to proceed on solving this?

**Comment by Angamanga** [comment] 2020-03-07 09:45
@Jenniline Try moving the locales-folder with the languages to the app-folder itself, and re-run gulp, then you should see the languages in the dropdown.

As the next step, try figuring out how the list in the dropdown is created. Where does the languages come from now? When you have figured this out, you can try to find a way to map languages to a list with the language-names translated to the target-languages. 
Hint! the code for the language-switcher lives here:
1. Template: https://github.com/ushahidi/platform-client/blob/develop/app/common/directives/language-switch.html
2. Directive: https://github.com/ushahidi/platform-client/blob/develop/app/common/directives/language-switch.directive.js

**Comment by Shreets** [comment] 2020-10-08 08:23
Hey @Angamanga , i an Outreachy applicant. I would like to work on this issue. Could you please assign it to me

**Comment by siggrid** [comment] 2020-10-08 08:41
Hi @Angamanga ! I am an Outreachy applicant. Would like to work on this issue.

**Comment by A-DML** [comment] 2020-10-08 09:06
Hi @Angamanga i will like to work on this for my outreachy contribution

**Comment by Angamanga** [comment] 2020-10-08 12:11
Thank you @Shreets @siggrid! Please go ahead 🎉 !
@A-DML I have assigned you to this one: https://github.com/ushahidi/platform/issues/3957

@siggrid You only need to care about the en.json file, the other ones gets updated by our translators :)

**Comment by siggrid** [comment] 2020-10-09 11:13
Hi @Angamanga
Created PR. https://github.com/ushahidi/platform-client/pull/1556
List of languages for the dropdown comes from `languages.json` file in `common/locales` folder. I added a `nativeName` field with corresponding value for each language in this file. Languages are shown in their native names regardless of selected language. Users won’t get lost even if they accidentally chose any other language.
Looks like this now.

<img width="302" alt="Screenshot 2020-10-09 at 14 02 58" src="https://user-images.githubusercontent.com/52042098/95576025-6a222100-0a38-11eb-9852-f3b7b38c2d46.png">

**Comment by Angamanga** [comment] 2020-10-09 11:55
@siggrid Thank you! I will review shortly!

**Comment by Shreets** [comment] 2020-10-11 10:37
Hey @Angamanga . I am just done with setup and looks like @siggrid  has already done a great deal of a job . 
Could you please assign me a new issue in this case?
Thanks :) !

**Comment by Angamanga** [comment] 2020-10-12 08:31
@Shreets Please check here if you find something you are interested in working on: https://github.com/ushahidi/platform/issues?q=is%3Aopen+is%3Aissue+label%3A%22Community+Task%22

**Closed** 2020-11-16 08:50 UTC
Labels: Codebase: Client, Hacktoberfest, Outreachy, Theme: Translations
