### ISSUE TITLE
Categories dissapear

### ISSUE THREAD

**Issue by natmanning** [ushahidi/platform#1569] opened 2017-02-02 17:57 UTC
### Expected behaviour

Categories don't disappear. 
### Actual behaviour

the categories to disappear and then only reappear when I attempt to reenter a category with the same slug

### Steps to reproduce the behaviour/error
Create some categories, and then jump between pages and they disappear.

**Comment by rjmackay** [comment] 2017-02-12 23:00
@natmanning is this on an ushahidi.io deployment? or open source?

**Comment by aoduor** [comment] 2017-02-13 05:11
I've experienced this on Ushahidi.io as well

**Comment by jshorland** [comment] 2017-02-17 09:21
This keeps popping up, but I'm never able to replicate it. I'd like to get to the bottom of this urgently.

**Comment by natmanning** [comment] 2017-02-17 20:48
So i haven't been able to replicate this either. But the user was working on:
https://mappingmediafreedomus.ushahidi.io/views/map

They said it's totally random for them too. They are working and things are moving along, and then, pop categories are gone, and so they go to and different page (within Ushahidi), then press backwards, and now categories are back.

But i can't figure out what is triggering it either!

**Comment by Angamanga** [comment] 2017-02-22 18:58
I cannot manage to reproduce it either. But it may be fixed by this pr: https://github.com/ushahidi/platform-client/pull/465/commits/575e00aeeb71eb1a28a170b5266f7e4864f4b100

**Comment by jshorland** [comment] 2017-03-07 06:16
I Can't get it to happen in qa.ushahididev.com, @Angamanga. It's hard for me to say whether this passes QA or not since i couldn't actually replicate the issue anywhere. @natmanning have you seen this issue happen to you again?

**Comment by Angamanga** [comment] 2017-03-07 08:16
I think it is fixed on staging now, that is why we cannot reproduce it there, but it is not deployed and that is why it is still appearing on some deployments. I actually remember being able to reproduce it on staging when starting working with this issue: https://github.com/ushahidi/platform/issues/1505 which sounds like the same.

**Comment by Angamanga** [comment] 2017-03-09 14:16
@jshorland Same as #1505. You can test this here: qa.ushahididev.com

**Comment by jshorland** [comment] 2017-04-12 00:48
Passes QA as far as I can tell. Let's get this deployed (if it hasn't been already!)

**Closed** 2017-04-20 13:52 UTC
Labels: Bug, P1 - Immediate
