### ISSUE TITLE
Feedback on successful actions

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#792] opened 2015-10-22 12:37 UTC
At the moment, when you click save, or post something - the user doesn't get any feedback or a prompt to confirm that "You've successfully saved/posted" or something. I just saved my settings and if it weren't for my keen eye on the slight page reload, i wouldn't be clear of my save action was successful or not - we should add these in.

**Comment by jshorland** [comment] 2015-10-22 14:27
Duplicate of #746 . Adding this note to that post and closing

**Closed by jshorland** 2015-10-22 14:27 UTC
Labels: Enhancement, Feature request
