### ISSUE TITLE
CSV export from the Settings tab exports a full data set despite selecting particular fields to export 

### ISSUE THREAD

**Issue by Alengai** [ushahidi/platform#3080] opened 2018-06-14 08:09 UTC
## Overview
Export should correctly take account of fields/surveys selected only when exporting data

## Requirements
- Only selected fields and surveys should appear in exported data

## Acceptance criteria
- Go to the Settings->Data Export view
- Select a survey and a subset of fields to export
- [x] Ensure that only the selected survey(s) and field(s) are present in the exported CSV

#Acceptance criteria 2
- [x] Go to the Settings->Data Export view
- [x] Select a subset of fields for 1 survey (only 1 survey)
- [x] Select "select all" for that survey
- [x]  Ensure that all the fields for that survey are present in the exported CSV

#Acceptance criteria 3
- [x] Go to the Settings->Data Export view
- [x] Select a all fields for 1 survey (only 1 survey)
- [x] Unselect 1 or 2 fields for that survey
- [x]  Ensure that all (and only) the fields selected for that survey are present in the exported CSV

**Describe the bug**
The export function form the settings tab in the deployment downloads a full data set despite selecting particular fields to export 

**To Reproduce**
1. Go to ‘dreamsic.ushahidi.io'
2. Click on ’settings tab, then to the export data tab and select fields to export. Select Siaya County Government - Council Health Management Team Database, click select all and click on the export selected fields
4. See error - it will download a full dataset for all surveys in this deployment. this will take about 25 minutes 

**Expected behavior**
The exported dataset is supposed to only include the Siaya County Government - Council Health Management Team Database.
This process is supposed to take no more than three minutes 

**Screenshots**
<img width="707" alt="screen shot 2018-06-14 at 11 02 30" src="https://user-images.githubusercontent.com/28722642/41399433-02e0d52a-6fc3-11e8-887a-90896ad5a706.png">

**URL / Environment where this happened**
https://dreamsic.ushahidi.io

**Additional context**
I tried to export the data using the select and filter option and this worked well. It exported the data I had sorted and filtered in two minutes

**Comment by jrtricafort** [comment] 2018-06-14 17:17
Tested and was able to repro this using the steps above.

@willdoran @rowasc I'm adding this as P2 since there is technically a workaround available and thus it won't block our upcoming training event on Monday. However, it is difficult to educate all 13 partner orgs on this workaround in the meantime, so we should address this next week at the beginning of Cycle 6 . Does that sound reasonable?

**Comment by jrtricafort** [comment] 2018-06-18 19:00
@jrtricafort and @rowasc to sync on this during Spec week.

**Comment by rowasc** [comment] 2018-06-21 21:28
@jrtricafort do you want to setup a call for this?

**Comment by jrtricafort** [comment] 2018-06-21 21:56
@rowasc No need. I think it's pretty well scoped, so let's not have it be a blocker for spec. It is P2, so let's make sure to get to the P1 issues and bugs first.

**Comment by rowasc** [comment] 2018-06-21 23:46
@jrtricafort In that case, and seeing we have >100 issues, I'd probably move it to cycle 7. 
My question about the call was because we agreed to sync on it, since I don't really understand the bug here. The export tab does not have filters.

**Comment by Alengai** [comment] 2018-06-22 02:43
Hi Romina,

I realize I may have used a technical term in the wrong context as I was
reporting this issue. This could have been due to the fact that there are
two ways in which the platform allows you to export data i.e through the
sort and filter option (we are currently applying this workaround) or
through the settings option where the platform allows you to select the
fields from the survey you want information from.

You are right, the export tab does not have filters, it actually has
"fields" which are supposed to be "selected" to be exported. I hope this
explanation has brought more clarity to the issue.

If you have any more questions, we can schedule a call and I will be able
to walk you through it.

Thanks.

Irene

**Comment by willdoran** [comment] 2018-06-22 13:15
@rowasc @jrtricafort I think we should fix this issue as it may be a blocker for partners? I think there is enough information to investigate it and determine how difficult it is to fix

**Comment by jrtricafort** [comment] 2018-06-22 17:21
@willdoran @rowasc @Alengai Good catch. That was my mistake. I was confusing Filters (in datamode) with Field Selection (in export). Since the bug is in Export->Field Selection, the original "workaround" I mentioned is actually not a workaround.

Upgrading to P1 due to lack of workaround and the fact we hit it in production with partners.

**Comment by willdoran** [comment] 2018-06-26 20:47
@rowasc Can you review?

**Comment by rowasc** [comment] 2018-06-27 14:58
@willdoran I think the acceptance criteria is OK, but I'd add two more  to ensure the client sends the correct fields in all scenarios and the server works as expected. 
#Acceptance criteria 2
- [ ] Go to the Settings->Data Export view
- [ ] Select a subset of fields for 1 survey (only 1 survey)
- [ ] Select "select all" for that survey
- [ ]  Ensure that all the fields for that survey are present in the exported CSV

#Acceptance criteria 3
- [ ] Go to the Settings->Data Export view
- [ ] Select a all fields for 1 survey (only 1 survey)
- [ ] Unselect 1 or 2 fields for that survey
- [ ]  Ensure that all (and only) the fields selected for that survey are present in the exported CSV

**Comment by jrtricafort** [comment] 2018-07-02 15:03
@rowasc @willdoran It looks like we are already moving forward on fixing this as a P1, which is great. @irenewa recently provided an update that we expect several partners to be doing CSV exports between now and July 10th because of a project deadline. As such, I think we should bump this up to a P0, and that it should take priority over HDX work.

Sorry again for my earlier misunderstanding of this issue! Thanks everyone for getting us back on the same page!

**Comment by jrtricafort** [comment] 2018-07-02 17:01
Assigning to @rowasc to assign.

**Comment by willdoran** [comment] 2018-07-03 14:45
@rowasc nope, go for it

**Comment by rowasc** [comment] 2018-07-03 16:18
Cool, picking it up today then . :D

**Comment by jrtricafort** [comment] 2018-07-03 17:25
Thanks yall!!

**Comment by rowasc** [comment] 2018-07-04 14:59
@willdoran I think this is a 3. 
The issue itself is pretty simple (should filter by survey, not just limit the fields included in the export) but might require some wrangling around filters vs fields code because the code was "designed" with fields not acting as filters. Anyway, I see how this issue can be super confusing after trying it again today, sorry it took me a while to "get it"

**Comment by rowasc** [comment] 2018-07-04 19:16
@Eve-wanderi can you prioritize testing this issue and doing a run of testing for CSV in general in http://csvexportsforever.v3-qa.ush.zone/? I would send to send the hotfix when I wake up since it's a P0 , but I want to make sure you re-test it in http://csvexportsforever.v3-qa.ush.zone/ before we do it since it's a CSV issue.

**Comment by rowasc** [comment] 2018-07-06 13:02
@Eve-wanderi great job! thanks for finding all those issues, this is really good.   I'll be opening child tickets for these issues since they are not related to the fix. I think we might have some code in master behind lumen fixes, did not expect all those UI issues to come up. 


---------


>Inconsistency on the amount of time it takes to do an export. Noticed at times exports take 3mins and at times exports take upto 7mins.

The export works in a queue, so it won't be consistent. Won't fix.

>Users do not get Notified on Successful or Unsuccessful export user has to go to export history to see the status of their export this happens regardless if user stays on the page or leaves the page.

Ah, that's pretty weird since we didn't change it. I'll check but it's going to go to another issue. 

>When an export status shows pending or failed then i refresh the page the status switches to complete.
oh ok. Adding a separate issue for that. Pretty strange, I suspect it might be an old bug in the client that didn't get attention. 

>Noticed that there are extra columns on the export sheet even if the survey does not have these fields should this be the case. I have highlighted the extra fields with Asterics**
Ah. Yes :( Those columns are fixed for all CSVs because they are "shared" amongst all posts. But, I think we should consider it as something to change, maybe with a "general" selection. 
I'll start a ticket and tag a few people who usually work with CSVs, +Design :D

**Comment by rowasc** [comment] 2018-07-06 13:23
>Noticed that if many users try to export there are delays took 20 mins to download the file and when it did the files were empty.
Eve, I (purely by chance) saw this update now. This is a major problem if it's happening, can you please open a ticket with details to reproduce?

**Comment by rowasc** [comment] 2018-07-09 15:36
@jrtricafort I think we can release this as-is, yes. The bugs are unrelated.

**Comment by rowasc** [comment] 2018-07-09 17:32
@Eve-wanderi This is now deployed in production (ushahidi.io deployments)

**Closed** 2018-07-09 17:33 UTC
Labels: Bug, P0 - Urgent

**Comment by Eve-wanderi** [comment] 2018-07-11 16:23
@rowasc  Great let me do some post-deployment checks for this.
