### ISSUE TITLE
Integrate Accessibility

### ISSUE THREAD

**Issue by crcommons** [ushahidi/platform#2578] opened 2018-03-08 20:14 UTC
- Accessibility adjusted html-templates should come from the PL
- We potentially need to do some focus-managing in the client, find out where that is needed, which components etc

**Comment by crcommons** [comment] 2018-03-08 20:15
@Angamanga Tagging you here solely because you had originally signed up for this one and want to keep a record. You don't need to reassign yourself.

**Comment by rowasc** [comment] 2019-06-11 15:57
Closing as duplicate of https://github.com/ushahidi/platform/issues/2506

**Closed by rowasc** 2019-06-11 15:57 UTC
Labels: Epic
