### ISSUE TITLE
Deleting location in filter modal gives new longitude and latitude coordinates

### ISSUE THREAD

**Issue by gitudaniel** [ushahidi/platform#1995] opened 2017-08-08 18:10 UTC
### Expected behaviour
On deleting a location in the location field the field should remain empty
### Actual behaviour
Deleting the location produces new longitude and latitude coordinates
### Steps to reproduce the behaviour/error
On uchaquzi.or.ke click on filters and enter a location like Nairobi, Kenya
Press and hold the backspace button to clear the field.
You should see new latitude and longitude coordinates appear.

**Comment by jshorland** [comment] 2018-02-27 23:55
I can't reproduce this. Closing.

**Closed by jshorland** 2018-02-27 23:55 UTC
Labels: Bug, P2 - Normal, Theme: Geo, Uchaguzi 2017
