### ISSUE TITLE
Categories and Survey pages do not reflect changes made on save.

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#2344] opened 2017-12-05 12:01 UTC
### Expected behaviour
The surveys and categories pages should reflect changes when a user changes settings on those pages. 
### Actual behaviour
A user creates a new survey or category, presses save, is navigated back to the survey/category page, and it looks like they never made the changes. User must refresh page before changes take effect.
### Steps to reproduce the behaviour/error
Navigate to surveys in settings, create a survey, press save. 
Navigate to categories, create a category, press save.

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by jshorland** [comment] 2018-03-01 00:33
Categories is fixed, and this is a duplicate of surveys. Closing.

**Closed by jshorland** 2018-03-01 00:33 UTC
Labels: Bug, Needs Triage
