### ISSUE TITLE
Organism --> bulk actions

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#2766] opened 2018-04-16 20:59 UTC
Aha! Link: https://ushahiditeam.aha.io/features/PROD-367

**Comment by justinscherer** [comment] 2018-04-24 22:26
click + shift + click to multi-select in a list

tap and hold to activate multi-select in mobile

can only do bulk actions in data mode.

**Comment by sethburtonhall** [comment] 2018-06-15 20:23
Can you link to a mock example of bulk actions? I have styles for bulk selected list below but I need more info.

![image](https://user-images.githubusercontent.com/1033332/41487826-32680a3e-70b8-11e8-9d46-7c4d97de241b.png)

**Comment by rowasc** [comment] 2018-06-19 16:44
Going back to design since it still needs testing.

**Comment by justinscherer** [comment] 2018-06-26 16:48
@rowasc should be able to lift the designs from here:

https://app.zenhub.com/workspace/o/ushahidi/platform/issues/3060

**Comment by rowasc** [comment] 2018-06-27 15:11
Yep excellent @justinscherer .
  @sethburtonhall @Angamanga feel free to move to  "QA by design" if this is completed in the PL already , or close if there's another ticket that's being reviewed for it

**Comment by sethburtonhall** [comment] 2018-06-28 13:05
Moving to "Ready for Front-End". @rowasc when do you need this by?

Mocks:
https://xd.adobe.com/view/df0747b4-7640-404f-6d3c-6af8f7a9db9c-a936/

https://xd.adobe.com/spec/2110a313-afd9-4e50-6966-bf094ebfd5a8-5721/

**Comment by Erioldoesdesign** [comment] 2018-09-05 11:49
I tried finding where to test this on the UI refresh PL. I tried:

http://preview.ushahidi.com/platform-pattern-library/ui-refresh/assets/html/3_organisms/#pl-pattern-list
http://preview.ushahidi.com/platform-pattern-library/ui-refresh/assets/html/5_layouts/settings-people.html

But neither had a shift+click interaction. Am I missing something @sethburtonhall

**Closed** 2020-10-13 16:14 UTC
Labels: Theme: JS Framework rewrite, UX/UI debt, wont-fix-until-redesign
