### ISSUE TITLE
2Chaguzi Prep 

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2120] opened 2017-10-10 23:55 UTC
This is just a ticket to coordinate major parts of the 2chaguzi launch. 
- [ ] Saved search works
- [ ] Split pane works
    - [ ] Edit mode works
    - [ ] Split pane view works
- [ ] Filtering works - Checklist (https://github.com/ushahidi/platform/issues/2091)
- [ ] Bulk action works
     - PL work is mostly done.
     - Client work is being started between @crcommons and @rowasc
- [ ] Load more works
     - Waiting to merge. 
- [ ] Post locking is done and require one more review, it’s a little complex to test as it requires redis
- [ ] Task Visibility is done and requires a review
- [ ] Changelog: finish off final pieces in the API
- [ ] Cover deployment needs for uchaguzi sandbox

**Comment by Angamanga** [comment] 2017-10-11 08:16
**Detailed testing checklist**
*General:*
 - [ ] name of “timeline” changes to “data” everywhere the name “timeline” occurs

*Split pane, general*
 - [ ] view split into two independently scrolling panes - left with list of post cards, right with post detail view when a post card is clicked. When no post card is selected, right pane is blank.
- [ ] Number of posts based on applied filters displayed above post card list on left pane (4 of 1,203 posts)
 - [ ] Checkboxes are removed from post cards and replaced with a right facing chevron after the report titles
 - [ ] entire postcard is tappable/clickable for selection except the “…” icon in the top right corner, which brings up the same action sheet as current
 when selecting a postcard, the postcard nudges to the right —> 0.2s with a quadratic easing curve
 - [ ] when a postcard is selected, the post detail appears on the right side pane
 share button works with current functionality (no change) (so it should share the post detail that’s selected. If no posts are selected, it shares the data view with filtered reports, or exports them if export selected)
 - [ ] bulk actions works as normal. If bulk actions is selected, checkboxes appear on post cards.

*Split-pane, editing*
- [ ] when postcard is selected, edit button appears next to “share” button if user is logged in with permission to edit posts
- [ ] logged in user with permission to edit posts can navigate directly to edit view through the … button on the postcard (current functionality)
- [ ] When user clicks edit, post detail should enter “edit mode” on the right pane
- [ ] When user clicks cancel without making any changes, taken back to post detail page, no changes saved
- [ ] When user clicks cancel when changes are made, a warning where the user can choose between continue without saving or save appears
- [ ] When user navigates away from editmode when changes are made, a warning where the user can choose between continue without saving or save appears
- [ ] When user clicks save without making any changes, “you haven’t made any changes error banner” appears. User kept in edit mode

**Comment by Angamanga** [comment] 2017-10-11 12:29
**My findings so far:**
1. timeline is still used in the dropdown when choosing the default view-mode for saved-searches and collection
2. split pane is not individually scrolling, but works as expected except for that
3. navigating between collections and normal view is a bit confusing, probably not connected to this but when i click on 'data' or 'map' i thought i would go back to 'normal' view, not collection/map or collection/data, what is the intended behaviour?
4. nb of posts above post-list is displayed but needs styling
5. Checkboxes are removed from post cards and replaced with a right facing chevron after the report titles <-- don't even know what this means?
6. ... is clickable but the whole card is clicked as well
7. No x is displayed on leave-edit-mode-warning 
8. 'no changes made'-banner is ugly
9. Save-button saves but does not select the next applicable report
10. Values are not displayed when editing an unstructured post although existing in database
11. I dont see a saved-search-filtering option
12. Only published and under review statuses are checked, not 'archived'
13. When I am in map-mode and select a post, i cannot navigate away from the detailed view
14. When, in data-view, I choose to clear all filters, the whole list of posts does not reappear

**Comment by rowasc** [comment] 2017-10-11 13:12
11. I dont see a saved-search-filtering option

 Fixed here: https://github.com/ushahidi/platform-client/pull/798 . Ready for review/merge

**Comment by rowasc** [comment] 2017-10-11 15:09
> When, in data-view, I choose to clear all filters, the whole list of posts does not reappear
Working on this one in the next ~30minutes. It's a dumb bug where I forgot to change reactiveFilters to true I think

**Comment by rowasc** [comment] 2017-10-11 15:22
> When I select "Show only" for a survey in mode-context-bar, the filter-badge displays the wrong survey ( in one case the survey that is not visible, and in another the survey-id for the selected survey, so very random)

Checking now

**Comment by Angamanga** [comment] 2017-10-11 20:42
Looking into next:
> ... is clickable but the whole card is clicked as well
> When I select a checkbox in the postcard, that post is clicked too (need to turn off click-event in those cases)

**Comment by willdoran** [comment] 2017-10-12 04:07
Issues I have found so far:

- [ ] Elipsis Menu doesn’t appear below shorter detail views
<img width="558" alt="screen shot 2017-10-12 at 00 05 05" src="https://user-images.githubusercontent.com/2694405/31478820-09c397d6-aee1-11e7-9b60-2a75f37c92d6.png">
- [ ] No loading animation when Posts refreshing on data view
- [ ] Can’t add new post in data view
- [ ] Filters dropdown appear behind loading bar animation
<img width="1058" alt="filters dropdown appears behind loading animation" src="https://user-images.githubusercontent.com/2694405/31478836-27efde90-aee1-11e7-934b-9fbeb3e233c7.png">
- [ ] Timeline appearing in Savedsearch and Collection dialog(I've added a PR for this)
<img width="410" alt="timeline appearing in savedsearch dialog" src="https://user-images.githubusercontent.com/2694405/31478857-3c0d7072-aee1-11e7-9fa0-3a23b33a4025.png">
- [ ] Filter dialog doesn’t close when clicking outside dropdown
- [ ] Checkbox should be separately clickable to the Postcard itself, at the moment, when I click on the check box after clicking bulk actions the whole card is selected.

**Comment by aoduor** [comment] 2017-10-12 09:09
Making a note of issues i find here.. Sorry I posted a few outside.. linking them here..

#2135 
#2134

**Comment by aoduor** [comment] 2017-10-12 09:13
I can't find where to edit saved searches in the data view. @justinscherer had included it here in this comment

https://github.com/ushahidi/platform/issues/1896#issuecomment-332763152

**Comment by Angamanga** [comment] 2017-10-12 12:29
- [ ] When navigating away from a card after cicking 'continue' or 'save' on the warning-modal, it doesnt continue to where the user was going, I stay on the post-details-view
- [ ] In data-view, filters doesnt update after choosing a saved search in saved search-modal (it does in map-view)
- [ ] Styling on bulk-actions-modal is off on smaller screens
- [ ] post does not go into edit-mode after unlocking it in data-view (locally)
- [ ] i got no message about that the post is unlocked in the other window (locally)
- [ ] what is the difference between task is for only internal use and show this task to everyone? Should they be possible to turn on at the same time? (possible now)
- [ ] I dont see any of the fields when trying to add a post with internal tasks as not logged in, just title and description

**Comment by aoduor** [comment] 2017-10-12 12:44
I know this is more of a design question that we can tackle later, buuut, i find it extremely useful to have this summary of the saved search i'm looking at, even in the data view.

![screen shot 2017-10-12 at 15 43 44](https://user-images.githubusercontent.com/721918/31496478-29ddc112-af64-11e7-9aa4-f31fe3a1e79b.png)


I know we can't represent it in the UI per se, but maybe we could include it in the tab name so that users are aware of what exactly they're looking at. Makes sense?

**Comment by crcommons** [comment] 2017-10-12 14:02
-[ ] Padding has been added to all notifications such that it's messing up other styles

**Comment by aoduor** [comment] 2017-10-12 14:29
- [ ] I can't find the message thread section when responding to a user from SMS.

**Comment by rowasc** [comment] 2017-10-12 16:37
- [ ] Save button in edit mode is not working . @rowasc looking into this

**Comment by jshorland** [comment] 2017-10-12 16:41
@angamanga re: what is the difference between task is for only internal use
and show this task to everyone? Should they be possible to turn on at the
same time? (possible now) @jshorland <https://github.com/jshorland> @aoduor
<https://github.com/aoduor>
-- task is for internal use means the task itself isn't shown to non-logged
in visitors or members, only to logged in users with permission to "manage
posts" or "edit posts".
-- show this task to everyone means that the content of the task is
published on the post and visible to everyone once that task is marked as
complete.

They can be turned on at the same time. Does that make sense?

**Comment by rowasc** [comment] 2017-10-12 19:10
- [ ]  In data-view, filters doesnt update after choosing a saved search in saved search-modal (it does in map-view) . (note from Romina: @jshorland I'm not able to reproduce this. :( @Angamanga ). Any other steps besides selecting a saved search and going to data view?

**Comment by rowasc** [comment] 2017-10-12 19:30
- [ ] Contextual menu "..." appears under the post card list. #2143

**Comment by rowasc** [comment] 2017-10-12 19:38
- [ ] Show the unsaved changes modal when page url changes or user tries to reload with an unsaved post https://github.com/ushahidi/platform/issues/2144

**Comment by rowasc** [comment] 2017-10-12 19:42
- [ ] Show the unsaved changes modal when page url changes or user tries to reload with an unsaved post https://github.com/ushahidi/platform/issues/2144

**Comment by aoduor** [comment] 2017-10-13 08:48
- [ ] Fix help text overlapping input on location field #2146

**Comment by rowasc** [comment] 2017-10-13 13:29
- [ ] user list layout is broken https://github.com/ushahidi/platform/issues/2148

**Closed** 2017-11-01 03:47 UTC
Labels: 2chaguzi
