### ISSUE TITLE
user0 doesn't have access error (forbidden) when logged in and trying to create surveys

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#2306] opened 2017-11-28 07:18 UTC
### Expected behaviour
Any users should be able to create separate and unique entities within the platform simultaneously if they are logged in at the same time. 

### Actual behaviour
The PEOs were doing a training and tried to have the trainees log in to platform and create surveys simultaneously. They began receiving forbidden errors about "user0". They all logged out and tried to do it only on one user account and still threw errors (see screenshot)

### Steps to reproduce the behaviour/error
![unnamed](https://user-images.githubusercontent.com/3224856/33306855-52405e2c-d425-11e7-9579-b5b16ad737a1.png)

@dukedanny what was the URL of the deployment, and did I miss any context?

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by willdoran** [comment] 2017-11-28 07:27
The forbidden(access denied) is caused by having insufficient rights to view the data on a page. 

The most common cause is, “My session has expired and I’ve been logged out BUT I haven’t clicked anything recently so I have no way to know that” I would suspect that because building a Survey is probably a bit involved and long as a process it takes longer than the session lasts. What probably happens is, after working through the Survey with client they click save and basically all their work is gone :confused:

Based on that, I don’t think there is a quick fix. I think the fix is:
- We should warn a user before their session times out and offer the chance to keep the session live
- We should save draft data locally at least so that we can recover the state

I think that would be the minimum requirements, there are a couple of ways we can solve it with our current code. I don’t know if that alone will solve the problem, it’s super irritating to get thrown off a detail page when you are logged out BUT I would imagine it’s a major problem to loose a Post or Survey. If you think about how complex we’re told setting stuff up is, if the thing is logging out before they get too grips with it that’s just going to compound the issue of on boarding.

We should write a spec for this and then determine the time cost for it with full requirements.

**Comment by aoduor** [comment] 2018-02-12 13:51
Flagging this as a PAINFUL, PAINFUL issue still happening on DREAMS deployments.

![screenshot](https://media2.giphy.com/media/l3q2wnlw48fuf1l3a/source.gif)

When sessions expire for partners, and they log back in, they should be redirected to the page they were initially working on.

As it stands now when they log back in, as much as a new session is started for them, they remain on the "Access denied/forbidden access" page, which confuses them and makes them think they're not allowed to perform any functions. 

HAAAAALLLLLP!

**Comment by jshorland** [comment] 2018-02-12 19:06
aiyaiyai. Sorry guys. tagging this to be fixed in the next dev cycle.

**Comment by aoduor** [comment] 2018-04-18 17:38
@caharding this happens ALL. THE. TIME. not just for dreams deployments.

**Comment by caharding** [comment] 2018-04-18 18:07
I spoke with Daniel. Right now people know a workaround: reload the tab or open incognito. We will fix in next cycle or two, but have to prioritize COMRADES right now.

**Comment by rowasc** [comment] 2018-09-28 14:03
We have a 24hs expiration now for tokens. This should help at least with the annoying 15 minute window we used to have to work on surveys.

**Comment by rowasc** [comment] 2020-01-02 20:38
Referenced in the two related issues. Closing in favor of those.

**Closed by rowasc** 2020-01-02 20:38 UTC
Labels: Bug, DREAMS, P2 - Normal, Tech Debt, Theme: Users and roles
