### ISSUE TITLE
Twitter widget displayed on posts from email

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#3438] opened 2018-12-07 02:43 UTC
<img width="418" alt="screenshot 2018-12-07 15 43 14" src="https://user-images.githubusercontent.com/7965/49624610-f88d7c00-fa36-11e8-9b15-daea250fac44.png">

## Reproduce the bug
- Configure data-sources for email and Twitter in Settings -> Datasources
- Get data from both email and twitter
- Check the data-view. Posts from email are formatted as tweets.

## Implementation notes
- Fix in https://github.com/ushahidi/platform-client repo
- Hint :bulb: The code handling twitter-display in posts can be found here: https://github.com/ushahidi/platform-client/blob/develop/app/main/posts/views/card.html
- When you are done, 🔀 Start a Pull Request. There are two ways how you can start a pull request:

   1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

   2. You can also[ edit files directly in your browser](https://egghead.io/courses/how-to-contribute-to-an-open-source-project-on-github) and open a pull request from there.

- 🏁 When done Ask in comments for a review :)

## Want to work on this issue?🙋 
Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

**Comment by rjmackay** [comment] 2018-12-07 03:07
It looks like we might just be checking data_source_message_id but not checking the message type at all.

**Comment by rowasc** [comment] 2019-06-24 20:16
I can't reproduce this in my deployment , closing. reopen if we know how to repro
<img width="1010" alt="Screen Shot 2019-06-24 at 17 15 43" src="https://user-images.githubusercontent.com/2434401/60049025-c7f3f380-96a3-11e9-840b-5c369fa2b21d.png">

**Comment by Angamanga** [comment] 2019-09-03 12:02
@rowasc Reopening since this happens on https://bristolstreetharassmentproject.ushahidi.io/posts/96.

**Comment by rowasc** [comment] 2019-09-03 12:08
oh. Interesting. Could you post the response from messages and posts
endpoint?
(I don't have permissions to see the post)

**Comment by Angamanga** [comment] 2019-09-03 12:30
@tuxpiper @rowasc I think I found it. We only check post.data_source_message_id, not post.source. If that id happens to be accessed to a tweet, it will display that tweet even if its not 😬  https://github.com/ushahidi/platform-client/blob/develop/app/main/posts/views/card.html#L17

**Comment by tuxpiper** [comment] 2019-09-03 12:33
oh yea, the absence of checks there is really suspicious! I guess this happening or not just depends on the ids involved, and whether they hit an active tweet or not.

**Comment by rowasc** [comment] 2019-09-03 12:37
Ah, yea. 😬 
@Angamanga do you want to send a fix or otherwise I can do It

**Comment by Angamanga** [comment] 2019-09-03 12:42
Fixing it now...

**Comment by Angamanga** [comment] 2019-09-03 12:46
@rowasc @tuxpiper fix in pr: https://github.com/ushahidi/platform-client/pull/1328 if one of you can double-check?

**Closed** 2020-03-04 14:42 UTC
Labels: Codebase: Client, Community Task, Size: S, Stage: In progress, Theme: Data Providers, Theme: Twitter
