### ISSUE TITLE
UX issue: Apply button stays disabled when filtering map views.

### ISSUE THREAD

**Issue by Obadha2** [ushahidi/platform#3946] opened 2020-04-21 11:28 UTC
# Approved solution
Apply button should always be manually clicked to apply filters, rather than always automatically applying the values in the map view and requiring a click in the data view. This is to ensure we are providing consistent behaviors across different screens, since several users were confused about this. 

### Checklist 
- [ ] Filters should not be automatically applied in map view
- [ ] Filters should not be automatically applied in data view

------------------------------------------------------

Original bug report here

**Describe the bug**
Apply button on the filters under the map views remains disabled and users cannot click on it to perform a filter operation. The filtering however still happens.

**Where was the bug observed**
Map views - https://test-deployment.steve-buscemi.ush.zone/views/data

**To Reproduce**
1. Go to a deployment.
2. Under the map views, Click on 'Sort & Filter' to perform a filter operation.
3. Note that as you select your filtering criteria, the filtering happens in the background behind the filter overlay.
4. Also note that the 'Apply' button stays disabled and cannot be clicked on to seemingly perform the filtering.

**Expected behavior**
In the presence of the 'Apply' button, users expect to click on the button to perform the filtering.

**Is there a workaround? What is it.**
The filtering actually works. Only it might go unnoticed for the user as they wait for the 'Apply' button to look enabled.

**Screenshots**

**URL / Environment where this happened**
- Happens in both prod and test environments, in map views.
https://test-deployment.steve-buscemi.ush.zone/views/data

**Desktop Hardware Details (please complete the following information):**
 - OS: iOS
 - Browser Chrome
 - Version 81.0.4044.92 (Official Build) (64-bit)

Aha! Link: https://ushahiditeam.aha.io/features/PROD-45

**Comment by noone0212** [comment] 2020-04-21 20:49
I am able to reproduce this issue. While going through code base, I found **disableApplyButton** function should return true if filtering is to done in map view, else it should return false, i.e. when in data view. I want to ask if I should remove this function and make apply button always enabled, because in data view it is always enabled. Please help. Thank You!

**Comment by rowasc** [comment] 2020-04-22 10:26
> Apply button on the filters under the map views remains disabled and users cannot click on it to perform a filter operation. The filtering however still happens.
This sadly is by design. 
It's always been confusing at best that we do that. I can't remember the rationale for this to be a thing to be honest.

**Comment by rowasc** [comment] 2020-04-22 10:27
Basically the idea was that in the map the filters apply automatically (why? ) and in the data view they don't (again, no idea why, will try to find the old documents for this so we can bring some clarity into it)

**Comment by rowasc** [comment] 2020-04-22 10:27
cc @Angamanga tagging because maybe you have awesome memory about this

**Comment by Angamanga** [comment] 2020-04-22 10:32
@rowasc @Obadha2 Yes I also remember it was by design. I think it was simply "ok so the filters apply themselves in map-view, lets disable the button" more than anything else... I think we can re-enable it (at least to close the modal?) Its confusing...

**Comment by rowasc** [comment] 2020-04-22 10:32
Ah ok so recalling a bit that
- for triage (data view) it was important for it to be manual apply, because otherwise the general feeling was that it'd be confusing and because the common usecase was that you'd group filters a lot more in data view. 
- For map, still no idea. 

Ideally, it'd be nice if filter behavior were the same in both views IMO. If you have to apply it manually then great apply it everywhere, if not, don't apply it manually. Because there's not enough distinction to make it intuitive that one behaves in a way and another in a different way.

**Comment by rowasc** [comment] 2020-04-22 10:33
@CeciliaHinga you chat with people using the tool all day, have you found a lot of confusion around this or generally is fine with users?

**Comment by rowasc** [comment] 2020-04-24 16:15
@aoduor also, not that you should feel obligated to answer, but I know you had *thoughts* about filters and I want to make sure I plug you into this convo just in case :)

**Comment by CeciliaHinga** [comment] 2020-05-06 07:39
@rowasc no this is not fine with our users, it was actually reported by one. It confuses them because they do not realize the filtering is happening on the background since the sort and filter page does not disappear, you have to click outside for it to disappear, the only time the page disappears is when you filter data by date range. Plus they can see the apply button at the bottom.

**Comment by rowasc** [comment] 2020-05-06 18:41
Thank you @CeciliaHinga . We had a suspicion given previous feedback but it's always good to get confirmation !
Yea I agree this is odd. 
Question for you: if you could change it, would you make it so that you *always* have to hit apply for filters to be applied? or would you make it so that you *never* need to apply them? I think that's the balance that's hard to hit between map and data view, which are serving different audiences almost

**Comment by CeciliaHinga** [comment] 2020-05-11 08:04
@rowasc I am not sure. How will it work without the apply button? With the apply button, I can select different features to filter by at a go, then hit _Apply_. Without the apply button, will the page disappear immediately I sort or filter by something, then go back and select something else to filter by and so forth?

**Comment by CeciliaHinga** [comment] 2020-05-11 08:12
But to answer your @rowasc I honestly cannot see it without the apply button, it makes sense to me, it is less confusing. Besides if we have it on data view, it's best we have it on map view as well.

**Comment by rowasc** [comment] 2020-05-11 14:46
@CeciliaHinga without the apply button, it'd work the same way it does in the map, where filters are applied as you select them

**Comment by Angamanga** [comment] 2020-08-03 09:35
@rowasc @CeciliaHinga Fixing this introduces some new questions...

Assume I make it required to always hit "Apply" to add the filters...
1. As it is now, the dropdown closes automatically when clicking outside of the dropdown. What should happen then if I haven't clicked Apply yet? Reverting back to the previous set filters? Restore to default? So far I think reverting back to previous set filters is the best option. Another option is to only close the dropdown when clicking Apply or Restore defaults,  but it is a bit confusing I think. There is also the arrow where you can open and close the dropdown which I think should have the same behaviour as clicking outside of the dropdown.

2. When selecting filters, they appear in the active search-box as small buttons + the option to save the search even if I haven't yet clicked "Apply". If save the search, but don't click "Apply", should saving a saved search automatically apply the filters to the view anyway if I click outside of the dropdown? I think applying the filters but change the save button to "Apply filters and save search"

3. The numbers in the little circle, should they update immediately when selecting a filter or only after clicking "Apply"?

**Comment by rowasc** [comment] 2020-08-03 19:38
Thanks Anna. This increases the scope a bit. I was running with the assumption that we'd make the same behavior apply in map view first, and then make other improvements right after, is that correct or am I way off? 

Answering here in any case
1 .   I'd definitely leave it as-is until we make a decision, and launch as a separate improvement. The bigger improvement would be to make _some_ visual change that hints "you have not applied this filters"  when you close the dropdown. Could we do a small "Do you want to apply the new filters"  pop-up  that shows up when someone closes the filter screen without applying them? Or would that be super confusing? Another alternative would be to "hint" that filters aren't applying in a less forceful way than a popup, maybe in the bar itself. After thinking about it, I don't super love the "resetting to previous filters" idea on dropdown closing because it's too easy to do it by mistake, so it'd be frustrating, but I also realize the current solution can be confusing, so it's a hard balance. @CeciliaHinga would love your thoughts on this too. 
2.  I Agree with  this, go ahead (may need to think about the words a bit if it turns out that's too long) : > I think applying the filters but change the save button to "Apply filters and save search"
3. Let's only update them on apply.  I think that provides better feedback that the filters are not really active until you apply them actually.

**Comment by Angamanga** [comment] 2020-08-04 12:36
@rowasc I agree on fixing the apply-button first since my questions is actually already existing problems in data-view... Adding new issues once this is landed... PR for button-fix is here: https://github.com/ushahidi/platform-client/pull/1531

**Comment by rowasc** [comment] 2020-08-04 19:17
@Obadha2 ready in steve.

**Comment by rowasc** [comment] 2020-08-11 13:29
@Obadha2 was this tested? LMK how it went

**Comment by Obadha2** [comment] 2020-08-11 14:29
This passes QA. :+1:

**Comment by rowasc** [comment] 2020-08-12 02:02
hrm. I just checked this on steve because I was doing release prep... it seems that while the apply button is in fact active, it doesn't really affect the fact that filters are applied "on the go" as always
@Angamanga

**Comment by Angamanga** [comment] 2020-08-12 16:18
Starting to fix to the filters/mode-context-bar here: https://github.com/ushahidi/platform-client/pull/1532

**Comment by Angamanga** [comment] 2020-09-29 08:03
@rowasc This is fixed now I? Closing

**Closed by Angamanga** 2020-09-29 08:04 UTC
Labels: Stage: In Testing, Theme: Filters & Search
