### ISSUE TITLE
FCDO Project: User Unable to submit posts on https://kenyacovid19.ushahidi.io/views/map

### ISSUE THREAD

**Issue by Nthiga** [ushahidi/platform#4186] opened 2020-12-21 04:05 UTC
**Describe the bug**
Two of the trained community mappers submitted posts are either blocked or disappear after submission (The posts cannot be verified by an administrator) 

**Where was the bug observed**
Include Deployment and page URL (e.g. "https://test.ushahidi.io/views/map")
https://kenyacovid19.ushahidi.io/views/map

**To Reproduce**
2. Log in as '...' (Please note if certain user permissions, like Admin or Manage Data, are required to reproduce this bug. Also include if there is a support@ or admin@ account for this deployment. If not, contact the platform slack channel with further instructions.)
3. Click on '....'
4. Scroll down to '....'
5. See error

Go to https://kenyacovid19.ushahidi.io/views/map
Log In 
Search for posts highlighted as missing posts by a Mapper Named Richard: See diagrams below 

Beyond that i need help on deciding whether this is a bug or something specific to the user phone specs  

**Expected behavior**
User should be able to submit post 

**Is there a workaround? What is it.**
Need help on deciding whether this a bug or something specific to a user phone specs etc 

**Screenshots**
Sample Posts that have disappeared 
![image](https://user-images.githubusercontent.com/26707984/102738127-4180a680-435a-11eb-9a01-e64bcad0fdf4.png)

![image](https://user-images.githubusercontent.com/26707984/102738181-6aa13700-435a-11eb-81af-0a4840b9ecd5.png)

Error message on Users Phone: 

![image](https://user-images.githubusercontent.com/26707984/102738139-4fcec280-435a-11eb-8fac-aea124c4f64c.png)

**URL / Environment where this happened**
https://kenyacovid19.ushahidi.io/views/map

**If the bug is datasource related (e.g. SMS or Targeted SMS), please specify the configuration details (e.g. Frontline + Clickatell, etc):**

N/A
**Desktop Hardware Details (please complete the following information):**

**Smartphone Hardware Details (please complete the following information):**

**Additional context**

**Comment by rowasc** [comment] 2021-01-01 17:44
Hey folks, we're having trouble reproducing this issue. We just sent a report from the mobile app  (check out the "post called "Test from Ushahidi", it's still in review since we were just trying to check submission of posts ), and we don't see anything missing right now, but I'm sure we are missing some information or doing something differently. 
Thanks
Romina

**Comment by tuxpiper** [comment] 2021-06-04 11:07
Possibly the same as #4220 (addressed by https://github.com/ushahidi/platform-mobile-app/pull/6) and a bit mitigated by  https://github.com/ushahidi/platform-mobile-app/pull/8 .

Marking as something we could probably close.

**Comment by Angamanga** [comment] 2021-06-30 11:46
@tuxpiper This is the fix we did for mobile, right? In that case its done :)

**Comment by tuxpiper** [comment] 2021-07-07 07:55
Yes I think it is. Closing on that assumption.

**Closed by tuxpiper** 2021-07-07 07:55 UTC
Labels: Cleanup/Done?
