### ISSUE TITLE
Twitter post on preview list won't open to show more details.

### ISSUE THREAD

**Issue by Obadha2** [ushahidi/platform#4034] opened 2020-08-11 10:19 UTC
**Describe the bug**
Posts that come in from twitter, when clicked on, don't open the post on details panel to show more details.

**Where was the bug observed**
Data page on test deployment in steve-buscemi.

**To Reproduce**
1. Go to the deployment.
2. Navigate to data page.
3. Find a post from twitter. Easiest way is by filtering posts.
4. Click on a post to open it to open more details about the post.
5. While clicking on the tweet opens the tweet on twitter site, clicking on the post to open it up for more details does not work.

**Expected behavior**
Clicking on a post on the preview list(left-side) should open the post to show more details on the details panel.

**Is there a workaround?**
None.

**URL / Environment where this happened**
https://test-deployment.steve-buscemi.ush.zone/views/data

**Desktop Hardware Details (please complete the following information):**
 - OS: Ubuntu 20.04.1 LTS
 - Browser: Chrome 
 - Version 84.0.4147.105 (Official Build) (64-bit)

**Additional Info**
The link on the tweets that come in on prod is broken.
It should be of the format:
`https://twitter.com/159450635/status/some-id`
but it is instead as:
`https://twitter.com/statuses/some-id`
Not sure this should reside on this issue since it's happening on a different server, but since it's a twitter thing I put them together here.

**Logs**
```Transition Rejection($id: 8 type: 6, message: The transition errored, detail: Error: Error: Request failed with status code 500) Error: Error: Request failed with status code 500 at i.<anonymous> (posts.js:36) at tslib.es6.js:99  at Object.throw (tslib.es6.js:80) at r (tslib.es6.js:71)```

Aha! Link: https://ushahiditeam.aha.io/features/PROD-58

**Comment by treasurechristain** [comment] 2020-10-11 03:26
Hi can I work on this issue if it's still open for my outreachy contribution.
I'm Amadikwa Joy N

**Comment by Naimaoye** [comment] 2020-10-11 11:30
Hi, my name is Naimat Oyewale. Can I work on this issue for my outreachy contribution?

**Comment by rowasc** [comment] 2020-10-13 20:00
@treasurechristain please go ahead!
Assigned.

**Comment by treasurechristain** [comment] 2020-10-14 01:34
ok @rowasc , Thank you very much. I'm currently on it.

**Comment by treasurechristain** [comment] 2020-10-14 01:45
@rowasc I'm Unable to locate any twitter tweets on this link https://test-deployment.steve-buscemi.ush.zone/views/data

![twitter1](https://user-images.githubusercontent.com/20610726/95933762-3c860080-0dc7-11eb-8ad6-0ca1cab23fae.PNG)

![twitter2](https://user-images.githubusercontent.com/20610726/95933773-43147800-0dc7-11eb-9b42-6e2e65661947.PNG)

Please confirm from your end if it's an issue from my side

**Comment by Obadha2** [comment] 2020-10-14 09:09
Hi @treasurechristain 

You are unable to see any posts because posts are not published. Posts need to have a status of published for them to be visible to non-logged in users.

I have changed the status of a few posts to published, you should be able to see them now without having to log in.

**Comment by bimbolabuari** [comment] 2020-11-05 07:42
@Obadha2 @rowasc, can I work on this if it's available?

**Comment by Angamanga** [comment] 2021-03-29 14:24
@Obadha2 Can you check if this is still happening? I cannot reproduce it?

**Comment by Angamanga** [comment] 2021-05-25 08:23
Ok, closing

**Closed by Angamanga** 2021-05-25 08:23 UTC
Labels: Done?
