### ISSUE TITLE
Payment Plan for surveyor is mis-aligned.

### ISSUE THREAD

**Issue by Eve-wanderi** [ushahidi/platform#3201] opened 2018-08-10 08:44 UTC
**Describe the bug**
Surveyor payment plan details is misaligned. This only happens if user selects mapper and it fails then they select Surveyor.

**Where was the bug observed**
https://lumen.passage.ush.zone

**To Reproduce**
1. Go to 'https://lumen.passage.ush.zone'
2. Create a deployment
3. Click on 'Mapper' ensure you get a failed status
4. Click on Surveyor
5. See error

**Expected behavior**
Surveyor payment plan text should be alligned.

**Is there a workaround? What is it.**
Yes to refresh the page.

**Screenshots**
<img width="1343" alt="screen shot 2018-08-09 at 11 23 27 am" src="https://user-images.githubusercontent.com/36038029/43948136-a8bfbe92-9c92-11e8-9ea5-c0e42dbca20a.png">

**URL / Environment where this happened**
[https://passage.ush.zone/create]

**If the bug is datasource related (e.g. SMS or Targeted SMS), please specify the configuration details (e.g. Frontline + Clickatell, etc):**

**Desktop Hardware Details (please complete the following information):**

**Smartphone Hardware Details (please complete the following information):**

**Additional context**

**Comment by rowasc** [comment] 2018-08-10 15:01
@Eve-wanderi please post the steps to reproduce the failing subscription issue and link the issue here, since that issue has a higher priority and this ticket cannot be reproduced without it.

**Comment by rowasc** [comment] 2018-10-04 03:49
Closing, surveyor no longer exists for new users

**Closed by rowasc** 2018-10-04 03:49 UTC
Labels: Bug
