### ISSUE TITLE
Issues with Custom form field set up

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#863] opened 2016-01-05 08:55 UTC
(via Intercom)

Hi, I'm having some issues with the 'checkbox' step for Ushahidi. Whenever I input a field name and the corresponding field options/checkboxes, all I receive is both the field name itself and one checkbox, containing only the field name, while the software completely ignores all of the field options. How do I solve this? Thank you!

![screenshot_1](http://i.imgur.com/zYmU2DR.jpg)

![screenshot_2](http://i.imgur.com/BDSPhA6.jpg)

**Comment by willdoran** [comment] 2016-01-06 19:52
I'll take a look at this now.

**Comment by willdoran** [comment] 2016-01-06 20:15
This is working for me in the current master branch. It may be that the release is out of date. I'll ask @rjmackay when he's on!

**Comment by lupa18** [comment] 2016-01-12 15:12
Here the same with checkbox field. I'm using deploy: https://pruebalup.ushahidi.io and with own installation based on github/master (yesterday).

The checkbox configuration:

![seleccion_034](https://cloud.githubusercontent.com/assets/463429/12267168/8d56ef02-b925-11e5-893d-271123d143ac.jpg)

The result:

![seleccion_033](https://cloud.githubusercontent.com/assets/463429/12267199/b29e57e6-b925-11e5-9a4d-8d70089030be.jpg)

**Comment by willdoran** [comment] 2016-01-25 17:29
Ah ha, ok, I have it reproduced now. I'll fix it immediately!

**Comment by willdoran** [comment] 2016-01-25 19:49
This is actually a deeper bug, @rjmackay: there is an issue with checkboxes, there seems to be no distinction between a checkbox and a radio button. Both allow only 1 value to be entered.

There is a display issue with checkboxes as well that seems to have been in the code for a while.

**Comment by willdoran** [comment] 2016-03-09 19:42
This was fixed in the past release.

**Closed** 2016-03-09 19:42 UTC
Labels: 2 - Up Next, Bug, P2 - Normal, Theme: Post editing
