### ISSUE TITLE
User Display Name doesn't update

### ISSUE THREAD

**Issue by sophshep** [ushahidi/platform#761] opened 2015-10-12 14:28 UTC
When changing my display name in the account settings, I hit save. The save button confirms that the change has been made, but the user drop down area still has my old name (in this screenshot, "test"). Even when I navigate to other pages, this still says "test"

![image](https://cloud.githubusercontent.com/assets/527589/10430162/458695c4-70c3-11e5-98fc-c5e1cdeb7754.png)

**Comment by sophshep** [comment] 2015-10-12 14:42
It does update when I log out and then in again.

**Comment by rjmackay** [comment] 2015-10-20 21:24
Dupe of #721

**Closed by rjmackay** 2015-10-20 21:24 UTC
Labels: Needs Triage
