### ISSUE TITLE
Keyword doesn't clear after navigating away from saved search

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#1200] opened 2016-06-13 16:45 UTC
### Expected behavior

After I go back to home from a saved search, I expect the search term in the search box to go away
- Filters should reset when switching home/saved search/collections views
- Filters should not reset when switch between map and list views
### Actual behavior

When I go home after a saved search, the search term stays in the search box, and doesn't clear in the mode context bar. 
### Steps to reproduce the behaviour/error

Go to a saved search, go back to home

Logged in Safari / OSx

**Comment by rjmackay** [comment] 2016-06-20 22:24
Confirmed.

**Comment by rjmackay** [comment] 2016-08-01 07:32
@jshorland this got stuck with a partial solutions - should we move it into the backlog for future sprints?

**Comment by rjmackay** [comment] 2016-10-27 20:41
Filter needs some refactor:
- Post filters needs to know about state: are we viewing a collection, search or all posts?
- Post filters should handle reset when state changes
- Collections and saved search controllers need less custom logic
- Ideally we would also push current filters onto the URL too (bonus)

**Comment by willdoran** [comment] 2016-10-27 20:47
That all sounds good, the current filters on URL will also allow users to share specific filtered searches

**Comment by willdoran** [comment] 2017-01-17 14:03
@rjmackay What is happening with this? I'd like to move it out code review should it go back to backlog?

**Comment by rjmackay** [comment] 2017-02-01 19:35
Not sure where this got to. Might actually be done.

**Comment by Angamanga** [comment] 2017-02-02 08:40
@willdoran @rjmackay This seems to be partly done here: https://github.com/ushahidi/platform-client/pull/413 but never got merged. There is still a problem when clicking on 'map' or 'timeline' in the nav-menu, /map or /list gets added to the current url and the saved search stays visible. I will not mess with this today, would rather hear your thoughts on how to move on. You seemed to have a discussion about it that ended somehow in the middle?

**Comment by jshorland** [comment] 2017-03-07 07:05
Is this ready to be QA'd @Angamanga and if so, which URL should I QA on?

**Comment by rjmackay** [comment] 2017-03-20 03:38
It looks like I never finished that PR. I'd guess it needs rebasing and cleaning up then we can test

**Comment by jshorland** [comment] 2017-04-12 00:54
@rjmackay @Angamanga should I throw back into dev backlog?

**Comment by Angamanga** [comment] 2017-04-28 08:09
@jshorland This can be tested on: http://qa.track-filter-state.ushahidilab.com/views/map

**Closed** 2017-08-24 04:26 UTC
Labels: Bug, P0 - Unbreak now!, Theme: Search
