### ISSUE TITLE
Fix contrast problems

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#1881] opened 2017-07-14 20:26 UTC
All colours should pass a 4.5:1 colour contrast ratio score.

Currently they do not. people with vision loss, low vision, colour blindness, and other special needs will not be able to use our website until this is fixed...

Aha! Link: https://ushahiditeam.aha.io/features/PROD-571

**Comment by vanessa-ariel** [comment] 2020-10-09 23:53
I am interested on working in this issue, @Angamanga.

**Comment by rowasc** [comment] 2020-10-10 21:50
Hey @vanessa-ariel this ticket is not marked for community contributions yet (it needs a lot of design work to make it into core)
https://github.com/ushahidi/platform/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Hacktoberfest+%22+label%3A%22Community+Task%22 please check this list and find an unclaimed issue. 
Thanks!

**Comment by Angamanga** [comment] 2021-05-27 08:40
Duplicate of https://github.com/ushahidi/platform/issues/4180. Closing.

**Closed by Angamanga** 2021-05-27 08:40 UTC
Labels: Feature request, Needs: design, Theme: accessibility, UX/UI debt
