### ISSUE TITLE
[Outreachy Task Submission]  No drop down arrow on the "choose survey" dialogue box

### ISSUE THREAD

**Issue by Ebere330** [ushahidi/platform#4819] opened 2024-03-12 23:18 UTC
Description: Drop down arrow should be added to the dialogue box on the "add new post button" when it is clicked.

FIX:
Add New Post Button: This takes the user to a dialogue box with the heading "Choose survey". The dialogue box has a button with the text "Basic post" but does not have a drop-down arrow for further selection of other surveys.

![choose survey](https://github.com/ushahidi/platform/assets/70584450/089462f0-d0c9-4795-9188-979cdadd7e02)

 I believe that this issue being solved can make the Ushahidi platform more accessible. @Angamanga

**Comment by MugoBrian** [comment] 2024-03-21 15:09
Hello @Ebere330 . This is not an issue, it's a feature. The Choose Survey modal displays a list of surveys, but since you only have one survey in your database, it displays only that one.

PS: The "Basic Post" is a survey and not a button and it redirects you to another page. Tip: Try clicking on it and see.

See the screenshot below
![Screenshot from 2024-03-21 18-06-21](https://github.com/ushahidi/platform/assets/49617104/728903a4-66fb-4337-9893-0c08ba30fed4)

**Comment by Angamanga** [comment] 2024-03-25 20:52
@Ebere330 @MugoBrian is correct, there should not be a dropdown, it is a link to go to the survey :) . Closing as works as designed.

**Closed by Angamanga** 2024-03-25 20:52 UTC
