### ISSUE TITLE
Manage Settings permission not working as documented (does not have access to categories)

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#3169] opened 2018-07-18 12:47 UTC
Expected behavior (from the docs)

`Manage Settings: Allows for managing`
General Settings
Map Settings
Data Sources
Surveys
Categories

Current behavior: 
A user with Manage Settings has access to 
- General
- Surveys
- Data sources 
- Map Settings
and does not have access for:
- Categories

**Comment by nocodes** [comment] 2020-03-06 16:57
Hi @Angamanga , can I work on this issue as a contribution to my outreachy program?

**Comment by Angamanga** [comment] 2020-03-06 19:22
@nocodes Absolutely! Please go ahead :) and reach out if you need any guidance!

**Comment by webong** [comment] 2020-03-09 23:06
@Angamanga @nocodes  can it be confirmed that this issue still persists ... I tried reproducing this bug issue on local development with a test user that has the manage settings permission ... I was able to manage categories (create & delete).

**Comment by Angamanga** [comment] 2020-03-10 08:15
@webong @nocodes I cannot reproduce it either. Thank you for noticing this! @nocodes Have you managed to reproduce it? If not, I will close this issue!

**Closed** 2020-03-27 12:08 UTC
Labels: Bug, Codebase: API, Community Task, GSoC, Outreachy, Theme: Users and roles
