### ISSUE TITLE
Embed map

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1387] opened 2016-09-15 18:30 UTC
Frame for any embed needs to show the deployment name and Ushahidi brand
- Popups/Postcards (link away)
- Add button (link away)
- Replace toolbar with button to see survey filters.[Key]

**Comment by jshorland** [comment] 2016-09-15 18:55
@brandonrosage quick question: are there already designs for embedding just the map?

**Comment by brandonrosage** [comment] 2016-09-15 18:58
@jshorland No, but I'll stage those in the PL...now.

**Comment by brandonrosage** [comment] 2016-09-15 20:30
I've staged this layout in a feature-specific branch, for now, called `f-embeds`. You can sample the "Embed: Map" layout here: http://preview.ushahidi.com/platform-pattern-library/f-embeds/assets/html/5_layouts/embed-map.html

Sample:
![embed](https://cloud.githubusercontent.com/assets/1136279/18566367/3a0dadf8-7b59-11e6-8131-d8637ac2eec4.png)

It will eventually be merged into a sprint-specific branch, once the issue is pegged for a release cycle.

**Comment by brandonrosage** [comment] 2016-09-15 20:47
On a related note, I've also staged embed layouts for:
* [Post: Add](http://preview.ushahidi.com/platform-pattern-library/f-embeds/assets/html/5_layouts/embed-post-add.html)
* [Post detail](http://preview.ushahidi.com/platform-pattern-library/f-embeds/assets/html/5_layouts/embed-post-detail.html)

**Comment by brandonrosage** [comment] 2016-09-15 20:50
@jshorland & @caharding: Does the aforementioned "Map" embed layout meet [the requirements we set out to meet](https://docs.google.com/a/ushahidi.com/document/d/1E-2-6hhVWZIMQrDaQSEqlnJ1MmNTWo9BoDhq-ZFeFVw/edit?usp=sharing) in Montreal for a Version 1?

**Comment by jshorland** [comment] 2016-09-19 18:43
Two questions/comments:

1. I don't see any prominent display of the Ushahidi brand. Is that intentional?
2. "Add to" styling seems off. Is this because of a specific-to-mobile design decision with embed? And hypothetically when I click on a survey to add to, does it take me to the full form on the ushahidi.io site?

**Comment by brandonrosage** [comment] 2016-09-19 21:41
> I don't see any prominent display of the Ushahidi brand. Is that intentional?

I don't care too much for Ushahidi. So I thought we'd just keep it out. (I've added it to today's round of revisions).

> "Add to" styling seems off.

The "Add to" treatment you're seeing is not unique to (or even a requirement for) the embed-specific patterns here. It's just a carryover from other work I've done to prepare a new "mainsheet" pattern for things like chips. 

For "Add to," specifically, the "mainsheet" solves a previously-logged issue with the current convention, where a deployment with more than 10 surveys really gets a messy experience when clicking the "+" button.

You're comment did highlight for me an inconsistency in how we use color in the design framework. So I tried unifying the mainsheet's color scheme with that of the "listing toolbar" and "date picker," which fly out from the same location(s):

![mainsheet](https://cloud.githubusercontent.com/assets/1136279/18649894/a39d344c-7e87-11e6-9e73-b8b7b4e31f61.png)

Better?

> when I click on a survey to add to, does it take me to the full form on the ushahidi.io site?

We had determined all links open in a new, full browser window/tab. So I think the same would occur here. Ideally, however, we'd provide as much of the UX inside the embed as possible, including selecting "Add to" and completing a survey.

**Comment by jshorland** [comment] 2016-09-19 22:02
Hahahahahahah

**Comment by caharding** [comment] 2016-09-20 00:29
Looks good to me

**Comment by rjmackay** [comment] 2016-09-20 03:19
I think this is pretty good. Only complaint is that it gets a bit cluttered at smaller sizes with an icon in every corner of the map..

**Comment by rjmackay** [comment] 2016-09-26 08:57
Suggested tech approach:
- [ ] Add a new entry point `embed.html`
   - Initially this should support a single route /map
   - Initially this loads the entire JS bundle - we can optimizing in next iteration
   - This shouldn't load the mode bar
- [ ] Force all links to load in a new borwser window
- [ ] Modified map view w/ Ushahidi branding, and 'filter by' button in small views.

**Comment by rjmackay** [comment] 2016-09-26 08:58
Sized on the large side because I'm not 100% sure how adding an extra entry point will work, or if this should just be part of index.html .. but aim for quicker implementation first.

**Comment by willdoran** [comment] 2016-10-20 19:44
@jshorland The PL styles for this should now be available in develop

**Comment by jshorland** [comment] 2016-10-25 23:18
@brandonrosage @willdoran I don't see the share --> embed menu on the map. Is that not how I'm supposed to access embed?

**Comment by jshorland** [comment] 2016-10-27 14:21
@willdoran I'm still only seeing the "export" button on the map mode, instead of the "share" menu. Am I missing something?

**Comment by brandonrosage** [comment] 2016-10-27 14:40
I was confused by this, too. @willdoran informed me that it's currently only accessible to deployers in Settings > General. But the intention is for it to be accessible to anyone visiting the deployment via the "Share" button and modal, demonstrated in the PL's `develop` layouts.

Map, for example: http://preview.ushahidi.com/platform-pattern-library/develop/assets/html/5_layouts/map.html

![Share](https://cloud.githubusercontent.com/assets/1136279/19771676/57f34b16-9c29-11e6-8756-696a849e8cc8.png)

**Comment by willdoran** [comment] 2016-10-27 15:00
@brandonrosage @jshorland I don't remember "embed share" being part of the spec for this feature. I added embed example code to the settings>general view as a mechanism for admins.

We don't have a share functionality at the moment. Was adding "Share" meant to be part of this issue?

**Comment by brandonrosage** [comment] 2016-10-27 15:08
I think it's fair to call out that this wasn't explicitly part of the scope of this feature.

As backstory, much like "How to post" in the mode context, Mustang always assumed a "Share" button and modal. But in the rush to implement it, I assume it got reduced to just "Export." So I've also assumed that, as we rolled out support for those sharing options, we understood the mechanism for users to access them.

Ugh.

So it's your call, @jshorland and @willdoran, as to what we release this go around. Let me know if the intended UX here is unclear.

**Comment by willdoran** [comment] 2016-10-27 15:26
If we move share to its own issue, does this count as passing qa/closeable?

**Comment by jshorland** [comment] 2016-10-27 15:38
Passes QA. Moving to waiting to deploy.

**Comment by jshorland** [comment] 2016-10-27 15:45
Yes, if we move share to it’s own issue, this is closable.

**Comment by willdoran** [comment] 2016-10-27 15:50
Done!

**Closed** 2016-11-02 23:13 UTC
Labels: Theme: Embed
