### ISSUE TITLE
CSV file downloaded doesn't give me all fields I expect on export

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#2838] opened 2018-04-25 12:02 UTC
### Expected behaviour
When exporting data from platform ( be it using the share button) or via the admin panel, I expect to be able to see my survey fields available in the CSV file. 

### Actual behaviour
These are the only headers available for me on the CSV file, even after selecting fields from two of my surveys.

`Post ID | Created (UTC) | Updated (UTC) | Post Date (UTC) | Contact ID | Contact | Sets`

See options i selected here:
![screen shot 2018-04-25 at 15 01 13](https://user-images.githubusercontent.com/721918/39244521-876cba1c-4899-11e8-9c4e-4af8d71986c6.png)

### Steps to reproduce the behaviour/error
* Log into a deployment
* Attempt to download posts from data mode/map view by clicking on share, and export filtered data
* Go to settings, select export, and select fields in your survey to download

#### Where does this issue happen?
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [x] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain): 

#### It is ready for development when
- [ ] Has a description that includes purpose of this particular feature/improvement (how it will help the user and for which use cases)
- [ ] Can be delivered within a sprint (make sure issues are small pieces of work, not huge epics)
- [ ] Has all designs and UI assets available
- [ ] Has all (probable) dependencies identified
- [ ] Is estimated by the team
- [ ] Has acceptance criteria defined (do we want to do this before we send to dev? might help us identify dependencies/holes earlier?)

## Test Script
- [ ] Download everything
- [ ] All field should be there
- [ ] Run some downloads that have only certain fields selected
- [ ] confirm correct fields are included in csv

**Comment by kinstelli** [comment] 2018-04-25 16:15
@rowasc - Was this in scope for CSV?

**Comment by rowasc** [comment] 2018-04-25 17:04
Certainly. This looks like a bug with the include fields feature to me. @kinstelli

**Comment by crcommons** [comment] 2018-04-26 17:28
Closing in favor of #2400

**Comment by rowasc** [comment] 2018-04-26 19:40
Checking on this now

**Comment by rowasc** [comment] 2018-04-26 19:41
As an update: 
- When I generate and request an export, I'm not missing fields. I have the opposite problem,  basically, I have them all (which is fine except when I select specific fields. )

**Comment by rowasc** [comment] 2018-04-26 20:05
so I had the opposite problem, which I fixed. Trying to figure out how both issues can happen 😕

**Comment by rowasc** [comment] 2018-04-26 20:32
@aoduor was this happening in a deployment without data  ?

**Comment by rowasc** [comment] 2018-04-26 20:37
@StaicyG ccing you in case you can help me figure out how to reproduce this

**Comment by aoduor** [comment] 2018-04-26 21:17
I have at least 160 posts on this deployment. I can give you log in creds. see dm ;)

**Comment by rowasc** [comment] 2018-04-27 23:01
Found root cause for @aoduor  issue and sent to code review. It was a faulty sql query where I joined form_stages and ids by wrong key.

---- separate note @crcommons 
I'm not convinced that DafneCalvo's issue is the same, I think we should open a separate one to investigate properly because it's not the field that is missing, it's the data for the field.

**Comment by joseantonioprado** [comment] 2018-04-28 22:55
Thank you very much for filing this, @aoduor . I really am not able to understand this github tool yet.
I wanted to add that Ive tried every alternative for downloading csv, in two very different deployments, choosing all, some, few, fields, and the result was always the same: only the 7 columns mentioned by Angela (the number of rows/responses is ok tho).
Thank you all for any help.
PS. I dont know if this idea is stupid but I wonder if maybe we could go back to the "old" csv export mechanism while this new format is debbugged. I have read complaints that resulting csv files werent very tidy, but you could always clean them with excel, etc. as all the data was there. 
Thx again!

**Comment by rowasc** [comment] 2018-05-01 02:13
@StaicyG can you test this? 
Thanks!

**Comment by crcommons** [comment] 2018-05-01 15:42
Passed QA

**Comment by crcommons** [comment] 2018-05-01 20:46
@rowasc Passed QA

**Closed** 2018-05-02 01:29 UTC
Labels: Bug, P0 - Unbreak now!

**Comment by crcommons** [comment] 2018-05-02 03:35
@dafneCalvo can you attempt a CSV download again? If it doesn't work, please let us know.

**Comment by joseantonioprado** [comment] 2018-05-02 14:25
Hi. Just to complement, I did too try a CSV download and while we now have all columns back (good!!), the two default fields (or columns) of any survey, originally named "title" and "description", come blank (which by the way is impossible because these 2 fields are mandatory).
So, we are better than last week but still unable to recover our "kidnapped" data.
Thanks!

**Comment by willdoran** [comment] 2018-05-03 20:45
@dafneCalvo Could you confirm that you are still experiencing the issue where a column other than Title and Description is blank when it shouldn't be?

**Comment by DafneCalvo** [comment] 2018-05-04 09:40
@willdoran I still experiencing this issue. I have a column with the Tittle of the question, but I have no answers there (although is a mandatory field, so it should not be empty). I attach a screenshot. 

![imagen](https://user-images.githubusercontent.com/36405677/39621676-e20ca660-4f8f-11e8-946b-896e1a585753.png)

**Comment by willdoran** [comment] 2018-05-04 13:26
@DafneCalvo Just to check, did you rename the column Title to above column your missing? I'm trying to tack down the issue and this info would be very helpful. Thank you!

**Comment by DafneCalvo** [comment] 2018-05-04 14:43
@willdoran Yes, the Tittle of the post correspond to the empty column which have a new name: "¿Cuál es el nombre de la organización". I did, I renamed this field.

**Comment by willdoran** [comment] 2018-05-04 20:01
@DafneCalvo  Fix should be there ten mins from now roughly, would you mind retesting and letting me know?

**Comment by joseantonioprado** [comment] 2018-05-05 00:33
Sorry for interfering and commenting over and over, but I wanted to report that the problem is now solved for me. I dont know if it is also the case for @DafneCalvo (espero que si :) but I can confirm that I tested this in two different deployments, with different surveys and different filters and everything is looking fine now. I wanted to inform it on time for the weekend, I hope you have a happy one! 
Thank you @willdoran , @crcommons , @rowasc , @aoduor for your amazing work. THANK YOU.
Greetings from Santa Cruz de la Sierra, Bolivia!

**Comment by DafneCalvo** [comment] 2018-05-06 10:27
@willdoran @rowasc @crcommons  Now it is working, thanks so much for your kindness and and patient!

@joseantonioprado saludos desde España! :)

**Comment by willdoran** [comment] 2018-05-07 12:47
@joseantonioprado Thanks so much for the feedback, and thank you so much for testing it! Hope all your stuff goes well. Let us know if there is anything else you find.

@DafneCalvo I'm very glad that it is working for you now, thank you for retesting and thank you for letting us know about the issue. Please do let us know if you find anything else! Best of luck with your project.
