### ISSUE TITLE
Android Mobile AppKeralaRescue Property Damage Assessment - in offline mode not able to view submission

### ISSUE THREAD

**Issue by laxman954** [ushahidi/platform#3239] opened 2018-08-24 20:47 UTC
Describe the bug

Android Mobile AppKeralaRescue Property Damage Assessment - Open the app in offline mode and Submit survey response once completed click "View Responses" there is no submission found in offline mode, once connected to internet only can able to view the offline submission also.

Where was the bug observed

Android Mobile AppKeralaRescue Property Damage Assessment

To Reproduce

Install Keralarescue mobile app in Android
Sign up using email ID
Login using email ID and password
Click submit 

**Make phone offline

Submit any survey response
Once done click the View Response, there is no submission

Expected behavior

Because in offline mode people submit the submission it will be available to view response to verify for them to give more comfortable to user. This data anyway we stored in local storage.

**Comment by bobinson** [comment] 2018-08-26 13:55
A related issue is sometimes in offline mode, clicking the submit button doesn't show any response.

**Comment by rowasc** [comment] 2018-10-19 20:41
@Eve-wanderi @dalezak  not urgent, I know you all have a lot to do right now,  but what's this about/what are we doing with this issue? 
Can we close it?

**Comment by rowasc** [comment] 2018-10-31 18:58
@Eve-wanderi @dalezak bumping. See question above.

**Comment by rowasc** [comment] 2019-06-12 01:59
Closing as duplicate of #3242

**Closed by rowasc** 2019-06-12 01:59 UTC
Labels: Bug, Mobile
