### ISSUE TITLE
importing csv feature on qa.ushahididev.com/

### ISSUE THREAD

**Issue by spiral99** [ushahidi/platform#1518] opened 2016-11-23 11:57 UTC
### Expected behaviour
the user should be able to select attributes from the csv columns.
### Actual behaviour
when importing csv files the csv columns are blank when on mozilla firefox. There are also duplicate survey fields.
### Steps to reproduce the behaviour/error
![2016-11-23_li](https://cloud.githubusercontent.com/assets/7393879/20560989/2a02930a-b18d-11e6-9679-5e2f629741ac.jpg)
![2016-11-23 1 _li](https://cloud.githubusercontent.com/assets/7393879/20561655/ae8d64e4-b190-11e6-85e1-4c1a4fc314a9.jpg)

**Comment by rjmackay** [comment] 2016-11-28 07:46
@spiral99 can you attach the CSV you were trying to upload?

**Comment by rjmackay** [comment] 2016-11-28 07:47
Also - does this issue exist on production? or only staging?

**Comment by spiral99** [comment] 2016-11-28 08:07
it's on production as well although initially it was working meaning a
recent change ha affected it.

**Comment by rjmackay** [comment] 2016-11-30 01:17
@spiral99 can you send me the CSV thats having issues? Are you sure this worked previous with *that csv*? It might be an issue with just that file

**Comment by rjmackay** [comment] 2016-11-30 01:43
I've pushed a fix for the duplicate title and description fields in the list. I can't reproduce the issue with missing CSV columns myself.

**Comment by spiral99** [comment] 2016-11-30 08:47
the issue is on Mozilla Firefox.

**Comment by jshorland** [comment] 2018-02-28 00:09
Can't replicate. Closing.

**Closed by jshorland** 2018-02-28 00:09 UTC
Labels: Bug
