### ISSUE TITLE
No data appearing for posts

### ISSUE THREAD

**Issue by FIU-Editor** [ushahidi/platform#988] opened 2016-03-18 17:50 UTC
Hi,

When creating a post, approximately the second half of all fields with data inputted did not appear to the public. 

![image](https://cloud.githubusercontent.com/assets/17600339/13887007/01e3433e-ed10-11e5-8ecd-9d0ea4b24ec3.png)

![image](https://cloud.githubusercontent.com/assets/17600339/13887081/4bed8098-ed10-11e5-8a6d-82b0dc4a97d8.png)

(Left/Underneath: Post Type. Right: Displayed Post)

As you can see, everything from "Challenge Date" downward is not appearing in the actual post. What could the cause of this?

Thank you.

**Comment by willdoran** [comment] 2016-03-18 17:53
Hi there @FIU-Editor, looking at this now!

**Comment by willdoran** [comment] 2016-03-18 17:59
Ok, so to get more information, are all the fields in a single step?

I notice that on the viewing of the post you have a second step:
"Add secondary sources..."

Does that step have separate fields? 

Would it be possible for me to get access to the deployment? I'm not clear why this issue would be occurring.

If you visit ushahidi.com, you can start an intercom conversation with us via the question mark bubble in the bottom right hand corner of the page.

**Comment by FIU-Editor** [comment] 2016-03-18 18:02
Nearly all our fields are in a single step, except for one, a short text box, in the second, "Add secondary sources..."

Here's the link to the deployment: bb.fiu.edu

**Comment by willdoran** [comment] 2016-03-18 18:02
Ok, looking now, thanks.

**Comment by willdoran** [comment] 2016-03-18 18:11
@FIU-Editor would it be possible for you to give me a login for the deployment?

**Comment by willdoran** [comment] 2016-03-18 18:12
@FIU-Editor I signed up by creating a user could you give that user admin access and I'll investigate further?

**Comment by FIU-Editor** [comment] 2016-03-18 18:19
Just did.

**Comment by willdoran** [comment] 2016-03-18 18:47
@FIU-Editor Thanks, ok the info is coming back from the DB with just the fields up to 'Challenge Date'. I'll try to recreate it locally and get back to you

**Comment by willdoran** [comment] 2016-03-18 18:48
@FIU-Editor Thanks, ok the info is coming back from the DB with just the fields up to 'Challenge Date'. I'll try to recreate it locally and get back to you

**Comment by willdoran** [comment] 2016-03-18 19:03
@FIU-Editor, I'm not seeing the issue locally but I am seeing an error on save. 

Can you give me the following info:
1. What version of Platform are you running?
2. What version of Platform Client are you running?
3. On the platform deployment in the dir application/logs/ can you share with me the contents of the log for today?

**Comment by jshorland** [comment] 2016-03-21 17:56
@willdoran this is the latest info wing ho gave me via email:

The version of platform is master c582e23
The version of platform Client is master 25151df 

we do not have log on March 21 but here's the log for 3/14, 3/16 and 3/18.  If you need more information, feel free to email me.
[14.txt](https://github.com/ushahidi/platform/files/182823/14.txt)
[16.txt](https://github.com/ushahidi/platform/files/182825/16.txt)
[18.txt](https://github.com/ushahidi/platform/files/182826/18.txt)

**Comment by willdoran** [comment] 2016-03-21 18:13
thanks @jshorland this helps hugely, I'll look into it now.

**Comment by willdoran** [comment] 2016-03-21 18:41
ok @jshorland @FIU-Editor 
I can reproduce the issue using the same commit numbers locally. This leads me to believe that it may be caused by DB version problem. The steps to test this would be:

1. Update both client and Platform to lastest versions of master
2. From the platform root dir run ./bin/phinx migrate -c application/phinx.php

This should run all database migrations to ensure they are up to date. The issue appears to be that the datetime field was formatted incorrectly when inserted into the DB. But I can't see this occurring.

If the problem persists after updating and running the migrations, then send me the log again and I will try to find more solutions.

**Comment by jshorland** [comment] 2016-03-25 12:26
Hi Will, This is the latest error Wing received when trying to test this:

[22.txt](https://github.com/ushahidi/platform/files/189487/22.txt)

**Comment by jshorland** [comment] 2016-04-09 14:46
Hey @willdoran -- any updates on this? Their deployment is dead until they get the calendar issue fixed. 

cc: @FIU-Editor

**Comment by willdoran** [comment] 2016-04-09 14:50
@FIU-Editor were you able to try my suggestions above for upgrading to the latest release and database version for platform? If you want we can discuss more directly via IM and I can walk you through the steps. Apologies for delay, I must have missed your update to the issue.

You can connect to us here:
https://gitter.im/ushahidi/Community
or here:
Hipchat Platform v3 room

**Comment by FIU-Editor** [comment] 2016-04-11 18:14
Hi, Will.

Yes, we have recently upgraded to the latest release and database versions
(as conveyed by your fix to delete steps!). Nonetheless, I have inquired
our team whether something was not updated, just to make sure.

The calendars are still not working, and all fields after a field with the
"Date" or "Date/Time" type still disappear in the post.

**Comment by willdoran** [comment] 2016-04-11 18:17
@FIU-Editor Ok, I will try again to reproduce the error locally.

**Comment by willdoran** [comment] 2016-04-11 20:14
@FIU-Editor let me know if it is possible for your team to use the Master branch for both platform and platform-client.

**Comment by FIU-Editor** [comment] 2016-04-19 17:05
We have been using the Master branch for both. How does the error look on your end?

**Comment by aoduor** [comment] 2016-04-22 08:55
Flagging this @willdoran @rjmackay @jasonmule, someone on intercom reached out about this.

**Comment by willdoran** [comment] 2016-06-20 14:51
Closing as issue resolved with user.

**Closed by willdoran** 2016-06-20 14:51 UTC
