### ISSUE TITLE
Unable to Post Responses if user is logged in

### ISSUE THREAD

**Issue by Eve-wanderi** [ushahidi/platform#3254] opened 2018-08-30 16:13 UTC
**Describe the bug**
If a user is logged IN i cannot post any responses i get an error "There was a problem posting your response".

**Where was the bug observed**
Mobile App (https://rominacsvsms.ushahidi.io)

**To Reproduce**
1. Go to 'https://rominacsvsms.ushahidi.io' mobile App.
2. Log in as 'Admin' (Please note if certain user permissions, like Admin or Manage Data, are required to reproduce this bug. Also include if there is a support@ or admin@ account for this deployment. If not, contact the platform slack channel with further instructions.)
3. Click on ' Submit Survey Response'
4. Scroll down to 'Basic Post.'
5. Fill in all details

**Expected behavior**
User should get a notification "Post submitted successfully"

**Is there a workaround? What is it.**
For android phones No.

**Screenshots**

![screenshot_20180830-182746_ushahidi](https://user-images.githubusercontent.com/36038029/44864427-4a7c7400-ac88-11e8-8401-27ff62aa0037.jpg)
![screenshot_20180830-185738_ushahidi](https://user-images.githubusercontent.com/36038029/44864428-4b150a80-ac88-11e8-8419-e0985bc8eca7.jpg)

**URL / Environment where this happened**
[https://rominacsvsms.ushahidi.io]

**If the bug is datasource related (e.g. SMS or Targeted SMS), please specify the configuration details (e.g. Frontline + Clickatell, etc):**

**Desktop Hardware Details (please complete the following information):**

**Smartphone Hardware Details (please complete the following information):**
 - Device: [Samsung S8+]
 - OS: [Android]
 - Version [Version 8.0.0]

![screenshot_20180830-194457_settings](https://user-images.githubusercontent.com/36038029/44866399-cb8a3a00-ac8d-11e8-91de-c1402756787c.jpg)

**Additional context**
This functionality however works in IOS and another Android version i.e 4 .

See video below
[20180830_191729_gif.zip](https://github.com/ushahidi/platform/files/2337037/20180830_191729_gif.zip)

**Comment by dalezak** [comment] 2018-08-30 19:37
@rowasc looks like the error is `User 0 is not allowed to create resource posts #0`.

```
{"errors":[{"status":403,"message":"User 0 is not allowed to create resource posts #0"}]}
```

Any idea why the API would return that?

**Comment by dalezak** [comment] 2018-08-30 19:47
*POST*
```
https://rominacsvsms.api.ushahidi.io/api/v3/posts
```
*BODY*
```
{"source":"mobile","form":{"id":1},"title":"iOS Simulator","content":"A test from iOS Simulator","values":{"location_default":[{"lat":52.117921,"lon":-106.661264}],"ff068758-2b7e-4a3b-af14-acbe26284ed1":["iOS Simulator"],"794636ad-5333-44db-aa09-d0ed553c06d4":["A test from iOS Simulator"],"1bf39730-3019-4c49-a0c7-c988c519effa":[]},"user":{"id":4}}
```
*HEADERS*
```
{"Accept":"application/json","Authorization":"Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6ImY4NDlhZGEzZDBlZmIwZTBiMzVlNjEyZDVhMmQxMDEzM2VkZDBiNDRiYWI5ZjAwYTgyMjc4MmVmMWU5Njc4Y2QxMjVjNTAzNjFjMDc2MDQ1In0.eyJhdWQiOiJ1c2hhaGlkaXVpIiwianRpIjoiZjg0OWFkYTNkMGVmYjBlMGIzNWU2MTJkNWEyZDEwMTMzZWRkMGI0NGJhYjlmMDBhODIyNzgyZWYxZTk2NzhjZDEyNWM1MDM2MWMwNzYwNDUiLCJpYXQiOjE1MzU2NTc3OTksIm5iZiI6MTUzNTY1Nzc5OSwiZXhwIjoxNTM1NzQ0MTk5LCJzdWIiOiIiLCJzY29wZXMiOlsiYXBpIiwicG9zdHMiLCJmb3JtcyIsInRhZ3MiLCJzZXRzIiwidXNlcnMiLCJtZWRpYSIsImNvbmZpZyJdfQ.FxPeUlfpR6YqAqKLlEe_fJqx_f-ltVbshy0dWa0oiR8jgruuFv-Wu_-6VROGuQ5-VG833Rl5He1TRZvcDh_zhUiSrqhKoUIVxdZePbMLXNg9PNgPpJnSw-V9nRmtl5YHtWEyH4k9UYLTSnEfH1ZrFXWRuECEkrfx7KqoHfgyzy0mXxGYesnqHDkIKBfTAJfnwkh9zXbpCKRxftPCXr8kObO5prRGHIeBXDflFjUbD__Rrf6kGAnIr7vxQPaxYejizPkx5wOHXnsbnOYE8YvXZdAe_ETL_lHJDzg64Ww13f4BjtgDjhF7BWU4WZTm7ITQATv8zMlMUtLEwkSElXCT7Z1RsNsJyevJYm0buIJszPQ5bB80xcGg7OO8gg1oVpaCvV26z3cCrpgVka9IHpG_e0teX7UmhHsgi33iJ9LWwRY2dI0ty-wsWr4UUpu8meXct4YecueCKiwBM6w-xefxsc6PMTLlP0pxSXGdBgHeKcB5BrAzVrPfVt1FOPI8-DPb29uUBqDvDkKuQ_EZEDlPN34FxCwPp9SX7pkNX1Jhw24pt-BBc7ZOII1XDDhgXStqSh2fZAWyAfIC1hEVc8O93Bssa2b2po_uVSZ8r4FFA58TK79kCBDt2c6Ko5aSjDH4d6-VIHJ7o4s5c5U_Shje7OWW9uKsCXOIoyJz0_e2O8U","Content-Type":"application/json"}
```

**Comment by rowasc** [comment] 2018-08-30 20:54
updating that I'm trying to reproduce this locally sending the same payload, but I haven't been able to do it yet . BUT, I can reproduce it against prod with postman at least

**Comment by dalezak** [comment] 2018-08-30 21:28
I've assigned the issue to you @rowasc, once you get things resolved on the backend just assign it back to me to verify it's working.

**Comment by rjmackay** [comment] 2018-08-30 23:08
I found if you decode the jwt (you can use jwt.io) then its missing the user id. ie instead of `"sub": "8"` it has `"sub": ""`. I'm wondering if its actually a client_credentials token? or the token handling isn't quite right in the mobile app now.
One thing that changed with lumen is that the oauth token payload return `expires_in` not `expires`. This changed with an update to our oauth library and matches the oauth spec, rather than what we had before. Unfortunately it's not backwards compatible :(

**Comment by rjmackay** [comment] 2018-08-30 23:17
I think it as an auth issue of some form. Try this:
1. Log in on the mobile app
2. See the logged in deployment home screen
3. Pull down to refresh
Get immediately logged out.

**Comment by dalezak** [comment] 2018-08-31 01:34
Good and bad news @rowasc.

The _good news_ is that @rjmackay and I tracked down the issue. 😄

The _bad news_ is the app is broken for all users until an update is approved. 😞

So previously, the API was _not_ returning a new `refresh_token` in the `grant_type: "refresh_token"` request, so the app was reusing the previous `refresh_token`.

However after the Lumen upgrade, it is returning a new `refresh_token` and it must invalidate the previous tokens as well.

So the app was getting back `{"error":"invalid_request","message":"The refresh token is invalid.","hint":"Token has been revoked"}` using a revoked token, and falling back to a client login instead.

Since it was posting a`user` but using a client login, it was returning the error `{"errors":[{"status":403,"message":"User 0 is not allowed to create resource posts #0"}]}` because of the mismatch.

I've updated the app to store the new `refresh_token` if it's returned, will be included in `1.12.3` build.

**Comment by rjmackay** [comment] 2018-08-31 07:03
I've pushed hacky workaround in a14967c that just prevents refresh tokens being revoked. That will hopefully make the mobile app work, while we wait for the update to be approved.

**Comment by rjmackay** [comment] 2018-08-31 07:26
@dalezak  let us know when the new app is live, and we'll revert this change a week or so afterwards

**Comment by rowasc** [comment] 2018-08-31 20:33
@dalezak is thihs ready to test? If yes please send it to qa backlog assigned to Eve

**Comment by dalezak** [comment] 2018-08-31 20:42
No, not yet @rowasc, was hoping to make a build for @Eve-wanderi today but also looking into https://github.com/ushahidi/platform/issues/3239 to see if there's a simple fix.

**Comment by Eve-wanderi** [comment] 2018-09-05 11:51
@dalezak is the Build ready?

**Comment by rowasc** [comment] 2018-09-07 12:39
bumping @dalezak . See Eve's comment above

**Comment by rowasc** [comment] 2018-09-14 16:12
@dalezak since the images issue is solved, can you generate the build for this one?

**Comment by dalezak** [comment] 2018-09-14 16:14
You bet @rowasc, working on it, will send out builds later this morning :+1:

**Comment by rowasc** [comment] 2018-09-27 18:35
@dalezak how did the app release/publishing go? can we close it?

**Comment by rowasc** [comment] 2018-10-19 20:46
Closing as this release went live

**Closed by rowasc** 2018-10-19 20:46 UTC
Labels: Bug, Mobile, P0 - Urgent
