### ISSUE TITLE
Hour of a photo: strange behaviuor

### ISSUE THREAD

**Issue by niccolov** [ushahidi/platform#1719] opened 2017-04-26 11:37 UTC
It happens when you change a post

### Expected behaviour

When you change a post the "timestamp" for the photo should remain the same, unless you force the change

### Actual behaviour

Everytime you modify a post and you save it, the timestamp for the photo change and goes 2 hours back :(

### Steps to reproduce the behaviour/error

Open a post, modify something and save it.

**Comment by rjmackay** [comment] 2017-11-03 01:43
Thats odd. When you say the timestamp of a photo... do you mean the date of the post itself?
Are you still seeing this issue @niccolov?

**Comment by rowasc** [comment] 2019-06-09 22:21
Closing as I can't reproduce this in current versions of platform

**Closed by rowasc** 2019-06-09 22:21 UTC
Labels: Bug
