### ISSUE TITLE
Styling issue in filters drop down

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#2327] opened 2017-11-30 10:34 UTC
### Expected behaviour
The filters box should not change sizes when I click on it

### Actual behaviour
it expands greatly in size horizontally 
-- i think it's the location search box
### Steps to reproduce the behaviour/error
go to crisisdemo.ushahidi.io
drop down filters in map mode
drop down filters in data mode

![screen capture on 2017-11-30 at 12-49-00](https://user-images.githubusercontent.com/3224856/33426458-ed36cb9c-d5d2-11e7-9096-ebea3e36248e.gif)

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by rowasc** [comment] 2019-06-11 02:37
Closing as duplicate of https://github.com/ushahidi/platform/issues/2321

**Closed by rowasc** 2019-06-11 02:37 UTC
Labels: Bug, P2 - Normal
