### ISSUE TITLE
Add post button partially hidden when using rtl-language in  Data mode.

### ISSUE THREAD

**Issue by Obadha2** [ushahidi/platform#4297] opened 2021-07-12 07:46 UTC
**Describe the bug**
When the language is switched to a rtl-language(right-to-left) then the button to add a response to a survey in data mode is 90% hidden.

**Where was the bug observed**
https://develop.staging.ush.zone/views/data

**To Reproduce**
1. Change the language of a deployment to a right-to-left language e.g Arabic
2. Open the Data view page.
3. Note that the Add button is partially hidden at the bottom right part of the screen. (see screenshot, bottom right part)

**Expected behavior**
The button should always be visible where available.

**Is there a workaround? What is it.**
Precise scrolling to access visible portion of button.

**Screenshots**
![Screenshot from 2021-07-12 10-33-47](https://user-images.githubusercontent.com/38259840/125249812-490b9b00-e2fe-11eb-8a32-967d1d6b1d7e.png)

**Desktop Hardware Details (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome
 - Version: 20.04.2 LTS

**Comment by joneskj55** [comment] 2021-10-11 18:01
Is this still happening? I just tried it on Chrome and cannot reproduce the error.

**Comment by Angamanga** [comment] 2021-10-14 08:08
@joneskj55
Could you please provide a screenshot?
It looks like it is still happening when I try to reproduce it:
![Screenshot 2021-10-14 at 10 06 43](https://user-images.githubusercontent.com/8624777/137277011-ac015619-142c-43e8-9cd5-820ca4cf0bb3.png)

**Comment by joneskj55** [comment] 2021-10-14 13:07
Hi @Angamanga I think I see why I could not reproduce the error. When I translate it to Arabic my toolbar is actually staying on the left and not moving to the right. I am probably not translating the deployment the correct way as I am just using Chrome's built in translate function which translates the page but doesn't move the toolbar. Would you mind letting me know how to translate the deployment the correct way so that I can try working on this issue?


![Screen Shot 2021-10-14 at 7 58 26 AM](https://user-images.githubusercontent.com/20748598/137323009-f1a4146e-8672-408b-a3cd-1d10b61d8a61.png)

**Comment by joneskj55** [comment] 2021-10-20 13:20
Yes, this is platform-pattern-library.

**Comment by joneskj55** [comment] 2021-10-21 17:13
@Angamanga I got this fixed. Will be submitting a PR shortly.

**Closed** 2021-12-06 10:13 UTC
Labels: Bug
