### ISSUE TITLE
[Platform Client] Passage env asks to confirm TOS after each login, despite confirmation

### ISSUE THREAD

**Issue by kinstelli** [ushahidi/platform#3210] opened 2018-08-16 23:50 UTC
**Describe the bug**
I'm guessing that this is simple, and that `TOS_RELEASE_DATE` is just not being set for platform-client env, but I'm making this placeholder ticket to inspect and confirm the situation before full migration.

**Comment by rowasc** [comment] 2018-08-17 22:08
Assigned to cycle and tagging to release so it doesn't get lost

**Comment by rowasc** [comment] 2018-08-22 13:51
@kinstelli same as @rjmackay  ,I  just logged in with a user I have used before and I don't get the error in lumen.passage. Can you confirm if this is still happening to you?

**Comment by rowasc** [comment] 2018-08-28 12:15
Closing as we could not reproduce it

**Comment by rowasc** [comment] 2018-08-29 20:32
Carolyn has been running into this randomly too

**Comment by rowasc** [comment] 2018-09-03 01:57
@crcommons any chance you could reproduce this with steps tomorrow? i'm having a hard time making this happen, but I know we have run into this. 
Thinking it may be related to different browsers/mobile/etc

**Comment by crcommons** [comment] 2018-09-04 15:31
Can't reproduce either. Closing again.

**Closed** 2018-09-04 15:31 UTC
Labels: lumen
