### ISSUE TITLE
Filters dropdown: Top Level categories with children should behave as "Select all"

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2436] opened 2018-01-31 13:28 UTC
# Current behavior:
- Top level categories are included in filters even if the user search for specific children, which means all posts with the parent selected, no matter of children, are returned in the search results.

# Expected behavior
- [ ] Top level categories are NOT included in the search if the user starts unselecting the children
    - A parent category should not remain selected if all children are unselected.
    - When you de-select a child, the parent should automatically be de-selected. The user can un-select some if they don't want them all.
- [ ] When filtering, you cannot select just a parent, unless they don't have children.

# Testing script 
Notes: run this once logged in, and once while being logged out.
- [x] Open filters dropdown 
- [x] Unselect a parent/top-level category with no children. 
    - [x] Posts that belong to that parent category should not be shown. 

- [x] When a user unselects a parent category, all its children should be unselected (devphase-addition)
    - [x] Unselect a parent category with many children
    - [x] All its children should be unselected
    - [x] Select the same parent category
    - [x] All its children should be selected again

- [x] For a parent with many children, deselect one or many children
    - [x] All other child categories should remain selected/not change
    - [x] The parent should become unselected 
    - [x] Posts that belong to any of the de-selected child categories should NOT be shown.
    - [x] Posts that belong to the parent-category only should NOT be shown. 
    - [x] Select the same child categories (so all children are selected). The parent becomes selected. 
    - [x] Posts that belong to any of the child categories and/or the parent category should be shown.

- [x] Open filters drop-down.
    - [x] Unselect all children of a parent category
    - [x] The parent is unselected
    - [x] Posts that belong to any of the children or the parent are NOT shown in the search results

# Demo script (equals testing script in this case)
- [x] Follow the test script while logged out. 
- [x] Follow the test script while logged in. 

Note: This assumes 1 level of categories which is what we support.

**Comment by rowasc** [comment] 2018-01-31 20:09
@Angamanga can you review this? Thanks

**Comment by Angamanga** [comment] 2018-02-01 15:18
@rowasc @aoduor @Erioldoesdesign Question about the behaviour: If a post only has the parent-category checked, and not the children, how do we filter that out? Even if we change the behaviour of parent-vs-children when adding a post, there is still a risk that there are already available posts with only the parent checked.

**Comment by rowasc** [comment] 2018-02-01 15:23
@Angamanga  good question. 
In short, I don't think we cannot make it backwards compatible without making this feature a mess. There are two options:
- live with this, let users know that we no longer search for parent categories . Ugly. 
- write a migration script so that posts linked to a parent category only are linked to all children in that parent category + communicate?  (potential for disaster?, should be very well tested and we need to be sure to communicate this change clearly)

**Comment by rowasc** [comment] 2018-02-01 15:24
@Angamanga from you question I have another. What happens when you link a post to a parent category , then create some more categories inside that parent category? 
:(

**Comment by Angamanga** [comment] 2018-02-02 08:44
@Erioldoesdesign @aoduor @rowasc My suggestion is to still search for parent-categories. And the user has to explicitly uncheck the parent in the filter to only search for children.

**Comment by Angamanga** [comment] 2018-02-02 08:49
Actually, the more I think of it. We shouldn't search for either-or in the backend, should we? We should include only posts that has ALL selected categories in it (except for when all is selected)?

**Comment by aoduor** [comment] 2018-02-02 09:05
> @rowasc @aoduor @Erioldoesdesign Question about the behaviour: If a post only has the parent-category checked, and not the children, how do we filter that out? Even if we change the behaviour of parent-vs-children when adding a post, there is still a risk that there are already available posts with only the parent checked.

When a parent only is checked, you filter out based on ALL it's children. I would think that when you select a parent, it should automatically select all children, and then user can deselect children(and parent if necessary) as they wish.

**Comment by Angamanga** [comment] 2018-02-02 09:07
@aoduor So you still think its important to search for parents?

**Comment by aoduor** [comment] 2018-02-02 09:30
@Angamanga @rowasc yes, it is still important to be able to search for parents. Usecase(pardon the example :P)

Top level category(parent) = fruits
Subcategories(children) = apples, mangoes, bananas, grapes, watermelons, avocadoes etc

It makes sense to have fruits as a header during the submission process, but not during the search and filtering process. Here's my reasoning why. There are two scenarios that apply here
1. I want to filter and see posts with all fruits: In this case, It makes sense to me, to be able to select the top level category (which would then in turn select all the child categories/fruits), as opposed to having to click on each and every fruit(subcategory) to get ALL of them
2. I want to filter and see posts with specific fruits: I may have specific instances where i only want to see apples, apples and mangoes, etc. My idea here would be:-

- When i select to filter for apples only( or any other subcategory), my selection is independent of the parent.

- In the event that i'm following up this search from scenario one, anytime i deselect one of the child categories, the parent category gets deselected ( a declaration of independence, lol!)

Does this make sense?

**Comment by Erioldoesdesign** [comment] 2018-02-02 09:45
Agree with above reasoning for keeping a parent selectable due to the fruit case:

_"A user cannot select 'Parent:Fruits' and then try and unselect 'mangoes' because a mango is a fruit. As soon as mango is deselected the assumption is that this user now wants to be specific with their fruit"_

However, I would suggest that styling wise a parent category have different font styling. e.g. bold and 1em font size bigger

**Comment by aoduor** [comment] 2018-02-02 09:47
> However, I would suggest that styling wise a parent category have different font styling. e.g. bold and 1em font size bigger

![screenshot](https://media.giphy.com/media/3oFzmte1x5WVErIqFq/giphy.gif)

**Comment by rowasc** [comment] 2018-02-02 13:07
@Angamanga Are we always saving the parent, when we assign a child?

**Comment by Angamanga** [comment] 2018-02-02 14:17
Styling-changes in new issue: https://app.zenhub.com/workspace/o/ushahidi/platform/issues/2458

**Comment by crcommons** [comment] 2018-02-02 14:37
Based on the conversation, it appears that the issue's expected behavior is incorrect:

*A parent category should remain selected if all children are unselected.*

If the parent acts as a select-all, then when it is selected, all children should be select. If any children are deselected, then the parent should also be deselected.

@Angamanga @aoduor @rowasc

**Comment by rowasc** [comment] 2018-02-02 14:58
yup. Thanks @crcommons

**Comment by rowasc** [comment] 2018-02-02 15:07
sending to Spec while I wait for Dale's answer

**Comment by rowasc** [comment] 2018-02-02 20:28
Answer from Dale:
You can select just a Parent in the mobile app when creating a post, even when they have children  so there are things linked to parents and not children.

**Comment by aoduor** [comment] 2018-02-05 08:54
> If the parent acts as a select-all, then when it is selected, all children should be select. If any children are deselected, then the parent should also be deselected.

This, to me is the ideal behaviour. While there may be edge cases where there are items linked to parents and not children ( e.g when a parent category is created, and you have posts assigned to it, and then later on child categories are added) - i think it creates confusion for the user, and possibly on the dev side to have the parent as independent of it's children. 

cc @dalezak @rowasc @Angamanga @Erioldoesdesign @jshorland

**Comment by Erioldoesdesign** [comment] 2018-02-05 10:11
Re: mobile app - @rowasc So does that mean the mobile app have a different behaviour to platform? ('desktop')

Parent acting like a select-all agreed. I have some sketches and copy amends that can be included in improvement tickets after they've been tested on users.

**Comment by rowasc** [comment] 2018-02-05 12:44
@Erioldoesdesign @aoduor agree. 
@Erioldoesdesign mobile app mention was about creating which could have impacted the way we filter if the mobile app didn't support what we need in web / saved the wrong thing. But it saves the correct values from our tests last friday. 
That said, yes, there might be differences. We need Dale involved in reading and checking all the scoped issues so we can prioritize any changes needed in mobile as well so they function the same way.
I will send @dalezak a list of issues to review TODAY so we can start thinking about that and getting some prioritization done in mobile for CSV+Filtering changes

**Comment by rowasc** [comment] 2018-02-06 22:26
Moved kind of slow today. I will be sending a WIP or ready-for-review PR tomorrow.

**Comment by rowasc** [comment] 2018-02-12 19:52
@jshorland demo is here https://drive.google.com/open?id=1jMnwaXgHJNJ1dsK6MKxDg2DNa6PpcNIh

**Comment by jshorland** [comment] 2018-02-14 22:54
Jess testing Feb 14
# Testing script 
Notes: run this once logged in, and once while being logged out.
- [ ] Open filters dropdown 
- [ ] Unselect a parent/top-level category with no children. 
    - [ ] Posts that belong to that parent category should not be shown. 

- [ ] When a user unselects a parent category, all its children should be unselected (devphase-addition)
    - [ ] Unselect a parent category with many children
    - [ ] All its children should be unselected
    - [ ] Select the same parent category
    - [ ] All its children should be selected again

- [ ] For a parent with many children, deselect one or many children
    - [ ] All other child categories should remain selected/not change
    - [ ] The parent should become unselected 
    - [ ] Posts that belong to any of the de-selected child categories should NOT be shown.
    - [ ] Posts that belong to the parent-category only should NOT be shown. 
    - [ ] Select the same child categories (so all children are selected). The parent becomes selected. 
    - [ ] Posts that belong to any of the child categories and/or the parent category should be shown.

- [ ] Open filters drop-down.
    - [ ] Unselect all children of a parent category
    - [ ] The parent is unselected
    - [ ] Posts that belong to any of the children or the parent are NOT shown in the search results

# Demo script (equals testing script in this case)
- [ ] Follow the test script while logged out. 
- [ ] Follow the test script while logged in.

**Comment by jshorland** [comment] 2018-02-14 23:02
One thing that I'm not sure is related to this or not, but "apply filters" button on filters drop down isn't working on map mode
https://d.pr/i/VKFa8J

**Comment by rowasc** [comment] 2018-02-14 23:38
@jshorland yea that's correct ( by design) .Apply filters is disabled in map because things are applied immediately so it's like a hint to the user that it doesn't need to be clicked

**Comment by rowasc** [comment] 2018-02-19 14:28
@jshorland this should be out of testing right? (passed?)

**Comment by jshorland** [comment] 2018-02-21 15:27
Yep sorry. Done.

**Closed** 2018-04-13 15:48 UTC
