### ISSUE TITLE
Unable to create posts in Armenian language.

### ISSUE THREAD

**Issue by arturp-a** [ushahidi/platform#4259] opened 2021-06-03 09:49 UTC
When creating a new post in English all is good the post is being created successfully. However, when I change the language to Armenian and fill the "Title" and "Description" fields of the post there is an error "Error: slug Slug is required".

Deployment and page URL  "https://ggg.ushahidi.io/posts/create/4"

1. Go to 'Data'
3. Click on add new post
4. Select Post example
5. Change typing language to Armenian
6. Type something in Title or Description fields
7. Click submit you will see the "slug Slug is required" error.

**Comment by tuxpiper** [comment] 2021-06-04 08:37
It looks like this may be caused by Laravel's `Str::slug()` (invoked in our `BaseModel::makeSlug()`) returning an empty result when passed an Armenian string.

Apparently, this is now fixed in more recent versions of Laravel:

```
$ ./artisan tinker
Psy Shell v0.10.8 (PHP 7.3.28 — cli) by Justin Hileman
>>> use Illuminate\Support\Str;
>>> Str::slug("Կրուասան եմ ուզում")
=> "krvouasan-em-vouzvoum"
```

Since the utility of slugs in our current app right now seems to be very marginal, I'd suggest adding some stop-gap in our code that generates a random string when Str::slug() fails.

**Comment by arturp-a** [comment] 2021-06-04 10:18
Is there any workaround to this issue for now as a quick solution?

**Comment by tuxpiper** [comment] 2021-06-04 10:24
A quick workaround can be adding a few latin script characters after the Armenian title, i.e.  "թեստային գրառում (abc)".

These extra characters can then be removed by editing the post. Users reporting anonymously will not be able to do this themselves, so an administrator would have to do it for them.

**Comment by arturp-a** [comment] 2021-06-04 10:35
All right thank you very much, for now will use with this workaround. Just a clarification when can we expect the fix to be merged to the  Next minor release?

**Comment by tuxpiper** [comment] 2021-06-04 10:43
We should have a fix pretty soon. I estimate that would be applied to our ushahidi.io hosting service at the beginning of next week.

**Closed** 2021-06-08 07:18 UTC
Labels: Bug, P0 - Urgent, Release: Hotfix

**Comment by arturp-a** [comment] 2021-06-08 14:28
Hi all, thank you for the fix I have tested it on "https://develop.staging.ush.zone/views/map" this deployment. It works fine.
Whereas it is not working on my deployment "https://ggg.ushahidi.io/posts/create/3" when creation posts.

**Comment by tuxpiper** [comment] 2021-06-10 07:48
Hi @arturp-a  ! That URL is where we do QA sometimes. Now it's all cleared out and today we will be deploying the fix to *.ushahidi.io . 

Cheers,
