### ISSUE TITLE
Posts Not Appearing on Map

### ISSUE THREAD

**Issue by Shadrock** [ushahidi/platform#1213] opened 2016-06-13 21:35 UTC
**This is for the COMRADES deployment**: http://comrades.ushahidi.com/views/map

### Expected behaviour
That approved posts set to "Everyone can see this." Would be visible in map view (especially while logged in). 
### Actual behaviour
Created a post while not logged in. Then logged in and approved post and set to "Everyone can see this." Post does not appear in map view but does in timeline view. 
### Steps to reproduce the behaviour/error
Create a post while not logged in. Then log in, approve post, and set to "Everyone can see this." Go back to map view. It appears that to get the map marker so show up I need to refresh the URL. http://comrades.ushahidi.com/views/map. I have to do this any time I leave the map view and then return to it.

**Comment by rjmackay** [comment] 2016-06-13 22:13
@zhalloran this might be a dupe of the other map bugs I think.

**Closed** 2016-06-14 03:42 UTC
Labels: P0 - Unbreak now!, QA: Confirm Fixed
