### ISSUE TITLE
Unable to change survey name on 6th survey

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1314] opened 2016-07-26 14:28 UTC
From grassroots user adviceni.ushahidi.io 

"I’ve been creating the surveys and putting all the fields in under one task – you’re right, it makes it much easier for the user. It worked well for the 1st 5 surveys. However from 6 on when I create a new survey it won’t let me change the name of the first task which it automatically creates and calls “post” and it won’t let me delete it so I have to add a 2nd task. I’m not sure why it’s doing this and how I can fix it. If you look at our deployment you can see that it starts to go wrong with the “Sure Start Maternity Grant (unable to apply for 2nd subsequent child) Benefits” survey.

@willdoran would you mind taking a look into this when you have a chance?

**Comment by jshorland** [comment] 2016-07-26 14:29
https://app.intercom.io/a/apps/hl5rfiga/inbox/jess@ushahidi.com/conversations/5467641498

**Comment by willdoran** [comment] 2016-07-26 15:29
hey @jshorland the default task "Post" is fixed and can't be renamed, I believe this is an intentional UI design. Do we want to change this to make the task renameable?

**Comment by jshorland** [comment] 2016-07-26 16:27
I double checked with the user, and she says she was able to change the first task from Post to a custom title, but wasn't able to do the same at the 4th or 5th survey she created. I've asked her to give me admin privileges to confirm this.

**Comment by willdoran** [comment] 2016-07-26 16:28
thanks! Hmm that is very strange

**Comment by jshorland** [comment] 2016-07-26 16:28
I was also able to change the first task's title in quakemap.ushahidi.io

**Comment by willdoran** [comment] 2016-07-26 16:29
Super weird, I'll test it here

**Comment by willdoran** [comment] 2016-07-26 16:51
Hmmm, I can't edit on my local or on my ushahididev.com instance. Were you able to edit it directly in the text box? Did you save first?

**Comment by jshorland** [comment] 2016-07-26 17:05
Update: the surveys on which she was able to edit the name of the first task were from her deployment pre-mustang. Surveys she's now creating post-mustang migration do NOT allow for changing first task name from "post". @brandonrosage do you mind reminding me of the thinking behind this?

**Comment by brandonrosage** [comment] 2016-07-27 14:30
Short answer: In a world where Ushahidi allows "free-form" tasks, all task names should be editable.

Slightly longer answer: The rollout of Mustang first offered a model for Tasks that was more "choose from these pre-built tasks." And that's where fixed task names originated. The constraints of the release led to this semi-clumsy hybrid.

I'm seeing editable task names across the board on my demo deployment, though. So I'm not clear what the issue is with the current client.

**Comment by jshorland** [comment] 2016-07-27 14:34
@brandon that's because those are surveys you created prior to mustang that retained that edit able quality in migration.

Try to create a new survey and edit the first pre-loaded task name to replicate the issue. It's presented a bit of confusion for pre-mustang users and requests for custom names from new users.

I'd suggest we make all tasks editable.

**Comment by brandonrosage** [comment] 2016-07-27 14:39
Oh, I see. It's presented as a field. So I assumed I could change it. Of course, it's disabled. Yeah, that needs to be editable in a "free-form" model.

**Comment by willdoran** [comment] 2016-08-01 17:42
@brandonrosage @jshorland I will change this to allow users to edit all tasks - @brandonrosage, all tasks should thus be reorderable, yes? At present the fixed "Post" task is not.

**Comment by jshorland** [comment] 2016-08-03 10:11
@willdoran yes, all tasks should be re-orderable as well.

**Comment by rjmackay** [comment] 2016-08-07 22:56
> @willdoran yes, all tasks should be re-orderable as well.

Wait... With the split of Post fields from Task fields I don't think we should treat 'Post' as a task at all. I think this need to loop back to design because [this design](http://preview.ushahidi.com/platform-pattern-library/develop/assets/html/5_layouts/settings-survey-edit.html) doesn't have UI to reorder tasks at all.

**Comment by brandonrosage** [comment] 2016-08-10 19:21
Two things to resolve here:

1. The process and timing for the build-out of Tasks. My understanding was that we'd finish staging a design solution in the PL before the next sprint planning meeting (which launches the client implementation). So while I have a solution for this, I've been careful not roll it out until it had been more thoroughly reviewed.

2. The solution to this point *does* provide, A, separation between "Post fields" and "Task fields", and B, UI for re-ordering a survey's tasks.

_Example:_
![Tasks](https://cloud.githubusercontent.com/assets/1136279/17567565/87a99e3e-5f05-11e6-8ac7-6441cb71b739.png)

I'd appreciate some clarity, @rjmackay and @jshorland, on how I can best time the staging of all this so design is not at all a bottleneck for the implementation of this feature.

**Comment by jshorland** [comment] 2016-08-15 21:39
Sorry for my delay here. @brandonrosage we won't be able to start implementing tasks until after hit team. I'll have a more detailed schedule based on recent issues submitted into out github by wednesday of this week. Is there more clarity you'll need beyond timing for tasks?

**Comment by brandonrosage** [comment] 2016-08-15 21:48
Just a shared understanding of how it'll work ([I've outlined a solution](https://github.com/ushahidi/biz/issues/6)) and the deadlines for each phase of work on the epic.

**Comment by rjmackay** [comment] 2016-09-06 20:39
Assigned to @jshorland for QA since this is probably solved in last sprint

**Comment by jshorland** [comment] 2016-09-23 17:46
@brandonrosage correct me if I'm wrong, but this really gets addressed in free-form survey build also addressing #1335

**Comment by brandonrosage** [comment] 2016-09-23 18:29
@jshorland Spot on.

**Closed** 2016-10-03 21:32 UTC
