### ISSUE TITLE
CSV export not exporting on qa.ushahididev.com

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#2106] opened 2017-10-04 14:44 UTC
Export throwing blank error. 

- Log in to QA
- Export all posts from map view -- don’t filter anything
- Also -- error message has styling errors (see screenshot). Dismiss is too close to the error icon. And the white triangle is not centered in the red circle.

![Screen Shot 2017-10-04 at 7.19.03 AM.png](https://zube.io/files/ushahidi/7e10fca0eb31803b5193ffa91e47920b.png)

After trying multiple times, it's started giving me a success message, but my download says "failed - network error". This happens from both map and timeline view.

![Screen Shot 2017-10-04 at 7.43.39 AM.png](https://zube.io/files/ushahidi/4b2133d24f14ad351d6216fa8ef59c65.png)

**Comment by jshorland** [comment] 2017-10-04 14:45
Note: this does NOT happen when I filter down to a smaller set of posts. Only when I'm trying to export everything.

**Comment by rowasc** [comment] 2017-10-04 14:51
debug info

Request URL:http://qa.api.ushahididev.com/api/v3/posts/export?form%5B%5D=1&form%5B%5D=2&form%5B%5D=3&form%5B%5D=4&form%5B%5D=5&form%5B%5D=6&form%5B%5D=7&form%5B%5D=8&form%5B%5D=10&form%5B%5D=15&form%5B%5D=26&form%5B%5D=28&form%5B%5D=29&form%5B%5D=30&form%5B%5D=32&form%5B%5D=33&form%5B%5D=34&form%5B%5D=35&form%5B%5D=36&form%5B%5D=37&form%5B%5D=39&form%5B%5D=41&form%5B%5D=none&format=csv&has_location=all&source%5B%5D=sms&source%5B%5D=twitter&source%5B%5D=web&source%5B%5D=email&status%5B%5D=published&status%5B%5D=draft
Request Method:GET
**Status Code:504 Gateway Time-out**


:( Weird. I tested with bigger datasets back when this was in development. 
I will take a look ASAP

**Comment by aoduor** [comment] 2017-10-17 08:12
related to #2154. I successfully managed to download a CSV file.

**Comment by rowasc** [comment] 2017-10-27 12:41
Folks I'm going to close this in favor of #2154 (which is WIP)  since it's a duplicate/included . I'm trying to tidy up our CSV tickets a bit since it's all over the place. I

**Comment by rowasc** [comment] 2017-10-27 12:42
TBC: This was not fixed YET. It's a dupe of #2154 which is in progress

**Closed by rowasc** 2017-10-27 12:41 UTC
Labels: Bug, P0 - Unbreak now!
