### ISSUE TITLE
Saving a post successfully shows a blank error message

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#2198] opened 2017-10-20 01:37 UTC
### Expected behaviour
Saving a post successfully should show a success message, and no errors

### Actual behaviour
Show a success message *and* and error message

### Steps to reproduce the behaviour/error
1. Edit a post
2. Make a change
3. Save the post

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [x] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by kinstelli** [comment] 2017-10-23 19:05
I believe this got fixed with 2186, and I can't reproduce this problem anymore.

**Closed** 2017-10-24 01:05 UTC
Labels: 2chaguzi, P1 - Immediate, Stage: Testing
