### ISSUE TITLE
RTL is not applied automatically on language change

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#1816] opened 2017-06-24 10:40 UTC
### Expected behaviour
- When selecting an RTL language the UX should switch to RTl
### Actual behaviour
- When selecting an RTL language the UX does not switch only the language file is loaded

**Comment by jshorland** [comment] 2017-06-27 16:16
If possible, This is ideally fixed for GISCON kuwait delivery.

**Comment by middle8media** [comment] 2017-07-25 00:39
@jshorland top priority tomorrow.

**Comment by dalezak** [comment] 2017-07-27 15:52
Related to mobile issue https://github.com/ushahidi/platform-mobile/issues/160

**Comment by Celestine22** [comment] 2017-07-27 15:54
@middle8media is this done?

**Comment by middle8media** [comment] 2017-07-27 16:23
I am currently working on this.

**Comment by middle8media** [comment] 2017-07-28 17:37
I went through the whole pattern library and updated each pattern/layout to support RTL [here](https://github.com/ushahidi/platform-pattern-library/commit/1ce1d527a836b74c4e5e01d91cf412d524d22061) and then published to npm via [this](https://github.com/ushahidi/platform-pattern-library/commit/93b47006407f2c146b04a719c61062d61c30e744)

If all goes well, once the PL is installed in the client and the RTL stylesheet triggered, the UI should be a full RTL reflection. That being said we will need to test in the client because I am sure some things will be broken.

As a review, RTL support in the PL is designed to be a mirror image. So for example:

default LTR Survey Filter
![image](https://user-images.githubusercontent.com/1033332/28728977-c42a0954-7398-11e7-8096-b611b52d1afe.png)

RTL Survey Filter
![image](https://user-images.githubusercontent.com/1033332/28728993-cd4f4eae-7398-11e7-8458-82f9d55fee8c.png)

Patterns can be tested [here](http://preview.ushahidi.com/platform-pattern-library/master/) via the "Read Direction" switcher in the top right navigation bar.

**Comment by rjmackay** [comment] 2017-08-02 03:00
@middle8media did you go through layouts too?

Looking at http://preview.ushahidi.com/platform-pattern-library/develop/assets/html/5_layouts/map.html
- If you switch to RTL, the categories in the mode context are no longer visible. 
- I'd also generally expect the mode bar and mode context to move to the right side of the page when in RTL (though @justinscherer could correct me if that shouldn't happen)

**Comment by middle8media** [comment] 2017-08-02 14:24
@rjmackay I am currently working on layouts. Yes, I agree, the PL is designed to be a mirror image with in RTL.

**Comment by middle8media** [comment] 2017-08-04 20:16
The PL layouts now fully support RTL.

To test:
- http://preview.ushahidi.com/platform-pattern-library/develop/assets/html/5_layouts/map.html
- choose a layout
- toggle the “direction switcher” in the mode-bar

**Comment by middle8media** [comment] 2017-08-21 15:44
This can be closed

**Comment by rjmackay** [comment] 2017-08-22 04:17
@Angamanga assigning this to you. We just need to confirm if this all works in the client now, or if it needs some markup updates.

**Comment by Angamanga** [comment] 2017-08-22 13:20
This needs some adjustments, the text changes to right to left in the client, but not the layouts.

**Comment by middle8media** [comment] 2017-08-22 14:15
@Angamanga I want to make sure we are fixing as intended, please let me know what you find.

**Comment by Angamanga** [comment] 2017-08-23 09:08
@middle8media We need to look at it together so I scheduled a time for tomorrow. In the pl, different stylesheets for rtf and ltr are loaded with js instead of class, but that is not happening in the platform-client.

**Comment by rjmackay** [comment] 2017-08-24 03:29
Its possible webpack is going to make swapping the entire style sheet pretty tricky. Let me know if you need pointers on how to manage that.

**Comment by middle8media** [comment] 2017-08-25 16:43
The tension is that the whole RTL system is designed to toggle stylesheets and although I believe it could be done, though not totally sure based on how the RTL sass is designed, it would be a major overhaul to convert over to styling based on the `rtl` body class.

**Comment by Angamanga** [comment] 2017-08-31 08:14
@rjmackay Do you have any comments on the separate stylesheets? I don't have enough knowledge of webpack to give a good answer.

**Comment by rjmackay** [comment] 2017-08-31 19:58
I haven't had a chance to look into it yet. We'd have to hack it for webpack, and I'm not sure it'd work. We can pair up on this next week

**Comment by rjmackay** [comment] 2017-09-08 04:56
I've spent pretty much an entire day on this. Its really hard to make webpack handle the 2 styles separately, and even harder to disable one of them once loaded.
I've gone back to the PL and I'm working on namespacing the styles there instead. I'll send a PR to the pattern library soon

**Comment by rowasc** [comment] 2018-09-13 22:40
This was released and confirmed. Closing as duplicate

**Closed by rowasc** 2018-09-13 22:40 UTC
Labels: Bug, P1 - Immediate
