### ISSUE TITLE
Intercom button and yellow FAB overlap

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#2315] opened 2017-11-29 07:45 UTC
### Expected behaviour
The FAB should appear below the Intercom FAB
### Actual behaviour
<img width="725" alt="screen shot 2017-11-29 at 10 43 52 am" src="https://user-images.githubusercontent.com/29209303/33363664-66bf3044-d4f2-11e7-9d3e-4ea5bc244cae.png">

### Steps to reproduce the behaviour/error
go to map view or data view

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by jshorland** [comment] 2017-11-29 07:46
WE KNOW! duplicate of #2290, closing in favor of that.

**Closed by jshorland** 2017-11-29 07:46 UTC
