### ISSUE TITLE
Task completed toggle not working on some tasks

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1865] opened 2017-07-13 15:10 UTC
Can toggle one at a time, but not multiple. And a user in intercom mentioned their task toggle button isn't working at all. And with validation requirements, they therefore can't publish posts.

**Comment by ryanchristo** [comment] 2017-07-18 10:28
@jshorland I'm not able to reproduce the issue. I created a survey with two tasks and then created a new post and was able to toggle `task completed` for both tasks and save the post. Do you have an example deployment I could look at? Do the tasks that the toggle is not working for have something in common or maybe something that makes them different from the other tasks?

**Comment by aoduor** [comment] 2017-08-02 10:16
confirming i had this same problem on the UWIANO project

**Comment by diegodorgam** [comment] 2017-08-11 02:34
I'm Having a related error.
I have a post with 8 activities, and only the first toogle works. 

The funny thing is that from activity 2 to activity 8 the toogles don't move, but when you click then the activity 1 toogle's moves.

very weird behaviour, but it seems that all toogles are activating the first activity's toogle.

**Comment by Angamanga** [comment] 2017-08-23 12:39
I cannot reproduce this either. @aoduor or @diegodorgam could you please share a screenshot what it looks like? I tried on a survey with many tasks and all toggles works, no matter what order I toggle them. Tried in Chrome and Safari.

**Comment by rjmackay** [comment] 2017-08-30 23:17
I think this was fixed by Will. Closing. Reopen if its still happening in the latest release

**Closed by rjmackay** 2017-08-30 23:17 UTC
Labels: Bug, P0 - Unbreak now!, Stage: Dev Backlog
