### ISSUE TITLE
Newly Created Surveys Not Appearing

### ISSUE THREAD

**Issue by dalezak** [ushahidi/platform#2291] opened 2017-11-21 15:32 UTC
### Expected behaviour
After creating a survey, it should appear as an option in the Surveys list, so I can submit a report for it.

### Actual behaviour
After what appears to have successfully created a survey, it does not appear in list of available surveys, which resulted in me creating the same survey three times.

#### Creating A New Survey
![screenshot 2017-11-21 08 51 53_preview](https://user-images.githubusercontent.com/91811/33080715-5f8b4466-ce9e-11e7-8629-a81b608708d4.png)

#### Survey Created
![screenshot 2017-11-21 08 52 05_preview](https://user-images.githubusercontent.com/91811/33080789-895fa0e8-ce9e-11e7-8396-29028a585554.png)

#### New Survey Not Listed
![screenshot 2017-11-21 09 23 08_preview](https://user-images.githubusercontent.com/91811/33080826-9e127e48-ce9e-11e7-9708-80d7c2075802.png)

#### After Login In Incoginto Window New Surveys Appear
![screenshot 2017-11-21 09 22 55_preview](https://user-images.githubusercontent.com/91811/33080878-b748df06-ce9e-11e7-8c2c-8183d677fa71.png)

It wasn't until I did a `Clear Browsing Data...` that the new surveys appears in Chrome.

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [X] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by dalezak** [comment] 2017-11-21 15:32
Here's the issue @jshorland

**Comment by caharding** [comment] 2018-03-23 00:08
Do you know if this issue is still occuring?

**Comment by Angamanga** [comment] 2018-04-13 13:38
@dalezak I cannot reproduce this anywhere, have tested locally, on qa and .io. Could you check if it is still happening for you?

**Comment by rowasc** [comment] 2018-04-13 13:40
@Angamanga there used to be a refresh issue. It was fixed here https://github.com/ushahidi/platform-client/pull/1007
 It already made it to production. 

AKA:  We need good release logs =(

**Comment by rowasc** [comment] 2018-04-13 13:41
https://github.com/ushahidi/platform-client/commit/ad71947367186611bf3c0649c5b8f0cc26f4f85e

**Comment by Angamanga** [comment] 2018-04-13 20:10
ok, thanks @rowasc. @caharding and @crcommons this is not an issue anymore so closing.

**Closed by Angamanga** 2018-04-13 20:10 UTC
Labels: Bug, P0 - Unbreak now!
