### ISSUE TITLE
No tweets being pulled in despite correct data source integration

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1582] opened 2017-02-09 07:29 UTC
### Expected behaviour
* We should be seeing posts from tweets under #resist and #equality on https://equality.ushahidi.io under the Unknown posts saved search

### Actual behaviour
* We're getting no tweets corresponding to hashtags set under twitter configuration

### Steps to reproduce the behaviour/error
* Log into your deployment
* Set up twitter config
* Set up hashtags #equality #resist 
* Check the Unknown posts saved search

cc @natmanning 

Worth noting that I tested with my own twitter credentials just to be sure that Nat's weren't the problem.

**Comment by aoduor** [comment] 2017-02-28 08:01
Got another one of our users complaining about the same issue on intercom.

See below. 

"I have gone through all of the support materials, and I just need a little help with troubleshooting if you have a moment.

As far as I can tell, I have set up the twitter and email data sources correctly.

If the twitter feed is supposed to forward hashtagged tweets into the installation as unknown posts, it is not happening. I did test posts with the appropriate hashtags and nothing came through. I also sent emails to the exclusive email account set up for receiving posts, and nothing came through.

I imagine that my assumptions about possible use might be wrong, or I might have made an error in settings setup. Can you please offer some simple examples on how these two should work when used correctly? There is great information on setup, but I could use some guidance on putting them into practice and understanding the flow of data.

Thanks so much for your help!

Best,

Frank"

**Comment by willdoran** [comment] 2017-03-01 18:10
There appears to be a bug with hashtags, it works correctly when the # is dropped. I'll take this now.

**Comment by Angamanga** [comment] 2017-03-02 13:30
I dont manage to reproduce it, for me, both # and no-# works locally, but only with a `,` between the search-terms. Where did you reproduce it @willdoran ? I am going through the requests we do anyway and check that we are doing correct queries to twitter...

**Comment by willdoran** [comment] 2017-03-06 20:52
@Angamanga Just to clarify here, I was able to reproduce on staging and prod, but did it succeed for you? I'll try again to see if I can still reproduce.

**Comment by Angamanga** [comment] 2017-03-06 21:27
@willdoran no, i could not reproduce it, tried on staging (qa.ushahididev.com) and locally with different variations of search-terms and they comes through.

**Comment by jshorland** [comment] 2017-03-07 07:19
On QA.ushahididev.com, I could not reproduce this. cc: @willdoran

**Comment by Angamanga** [comment] 2017-03-07 08:05
This is what I have changed to try to make the tweets work better: I have tweaked the fetch-functionality a bit in pr to reset the last imported twitter to 0 when new search-terms are added. This might have limited which new tweets are being pulled in when a new search-term was added (before i did that only newer tweets than the last one imported was being pulled in, even if I added new search-terms. This might have caused this problem). I will also check that the jobs that pulls in the tweets in https://equality.ushahidi.io work as they should today.

**Comment by fsindaco** [comment] 2017-03-14 15:15
Hello. I am the user referenced above by aoduor. I thought I'd check in, as I created a new twitter app (set to read/write, if that matters) and put in the new information for the data source for my installation: https://movemap.ushahidi.io
Sadly, there is still nothing showing up in the unknown posts. 
I have to make some choices and weigh factors about project implementation very soon, and I am wondering if twitter will be a reliable and viable data source. How can I get this working? I am having a similar problem with the email data source.
Please know that I am quite thankful for your work, the installation, and the support.

**Comment by jshorland** [comment] 2017-03-17 19:35
@rjmackay @Angamanga is there still an issue with the job queue? (the problem that @rjmackay fixed in dreamsdemo.ushahidi.io)?

**Comment by Angamanga** [comment] 2017-03-17 20:52
@jshorland I think @rjmackay started the workers that pulls in the tweets again this week so should be ok now.

**Comment by rjmackay** [comment] 2017-03-20 03:32
I think the job queue broke again when rackspace restarted the server. It should be working again as of this morning. We need better alerting so it doesn't go unnoticed so long :/

**Comment by fsindaco** [comment] 2017-03-31 01:17
Everything is working wonderfully now. Thanks!

**Comment by jshorland** [comment] 2017-04-12 00:48
Can we close this now @rjmackay ?

**Closed** 2017-04-12 00:55 UTC
Labels: Bug, P0 - Unbreak now!, Stage: Testing
