### ISSUE TITLE
CSV import column mapping UI doesn't work on Firefox

### ISSUE THREAD

**Issue by tuxpiper** [ushahidi/platform#2603] opened 2018-03-15 11:44 UTC
See https://github.com/ushahidi/platform/issues/3297 for more information 
### Expected behaviour
When importing a CSV file using the Firefox browser, I should be able to map the correspondence between columns in the CSV and the survey questions.

### Actual behaviour
The mapping options appear empty, so there's no way to tell what I'm actually selecting

![2018-03-15 12 40 16](https://user-images.githubusercontent.com/467393/37461290-2680c7a4-284e-11e8-94cd-59a3a7c3685b.gif)

### Steps to reproduce the behaviour/error
- As an administrator, Go to Settings -> Data Import
- Upload a CSV and try to map its fields to a survey
- You will see that no options are displayed

##### Where
- [x] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [x] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [x] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain): 

### Fixing this issue

- Fix in https://github.com/ushahidi/platform-client repo
- Hint :bulb: The code handling users can be found here: https://github.com/ushahidi/platform-client/tree/develop/app/settings/data-import/data-import.html
- Note: I think it's fixed by adding the text of the {{column}}  in the <option> around line 186, but need to be tested. 

#### Sending a Pull Request after fixing it 
- When you are done, 🔀 Start a Pull Request. There are two ways how you can start a pull request:

   1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

   2. You can also[ edit files directly in your browser](https://egghead.io/courses/how-to-contribute-to-an-open-source-project-on-github) and open a pull request from there.

- 🏁 When done Ask in comments for a review :)

## Want to work on this issue?🙋 
Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

Ping @rowasc if you need help with this issue!

Aha! Link: https://ushahiditeam.aha.io/features/PROD-409

**Comment by rowasc** [comment] 2019-06-11 18:41
Still happening in new versions of Firefox

**Comment by individual-it** [comment] 2020-04-02 02:35
fix in https://github.com/ushahidi/platform-client/pull/1477

**Comment by rowasc** [comment] 2020-04-02 03:17
@Obadha2 can you test in the morning?

**Comment by Obadha2** [comment] 2020-04-02 09:39
QA'd, passes! 👍

**Comment by renujain31** [comment] 2020-10-01 05:30
Hey, I guess the issue is already fixed. If not, can I help on this one? Thanks!

**Comment by Angamanga** [comment] 2020-10-01 11:55
This appear fixed so closing this issue. @renujain31 I am adding more issues today, check out this one for example: https://github.com/ushahidi/platform/issues/4076

**Closed by Angamanga** 2020-10-01 11:55 UTC
Labels: Bug, Codebase: Client, Community Task, Hacktoberfest, Theme: Browser compatibility issues, Theme: Data import, good-first-issue
