### ISSUE TITLE
USH-023 — Internal Server Error While Uploading Photo

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#1618] opened 2017-03-06 07:54 UTC
### Expected behaviour
- Don't show (detailed) error messages to users.
- Validate the input.
### Actual behaviour
- An internal server error appears when using a NULL byte in the filename. This reveals the underlying host where the images are located.
- Server throws a 500, not 422

```
{"errors":[{"status":0,"title":"Client error response\n[status code] 412\n[reason
 phrase] Precondition Failed\n[url] https:\/\/storage101.ord1.clouddrive.com
\/v1\/MossoCloudFS_e606dc27-4d2f-4bbb-8ea9-ff12ba538332\/platform-cloud\/svink.api.ush
ahidi.io\/5\/8\/58a6821538ad0-test.png%00","message":"Cli
ent error response\n[status code] 412\n[reason phrase] Precondition Failed\n[url]
 https:\/\/storage101.ord1.clouddrive.com\/v1\/MossoCloudFS_e606dc2
7-4d2f-4bbb-8ea9-ff12ba538332\/platform-cloud\/svink.api.ushahidi.io\/5\/8\/58a6821538
ad0-test.png%00"}]}
```

### Steps to reproduce the behaviour/error
- [ ] Simulate a file upload where the file name is `test.png%00`
- [ ] Server throws an error
- [ ] Error shouldn't contain paths.

## Implementation

- Validate file name in Media Create validator
- Modify Ushahidi\Core\Tool\Uploader
    - Add try/catch blocks around `fs` calls where needed and ensure we are catching error
    - Throw appropriate errors ie. validation or client errors.
- Modify CreateMedia usecase:
    - Move `$this->uploader->upload` to try/catch block. 
    - If it fails, trigger a Validator exception (or something else where appropriate)

Caveat:
- Uploader is modified/deprecated in lumen. If we can resolve this issue solely within the usecase - do that.

**Comment by rowasc** [comment] 2018-06-25 18:39
Does this need a more detailed spec or is it good to go?
@rjmackay @willdoran ?

**Comment by rjmackay** [comment] 2018-06-25 21:14
I think it's straight forward. Error messages shouldn't include paths, in this case I think its because we send the flysystem error back in the response. We can drop that.

**Comment by rjmackay** [comment] 2018-06-25 23:05
@rowasc added more to the spec. Is that sufficient?

**Comment by rjmackay** [comment] 2018-06-26 18:08
I'll bump it to a 2 just to account for checking the develop and master branches for the issue

**Comment by rowasc** [comment] 2018-07-06 00:09
I just tested this in qazone and it worked. I also confirmed that I was able to reproduce the issue before the fix landed in that server.

**Closed** 2018-07-11 19:38 UTC
