### ISSUE TITLE
bug in editing post collections.

### ISSUE THREAD

**Issue by spiral99** [ushahidi/platform#1407] opened 2016-09-22 10:08 UTC
### Expected behaviour

editing  a collection should make observable changes to the selected colllection
### Actual behaviour

Trying to edit a created collection doesn't seem to work as expected instead the feature creates a new collection while retaining the unedited collection.  
### Steps to reproduce the behaviour/error
1. Login to your deployment
2. Click on the collection icon on the bottom left of the page and create a new collection.
3. Click on the created collectioncand attempt to edit.
   ![2016-09-22 1](https://cloud.githubusercontent.com/assets/7393879/18744124/3439116c-80c5-11e6-985d-9ccf7a15c467.png)
   ![2016-09-22 2](https://cloud.githubusercontent.com/assets/7393879/18744127/3973fade-80c5-11e6-960c-cdb51f7e8a99.png)
   ![2016-09-22](https://cloud.githubusercontent.com/assets/7393879/18744133/3c0952e4-80c5-11e6-9462-0055c2413265.png)

**Comment by rjmackay** [comment] 2016-09-26 01:01
Thanks for the bug report @spiral99 
I think this is a duplicate of #1402 .. though you've provided MUCH more info thanks!

**Comment by willdoran** [comment] 2016-10-05 20:16
@rjmackay I just fixed 1402, it's PR is up on the repo

**Comment by rjmackay** [comment] 2016-10-19 22:07
@willdoran I see https://github.com/ushahidi/platform-client/pull/355 which fixed https://github.com/ushahidi/platform/issues/1413 
but not #1402

Am I missing something?

**Comment by willdoran** [comment] 2016-10-19 22:09
@rjmackay I think that was a typo on my part I meant #1413

**Comment by rjmackay** [comment] 2016-11-10 19:46
Test on http://qa.fix-collection-editing-14-7.ushahidilab.com/

**Comment by jshorland** [comment] 2016-11-10 19:53
Editing name of collection is successful. 

Editing default view does not work.

Editing permissions is ok to change only upon returning to the collection/refreshing.

**Comment by rjmackay** [comment] 2016-11-11 04:08
I think setting view mode works as expected. You can view a collection with either map or timeline view.. the default is just the default with you first navigate to it. It won't change mode when you reload the view, because the URL is `/collections/5/list` or `/collections/5/map`. That is the way this worked prior to this change too

To test
1. Open collections menu and click on a collection
2. Edit collection and set default viewing mode to 'map'
3. Save the collection
4. Open collections menu and click on the same collection
It will take you to the map.
Repeat with timeline mode.

**Comment by rjmackay** [comment] 2016-11-11 04:09
I'm going to land the change since it fixes the original bug. I can do a follow up if the default view behaviour is a problem.

**Closed** 2016-11-17 22:48 UTC
Labels: Bug, P1 - Immediate
