### ISSUE TITLE
[USH-942] update Language Input Under Post Title in Post Edit Modal In The Map View (Mobile Version)

### ISSUE THREAD

**Issue by Mh-Asmi** [ushahidi/platform#4726] opened 2024-03-01 08:51 UTC
Design ticket [USH-817](https://linear.app/ushahidi/issue/USH-817/replace-language-input-under-post-title-in-post-edit-modal-in-the-map)

<sub>From [SyncLinear.com](https://synclinear.com) | [USH-942](https://linear.app/ushahidi/issue/USH-942/update-language-input-under-post-title-in-post-edit-modal-in-the-map)</sub>

**Comment by Felysilver** [comment] 2024-03-06 19:12
@Mh-Asmi, @Angamanga  may this be assigned to me.Thanks

**Comment by Angamanga** [comment] 2024-03-08 12:51
Duplicate of https://github.com/ushahidi/platform/issues/4731, closing

**Closed by Angamanga** 2024-03-08 12:51 UTC
