### ISSUE TITLE
Add "instructions" field on post type steps

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#796] opened 2015-10-26 07:03 UTC
Adding instructions will help in internal training and workflow processes and make how to complete the steps easier to understand

**Comment by rjmackay** [comment] 2015-10-27 02:01
@jshorland Is this a duplicate of #680 ?

**Comment by rjmackay** [comment] 2015-10-27 02:04
actually #680 was something slightly different.
I think there is a pattern for instructions on individual fields, but not steps. Jess can you add more info about how this would work? or why its different/needed?

**Comment by jshorland** [comment] 2015-10-27 06:30
yup. 

Use case example: I am not an administrator on the deployment, but am part of a team helping to manage incoming posts. I log in to the deployment and see that there are posts that need to be verified. I click on the post and move to the "verification" step. It has fields for data input, but I wonder "how does the organization want me to actually verify this post? What does "verify" mean to them and how would they like me to go about it? A place to include instructions, similar to a post type description, could help answer these questions and improve team training and internal efficiency.

**Comment by caharding** [comment] 2017-07-19 16:03
@jshorland closing this issue as it will be covered in tasks. Adding to the user story in #1381 and closing

**Closed by caharding** 2017-07-19 16:03 UTC
Labels: Enhancement, Feature request, Icebox, P4 - Wishlist, Theme: Settings
