### ISSUE TITLE
Unable to download CSV

### ISSUE THREAD

**Issue by StaicyG** [ushahidi/platform#2849] opened 2018-04-26 14:56 UTC
### Expected behaviour
The user should be able to receive the downloaded CSV file after selecting "Export CSV file"

### Actual behaviour
The process gets stuck at "Export in progress" for a long period of time then the user gets logged out

### Steps to reproduce the behaviour/error
Logged into my deployment www.speech.ushahidi.io
Select Settings
Select Export CSV
Select Export All data
Process gets stuck at "Export in progress" then times out

#### Where does this issue happen?

- [ ] Ushahidi.io / SaaS solution

**Comment by jrtricafort** [comment] 2018-04-26 15:11
@crcommons Tagging you here for prioritization. Attempting to repro this myself now.

**Comment by kinstelli** [comment] 2018-04-26 15:27
Do we know how long this wait was? Under the data-providers process, this can take a very long time.

**Comment by jrtricafort** [comment] 2018-04-26 15:50
@StaicyG What tier (plan) is the deployment?

**Comment by rowasc** [comment] 2018-04-26 17:30
@aoduor @StaicyG can you get in touch with the user and ask them to check if the deployment finished? 
It's a tier 1 / free deployment so it was most likely an issue with the providers taking a long time because they run every hour.

**Comment by rowasc** [comment] 2018-04-26 17:59
@crcommons which status should I use here?

**Comment by crcommons** [comment] 2018-04-26 18:00
In development, I believe.

**Comment by jrtricafort** [comment] 2018-04-26 19:35
Downgrading this from p0 to p2 since we believe it is actually expected behavior. @StaicyG we will wait for you to let us know if the user got the CSV (or if they are able to try again and receive the CSV after 1 hour).

**Comment by rowasc** [comment] 2018-09-28 13:50
Closing, this is resolved.

**Closed by rowasc** 2018-09-28 13:50 UTC
Labels: Bug, P2 - Normal
