### ISSUE TITLE
COMRADES Language Dropdown text not appearing in Firefox

### ISSUE THREAD

**Issue by Shadrock** [ushahidi/platform#1840] opened 2017-06-30 17:27 UTC
### Expected behaviour
Click "Language" option at bottom of categories and immediately see list of available languages. 
### Actual behaviour
Clicking "Language" option at bottom of categories first opens up _another_ drop down menu called "select language" which you need to click _again_ (Yes, I know this is a UI issue), then the list of available languages pops up but appears blank: language names only appear on rollover (see screenshot below). This **does not** happen in Chrome.  
![screen shot 2017-06-30 at 11 22 44 am](https://user-images.githubusercontent.com/4574998/27747067-f3c3d708-5d86-11e7-9312-c85eb8ae8e97.png)
### Steps to reproduce the behaviour/error
Go to a deployment in Chrome and look at language menu.

**Comment by jshorland** [comment] 2018-02-27 23:59
I can't reproduce this.  closing.

**Closed by jshorland** 2018-02-27 23:59 UTC
Labels: Bug, COMRADES, P2 - Normal
