### ISSUE TITLE
Posts duplicated

### ISSUE THREAD

**Issue by gsvlopez** [ushahidi/platform#1696] opened 2017-04-14 14:45 UTC

**Comment by jshorland** [comment] 2017-04-14 15:13
hi @gsvlopez -- are you running a self-hosted deployment, or a .io deployment? Do you mind sharing the URL?

**Comment by gsvlopez** [comment] 2017-04-14 15:22
Hi Jess,

Sure - I was developing an initial deployment with your colleague Steven
Blumenfeld. It looks like this issue was fixed or it was just a temporary
issue, since the duplicated posts disappeared just after I submitted this.
There was however another issue we ran into when trying to save a task -
the task was "Verify this information", but the field I had added for the
Task (Provide Name) did not appear, so there was no way to complete the
task. I think Steven will be following up with support on this but I
thought I would mention that as well.

Here is the link to the map: https://hatespeechtracker.ushahidi.io

Best,
Giselle

**Comment by jshorland** [comment] 2017-04-14 15:23
Thank you for this info @gsvlopez — we’ll look into it ASAP.

**Comment by jshorland** [comment] 2017-04-14 15:38
@gsvlopez I haven't been able to replicate the task issue you noted above. I believe it might be a confusing design around how to save a task (which will ultimately get fixed by our auto save feature in #1584). For now, can you try adding the task and then saving survey itself and letting me know if the issue is still there? (See example at this link: http://d.pr/i/5Zsa)

**Comment by niccolov** [comment] 2017-04-19 13:42
Sometimes it happens to us too! If I'm logged in with the administrator of the survey sometimes I see some posts duplicated but not in orderd... it happens to see the lastes 5 posts and then again the 5 posts, the new 5 posts and again another repetition.

I solve reloading the page... and the problem dissapear.

**Closed** 2017-06-07 22:21 UTC
Labels: P0 - Unbreak now!
