### ISSUE TITLE
The search/filter pane should be scrolled to the top when you open it

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#2234] opened 2017-10-24 19:35 UTC
### Expected behaviour
When you open the search/filter pane, it should be scrolled all the way to the top of the pane
### Actual behaviour
It remains at the scroll place where you left it the last time you opened the pane
### Steps to reproduce the behaviour/error
Open search filter pane, scroll a bit, click away to close the pane, re-open it. 

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by jshorland** [comment] 2017-10-24 22:08
Confirmed that this bug still exists.

**Comment by rowasc** [comment] 2019-06-11 02:48
closing as duplicate of. https://github.com/ushahidi/platform/issues/2347

**Closed by rowasc** 2019-06-11 02:48 UTC
Labels: Community Task, Theme: Filters & Search
