### ISSUE TITLE
Grammar mistake in message on platform

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#1833] opened 2017-06-28 19:01 UTC
### Expected behaviour
- Add a basic post
### Actual behaviour
- Add to a basic post
### Steps to reproduce the behaviour/error
- Add a post of any survey type

**Comment by jshorland** [comment] 2017-09-27 11:10
Closing -- dupe of ushahidi/platform#1833

**Closed** 2017-09-27 11:11 UTC
Labels: Bug, P2 - Normal
