### ISSUE TITLE
Sandbox deployment redirects to "forbidden" page on initial access

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#2150] opened 2017-10-16 07:58 UTC
### Expected behaviour
I should get redirected to the map view of https://sandbox.uchaguzi.or.ke as a non logged in user, since it isn't a private deployment

### Actual behaviour
I get redirected to the access forbidden page when I click on sandbox.uchaguzi.or.ke

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [X] Ushahidi's QA environment
- [x] Other (explain): sandbox + all environments

**Comment by rjmackay** [comment] 2017-10-19 21:17
I can't reproduce this myself. @aoduor do you get the same issue in an incognito window? or only in your normal browser session? I wonder if its a caching issue causing the app to try to load private data even though you're logged out.

**Comment by rowasc** [comment] 2017-10-23 17:57
Note: this happens to all environments. Adding that and changing title to reflect it

**Comment by rowasc** [comment] 2017-10-23 17:58
This happens while using the app normally, not just on first access, AFAIK. It's been happening to the devs at  "random"

**Comment by rowasc** [comment] 2017-10-25 18:28
@jshorland is this fixed with the fix Robbie sent yesterday? I think it's the same issue

**Comment by jshorland** [comment] 2017-10-25 18:44
Yes! same issue and robbie's fix fixes this.

**Closed** 2017-10-26 01:09 UTC
Labels: 2chaguzi, 4, Bug, Dev Backlog, P1 - Immediate
