### ISSUE TITLE
Change category visibility to match pattern library

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1412] opened 2016-09-25 15:59 UTC
From same user having issues with images. @rjmackay, can you help ID the issue when you're back online today?:

Another problem keeps arising as well. While you've restored the pictures, our categories seem to keep going missing! I have taken a snip of the drop down filters bar and this is what happens,

The category not only dissapears here in the filters bar but also in the settings bar, where the categories were initially set. Besides, before this, when I select a certain categories used to appear in the task bar, below the deployment name, as shown in the right side of the below image but unfortunately now it does not. This is as shown in the picture below. 

Why does this happen? Can you help us fix it?
Now that the pictures issues have been partly resolved this last one day,at least this map is presentable. However I need it in its full working condition for the state goverment to view it and if they are in favour and support, perhaps subscribe to one of your paid versions of Ushahidi. Please treat this as an urgent request as well.

**Comment by jshorland** [comment] 2016-09-25 16:02
https://app.intercom.io/a/apps/hl5rfiga/inbox/all/conversations/6060959927

**Comment by rjmackay** [comment] 2016-09-26 02:53
This is because 1 category was only visible to logged in users

This is how it was set
<img width="907" alt="screenshot 2016-09-26 15 46 53" src="https://cloud.githubusercontent.com/assets/7965/18821263/23e0e396-8401-11e6-8b58-014400672134.png">

This is what it needed to be to be seen by everyone.
<img width="860" alt="screenshot 2016-09-26 15 46 59" src="https://cloud.githubusercontent.com/assets/7965/18821264/23e1e638-8401-11e6-9f10-7d0fe6474399.png">

I think we should update this UI and probably use the same style of role selector as seen elsewhere:
https://www.dropbox.com/s/dbnbt9ba8ofhdrq/Screenshot%202016-09-26%2015.52.56.png?dl=0

**Comment by rjmackay** [comment] 2016-09-26 02:54
Lower priority since this is fixed for the reporting user

**Comment by rjmackay** [comment] 2016-09-26 21:17
Correct UI for this is present on http://preview.ushahidi.com/platform-pattern-library/develop/assets/html/5_layouts/settings-category-edit.html

**Comment by Angamanga** [comment] 2016-12-06 14:36
I might mistake what the behaviour of the roles for the categories should do but I think I found an error. The roles selected in categories does not seem to do anything with the categories. They are visible to all users independent of what roles are set. A member can choose between all categories when creating a post and if a category that is only available for admins is set, it is still visible in posts for not logged in. Is this really correct behaviour?

**Comment by jshorland** [comment] 2016-12-08 19:27
@Angamanga This is not correct behavior. Do you mind creating a new issue for this and assigning to me so I can try to reproduce it on a hosted deployment?

**Comment by jshorland** [comment] 2016-12-08 19:32
QA: 
- patterns are now correct
- after making the "other" category only visible to admins in qa.ushahididev.com, I logged out and was still able to see "other" listed in categories as a logged out visitor to the deployment. @Angamanga good catch. @rjmackay do you want us to make a new issue for this?

**Comment by rjmackay** [comment] 2016-12-12 21:19
I suspect this could be a caching issue where the endpoints need to clear their local cache on log out.
We should try to fix that before this deploys

**Comment by Angamanga** [comment] 2017-01-02 13:13
@jshorland @rjmackay The issue with the categories being visible although they shouldn't was fixed through issue #1505 (was caused by the same problem) and can now be QA:ed.

**Comment by Angamanga** [comment] 2017-03-09 14:15
@jshorland Fixed in #1505 You can test on qa.ushahididev.com

**Comment by jshorland** [comment] 2017-04-12 01:01
Fixed. DEPLOY!

**Closed** 2017-04-20 13:52 UTC
