### ISSUE TITLE
Data Export settings item

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#2456] opened 2018-02-02 13:55 UTC
### Spec
- Add new settings-chapter to Pattern Library-layouts
- Add Data Export item to Settings list
  - Should only be available to Users with bulk data permission

![Screen Shot 2018-02-02 at 08.45.50.png](https://images.zenhubusercontent.com/5a6a44264b5806bc2bc4546d/f60fbb9c-acd2-4863-8b16-82fe9f872be8)

- Add Data Export view, controller, directive and route
- Add initial loading page
![Screen Shot 2018-02-02 at 08.48.35.png](https://images.zenhubusercontent.com/5a6a44264b5806bc2bc4546d/cbc95ee1-1e7c-4f8e-8ba5-d53368c4c255)

- Add "Export All Data" function
- Add "Select Fields" functions
- Add "Select Fields" view
![Screen Shot 2018-02-02 at 08.49.43.png](https://images.zenhubusercontent.com/5a6a44264b5806bc2bc4546d/f1e9b24d-28f2-411a-bee1-cc065a248cd0)
- Add export-in-progress to Pattern Library
- Add "Export in Progress" screens
![Screen Shot 2018-02-02 at 08.51.06.png](https://images.zenhubusercontent.com/5a6a44264b5806bc2bc4546d/96912e14-d266-46f7-a356-b8ad9a9f8269)

- Wire Data Export to Data Export Endpoint
- Add notification-window to pattern-library
- Add notification to tell user that Data Export is in Progress
![Screen Shot 2018-02-02 at 08.52.45.png](https://images.zenhubusercontent.com/5a6a44264b5806bc2bc4546d/867b3bbd-35e0-40e2-994f-5c978b5f5000)

- Create async notify function to receive update from Data Export Process sent via websockets and tell User when export is completed
 

### Test
- [ ] For users with bulk data permission, you should see the Data Export item in the Settings menu
- [ ] When you click on Data Export Settings menu item you should be taken to the Data Export view
- [ ] When you click on Export All Data, you should be taken to the Data Export in progress view and you should receive a message explaining the export is underway
  - [ ] The export message should contain the number of Posts to be exported
  - [ ] If you click Cancel on this message the export should be cancelled
- [ ] When the Export completes you should get an update notification telling you the file is ready to download
- { ] User can only request 1 download at a time

**Comment by rowasc** [comment] 2018-02-02 16:41
@Angamanga need a new layout for this, I think. Can you check?

**Comment by rowasc** [comment] 2018-02-02 20:54
@willdoran just realized. Do we want to do anything if an export is already being generated? I feel we should stop users from requesting exports if there is one in progress (requested by them) since people might get anxious if it has a delay and just try 10 times.

**Comment by rowasc** [comment] 2018-02-02 20:55
Other than that, it looks great!

**Comment by willdoran** [comment] 2018-02-05 18:34
That's a good idea. I'll add it to the spec

**Comment by Angamanga** [comment] 2018-02-14 14:53
This is a duplicate of #2405. closing.

**Closed by Angamanga** 2018-02-14 14:53 UTC
